// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package proto_item

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求背包信息
type C2SBag struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SBag) Reset()         { *m = C2SBag{} }
func (m *C2SBag) String() string { return proto.CompactTextString(m) }
func (*C2SBag) ProtoMessage()    {}
func (*C2SBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *C2SBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SBag.Unmarshal(m, b)
}
func (m *C2SBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SBag.Marshal(b, m, deterministic)
}
func (m *C2SBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SBag.Merge(m, src)
}
func (m *C2SBag) XXX_Size() int {
	return xxx_messageInfo_C2SBag.Size(m)
}
func (m *C2SBag) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SBag.DiscardUnknown(m)
}

var xxx_messageInfo_C2SBag proto.InternalMessageInfo

type S2CBag struct {
	Bag                  map[int32]int32 `protobuf:"bytes,1,rep,name=Bag,proto3" json:"Bag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *S2CBag) Reset()         { *m = S2CBag{} }
func (m *S2CBag) String() string { return proto.CompactTextString(m) }
func (*S2CBag) ProtoMessage()    {}
func (*S2CBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *S2CBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CBag.Unmarshal(m, b)
}
func (m *S2CBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CBag.Marshal(b, m, deterministic)
}
func (m *S2CBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CBag.Merge(m, src)
}
func (m *S2CBag) XXX_Size() int {
	return xxx_messageInfo_S2CBag.Size(m)
}
func (m *S2CBag) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CBag.DiscardUnknown(m)
}

var xxx_messageInfo_S2CBag proto.InternalMessageInfo

func (m *S2CBag) GetBag() map[int32]int32 {
	if m != nil {
		return m.Bag
	}
	return nil
}

// 道具数量变化推送
type PushChange struct {
	Change               map[int32]int32 `protobuf:"bytes,1,rep,name=Change,proto3" json:"Change,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushChange) Reset()         { *m = PushChange{} }
func (m *PushChange) String() string { return proto.CompactTextString(m) }
func (*PushChange) ProtoMessage()    {}
func (*PushChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *PushChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChange.Unmarshal(m, b)
}
func (m *PushChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChange.Marshal(b, m, deterministic)
}
func (m *PushChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChange.Merge(m, src)
}
func (m *PushChange) XXX_Size() int {
	return xxx_messageInfo_PushChange.Size(m)
}
func (m *PushChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushChange proto.InternalMessageInfo

func (m *PushChange) GetChange() map[int32]int32 {
	if m != nil {
		return m.Change
	}
	return nil
}

// 使用道具
type C2SUseItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	ItemNum              int32    `protobuf:"varint,2,opt,name=ItemNum,proto3" json:"ItemNum,omitempty"`
	AppointId            int32    `protobuf:"varint,3,opt,name=AppointId,proto3" json:"AppointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUseItem) Reset()         { *m = C2SUseItem{} }
func (m *C2SUseItem) String() string { return proto.CompactTextString(m) }
func (*C2SUseItem) ProtoMessage()    {}
func (*C2SUseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *C2SUseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUseItem.Unmarshal(m, b)
}
func (m *C2SUseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUseItem.Marshal(b, m, deterministic)
}
func (m *C2SUseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUseItem.Merge(m, src)
}
func (m *C2SUseItem) XXX_Size() int {
	return xxx_messageInfo_C2SUseItem.Size(m)
}
func (m *C2SUseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUseItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUseItem proto.InternalMessageInfo

func (m *C2SUseItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *C2SUseItem) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *C2SUseItem) GetAppointId() int32 {
	if m != nil {
		return m.AppointId
	}
	return 0
}

type S2CUseItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CUseItem) Reset()         { *m = S2CUseItem{} }
func (m *S2CUseItem) String() string { return proto.CompactTextString(m) }
func (*S2CUseItem) ProtoMessage()    {}
func (*S2CUseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *S2CUseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUseItem.Unmarshal(m, b)
}
func (m *S2CUseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUseItem.Marshal(b, m, deterministic)
}
func (m *S2CUseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUseItem.Merge(m, src)
}
func (m *S2CUseItem) XXX_Size() int {
	return xxx_messageInfo_S2CUseItem.Size(m)
}
func (m *S2CUseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUseItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUseItem proto.InternalMessageInfo

func (m *S2CUseItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 合成道具
type C2SCompositionItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SCompositionItem) Reset()         { *m = C2SCompositionItem{} }
func (m *C2SCompositionItem) String() string { return proto.CompactTextString(m) }
func (*C2SCompositionItem) ProtoMessage()    {}
func (*C2SCompositionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *C2SCompositionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SCompositionItem.Unmarshal(m, b)
}
func (m *C2SCompositionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SCompositionItem.Marshal(b, m, deterministic)
}
func (m *C2SCompositionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SCompositionItem.Merge(m, src)
}
func (m *C2SCompositionItem) XXX_Size() int {
	return xxx_messageInfo_C2SCompositionItem.Size(m)
}
func (m *C2SCompositionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SCompositionItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SCompositionItem proto.InternalMessageInfo

func (m *C2SCompositionItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type S2CCompositionItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CCompositionItem) Reset()         { *m = S2CCompositionItem{} }
func (m *S2CCompositionItem) String() string { return proto.CompactTextString(m) }
func (*S2CCompositionItem) ProtoMessage()    {}
func (*S2CCompositionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *S2CCompositionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CCompositionItem.Unmarshal(m, b)
}
func (m *S2CCompositionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CCompositionItem.Marshal(b, m, deterministic)
}
func (m *S2CCompositionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CCompositionItem.Merge(m, src)
}
func (m *S2CCompositionItem) XXX_Size() int {
	return xxx_messageInfo_S2CCompositionItem.Size(m)
}
func (m *S2CCompositionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CCompositionItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CCompositionItem proto.InternalMessageInfo

func (m *S2CCompositionItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 出售道具
type C2SSellItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SSellItem) Reset()         { *m = C2SSellItem{} }
func (m *C2SSellItem) String() string { return proto.CompactTextString(m) }
func (*C2SSellItem) ProtoMessage()    {}
func (*C2SSellItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *C2SSellItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SSellItem.Unmarshal(m, b)
}
func (m *C2SSellItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SSellItem.Marshal(b, m, deterministic)
}
func (m *C2SSellItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SSellItem.Merge(m, src)
}
func (m *C2SSellItem) XXX_Size() int {
	return xxx_messageInfo_C2SSellItem.Size(m)
}
func (m *C2SSellItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SSellItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SSellItem proto.InternalMessageInfo

func (m *C2SSellItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type S2CSellItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CSellItem) Reset()         { *m = S2CSellItem{} }
func (m *S2CSellItem) String() string { return proto.CompactTextString(m) }
func (*S2CSellItem) ProtoMessage()    {}
func (*S2CSellItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *S2CSellItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CSellItem.Unmarshal(m, b)
}
func (m *S2CSellItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CSellItem.Marshal(b, m, deterministic)
}
func (m *S2CSellItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CSellItem.Merge(m, src)
}
func (m *S2CSellItem) XXX_Size() int {
	return xxx_messageInfo_S2CSellItem.Size(m)
}
func (m *S2CSellItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CSellItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CSellItem proto.InternalMessageInfo

func (m *S2CSellItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 推送奖励弹框
type PushPopReward struct {
	Items                map[int32]int32 `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Src                  int32           `protobuf:"varint,2,opt,name=Src,proto3" json:"Src,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushPopReward) Reset()         { *m = PushPopReward{} }
func (m *PushPopReward) String() string { return proto.CompactTextString(m) }
func (*PushPopReward) ProtoMessage()    {}
func (*PushPopReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *PushPopReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPopReward.Unmarshal(m, b)
}
func (m *PushPopReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPopReward.Marshal(b, m, deterministic)
}
func (m *PushPopReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPopReward.Merge(m, src)
}
func (m *PushPopReward) XXX_Size() int {
	return xxx_messageInfo_PushPopReward.Size(m)
}
func (m *PushPopReward) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPopReward.DiscardUnknown(m)
}

var xxx_messageInfo_PushPopReward proto.InternalMessageInfo

func (m *PushPopReward) GetItems() map[int32]int32 {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PushPopReward) GetSrc() int32 {
	if m != nil {
		return m.Src
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SBag)(nil), "Proto.Item.C2SBag")
	proto.RegisterType((*S2CBag)(nil), "Proto.Item.S2CBag")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Item.S2CBag.BagEntry")
	proto.RegisterType((*PushChange)(nil), "Proto.Item.PushChange")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Item.PushChange.ChangeEntry")
	proto.RegisterType((*C2SUseItem)(nil), "Proto.Item.C2SUseItem")
	proto.RegisterType((*S2CUseItem)(nil), "Proto.Item.S2CUseItem")
	proto.RegisterType((*C2SCompositionItem)(nil), "Proto.Item.C2SCompositionItem")
	proto.RegisterType((*S2CCompositionItem)(nil), "Proto.Item.S2CCompositionItem")
	proto.RegisterType((*C2SSellItem)(nil), "Proto.Item.C2SSellItem")
	proto.RegisterType((*S2CSellItem)(nil), "Proto.Item.S2CSellItem")
	proto.RegisterType((*PushPopReward)(nil), "Proto.Item.PushPopReward")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Item.PushPopReward.ItemsEntry")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0x56, 0xad, 0xba, 0xa3, 0xba, 0x94, 0xa5, 0x14, 0xa1, 0xb6, 0x60, 0x44, 0x0b, 0x3e,
	0xb4, 0x2a, 0xdd, 0x42, 0x70, 0x7c, 0x49, 0xa2, 0xc5, 0x04, 0x5f, 0x82, 0xd0, 0x92, 0x4b, 0x08,
	0x04, 0xd9, 0x5a, 0x64, 0x11, 0x49, 0x2b, 0xf4, 0x91, 0xe0, 0x73, 0x7e, 0x44, 0xfe, 0x6e, 0x58,
	0xed, 0xda, 0x32, 0x3e, 0x18, 0xec, 0xd3, 0xbc, 0x79, 0xfb, 0x66, 0xde, 0x2e, 0x33, 0x0b, 0x90,
	0xd4, 0x2c, 0x73, 0x8b, 0x92, 0xd7, 0x1c, 0x81, 0x2f, 0x82, 0x3b, 0xaf, 0x59, 0x66, 0x7f, 0x2c,
	0x9a, 0x45, 0x9a, 0x2c, 0xe5, 0x89, 0x33, 0x00, 0x83, 0x60, 0xea, 0x85, 0xb1, 0xc3, 0xc1, 0xa0,
	0x98, 0x78, 0x61, 0x8c, 0xfe, 0x80, 0xee, 0x85, 0xb1, 0xa5, 0x8d, 0xf4, 0xb1, 0x89, 0xbf, 0xb9,
	0x5d, 0xad, 0x2b, 0x05, 0xae, 0x17, 0xc6, 0xb3, 0xbc, 0x2e, 0xd7, 0x81, 0xd0, 0xd9, 0x67, 0x30,
	0xd8, 0x10, 0xe8, 0x33, 0xe8, 0x8f, 0x6c, 0x6d, 0x69, 0x23, 0x6d, 0xdc, 0x0f, 0x04, 0x44, 0x5f,
	0xa0, 0xff, 0x14, 0xa6, 0x0d, 0xb3, 0x7a, 0x2d, 0x27, 0x93, 0x69, 0x6f, 0xa2, 0x39, 0x2f, 0x1a,
	0x80, 0xdf, 0x54, 0x2b, 0xb2, 0x0a, 0xf3, 0x98, 0xa1, 0x29, 0x18, 0x12, 0x29, 0x63, 0x67, 0xd7,
	0xb8, 0xd3, 0xb9, 0x32, 0x48, 0x7f, 0x55, 0x61, 0x9f, 0x83, 0xb9, 0x43, 0x1f, 0x75, 0x8b, 0x7b,
	0x00, 0x82, 0xe9, 0x6d, 0xc5, 0x84, 0x0f, 0xfa, 0x0a, 0x86, 0x88, 0xf3, 0x48, 0x15, 0xab, 0x0c,
	0x59, 0xf0, 0x5e, 0xa0, 0x9b, 0x26, 0x53, 0x1d, 0x36, 0x29, 0xfa, 0x0e, 0x1f, 0xae, 0x8a, 0x82,
	0x27, 0x79, 0x3d, 0x8f, 0x2c, 0xbd, 0x3d, 0xeb, 0x08, 0xe7, 0x02, 0x80, 0x62, 0xb2, 0xe9, 0xfe,
	0x0f, 0xde, 0x2d, 0x79, 0xc4, 0xda, 0xde, 0x9f, 0xf0, 0x0f, 0xf5, 0x40, 0x5f, 0xce, 0x83, 0xf0,
	0x2c, 0xe3, 0xf9, 0xac, 0x2c, 0x79, 0x49, 0x78, 0xc4, 0x82, 0x56, 0xea, 0xfc, 0x06, 0x44, 0x30,
	0x25, 0x3c, 0x2b, 0x78, 0x95, 0xd4, 0x09, 0xcf, 0x0f, 0x5d, 0xd3, 0xb9, 0x06, 0x44, 0x31, 0xd9,
	0x57, 0x9f, 0x60, 0xfb, 0x0b, 0x4c, 0x82, 0x29, 0x65, 0x69, 0x7a, 0xd0, 0xef, 0x12, 0x4c, 0x8a,
	0xc9, 0x56, 0x76, 0x82, 0xd1, 0xab, 0x06, 0x43, 0x31, 0x5c, 0x9f, 0x17, 0x01, 0x7b, 0x0e, 0xcb,
	0x08, 0x4d, 0xa1, 0x2f, 0x9a, 0x55, 0x6a, 0x0d, 0x7e, 0xee, 0xaf, 0xc1, 0x56, 0xd9, 0x52, 0x95,
	0x5c, 0x04, 0x59, 0x22, 0x06, 0x4f, 0xcb, 0xa5, 0x1a, 0x91, 0x80, 0xf6, 0x04, 0xa0, 0x93, 0x1d,
	0xb3, 0x18, 0xde, 0xf0, 0xce, 0xfc, 0xdb, 0xfe, 0x91, 0x07, 0xf1, 0x91, 0x16, 0x46, 0x8b, 0xff,
	0xbf, 0x05, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x99, 0xe1, 0xb5, 0x57, 0x03, 0x00, 0x00,
}
