package dto

const (
	SUCCESS = 0

	ERR_SERVER_INTERNAL                  = 1
	ERR_PAY_ORDER_NOT_FOUND              = 2
	ERR_PAY_SIGN                         = 3
	ERR_INVITE_CODE_FAIL                 = 29
	ERR_DB                               = 1801
	ERR_ACCOUNT_EXISTS                   = 1802
	ERR_ACCOUNT_PASSWORD_FAILED          = 1803
	ERR_ACCOUNT_TYPE_UNKNOWN             = 1804
	ERR_ACCOUNT_NOT_FOUND                = 1805
	ERR_ACCOUNT_VERIFY_CODE_INCORRECT    = 1806
	ERR_ACCOUNT_GET_VERIFY_CODE_FAILED   = 1807
	ERR_ACCOUNT_REGISTER_CLOSED          = 1808
	ERR_ACCOUNT_LOGIN_SERVER_MAINTAIN    = 1809
	ERR_ACCOUNT_BANNED                   = 1810
	ERR_ACCOUNT_PARAMS_ERROR             = 1811
	ERR_ACCOUNT_CLIENT_VERSION_UNMATCHED = 1812
	ERR_ACCOUNT_SDK_TOKEN_AUTH_FAILED    = 1813
	ERR_ACCOUNT_SDK_TOKEN_EXPIRED        = 1814
	ERR_ACCOUNT_HAS_NO_NFT_HERO          = 1815
	ERR_ACCOUNT_FORCED_OFFLINE           = 1816
)
