// Code generated by main_server/tools/invoke_gen. DO NOT EDIT.

package invoke

import (
	"xfx/core/define"
	"xfx/core/model"
)

type CommonModClient struct {
	invoke Invoker
	Type   string
}

func CommonClient(invoker Invoker) CommonModClient {
	return CommonModClient{
		invoke: invoker,
		Type:   define.ModuleCommon,
	}
}

func (c CommonModClient) ReleaseRobot(robotId int32) {
	result, err := c.invoke.Invoke(c.Type, "releaseRobot", robotId)
	if err != nil {
		return
	}

	_ = result
	return
}

func (c CommonModClient) MatchRobot(mode int, startPower int64, endPower int64) (*model.Robot, error) {
	result, err := c.invoke.Invoke(c.Type, "matchRobot", mode, startPower, endPower)
	if err != nil {
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[*model.Robot](result)
	if err2 != nil {
		return nil, err2
	}
	return v, nil
}

func (c CommonModClient) MatchRobots(mode int, startPower int64, endPower int64, count int32) ([]*model.Robot, error) {
	result, err := c.invoke.Invoke(c.Type, "matchRobots", mode, startPower, endPower, count)
	if err != nil {
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[[]*model.Robot](result)
	if err2 != nil {
		return nil, err2
	}
	return v, nil
}

