// Code generated by main_server/tools/invoke_gen. DO NOT EDIT.

package invoke

import (
	"xfx/core/define"
	"xfx/main_server/messages"
	"xfx/pkg/agent"
	"xfx/pkg/log"
)

type LoginModClient struct {
	invoke Invoker
	Type   string
}

func LoginClient(invoker Invoker) LoginModClient {
	return LoginModClient{
		invoke: invoker,
		Type:   define.ModuleLogin,
	}
}

func (c LoginModClient) Login(msg *messages.Login) (*messages.LoginResult, error) {
	result, err := c.invoke.Invoke(c.Type, "login", msg)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "login", err)
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[*messages.LoginResult](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "login", err2)
		return nil, err2
	}
	return v, nil
}

func (c LoginModClient) Logout(playerId int64) (error) {
	result, err := c.invoke.Invoke(c.Type, "logout", playerId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "logout", err)
		return err
	}

	if result == nil {
		return nil
	}
	v, err2 := As[error](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "logout", err2)
		return err2
	}
	return v
}

func (c LoginModClient) Disconnect(playerId int64) (error) {
	result, err := c.invoke.Invoke(c.Type, "disconnect", playerId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "disconnect", err)
		return err
	}

	if result == nil {
		return nil
	}
	v, err2 := As[error](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "disconnect", err2)
		return err2
	}
	return v
}

func (c LoginModClient) CastAgent(playerId int64, msg any) {
	result, err := c.invoke.Invoke(c.Type, "castAgent", playerId, msg)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "castAgent", err)
		return
	}

	_ = result
	return
}

func (c LoginModClient) CastAgents(playerIds []int64, msg any) {
	result, err := c.invoke.Invoke(c.Type, "castAgents", playerIds, msg)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "castAgents", err)
		return
	}

	_ = result
	return
}

func (c LoginModClient) BoardCast(msg any) {
	result, err := c.invoke.Invoke(c.Type, "boardCast", msg)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "boardCast", err)
		return
	}

	_ = result
	return
}

func (c LoginModClient) IsOnline(id int64) (bool) {
	result, err := c.invoke.Invoke(c.Type, "isOnline", id)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "isOnline", err)
		return false
	}

	if result == nil {
		return false
	}

	v, err2 := As[bool](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "isOnline", err2)
		return false
	}
	return v
}

func (c LoginModClient) GetPlayerPid(dbId int64) (agent.PID) {
	result, err := c.invoke.Invoke(c.Type, "getPlayerPid", dbId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "getPlayerPid", err)
		return nil
	}

	if result == nil {
		return nil
	}

	v, err2 := As[agent.PID](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "getPlayerPid", err2)
		return nil
	}
	return v
}

