// Code generated by main_server/tools/invoke_gen. DO NOT EDIT.

package invoke

import (
	"xfx/core/define"
	"xfx/core/model"
	"xfx/pkg/log"
)

type TransactionModClient struct {
	invoke Invoker
	Type   string
}

func TransactionClient(invoker Invoker) TransactionModClient {
	return TransactionModClient{
		invoke: invoker,
		Type:   define.ModuleTransaction,
	}
}

func (c TransactionModClient) CreateOrder(sellerId int64, sellerName string, attachmentData *model.AttachmentData, priceType int32, price int32, orderType int32, receiverId int64, receiverName string) (*model.TransactionOrder) {
	result, err := c.invoke.Invoke(c.Type, "CreateOrder", sellerId, sellerName, attachmentData, priceType, price, orderType, receiverId, receiverName)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "CreateOrder", err)
		return nil
	}

	if result == nil {
		return nil
	}

	v, err2 := As[*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "CreateOrder", err2)
		return nil
	}
	return v
}

func (c TransactionModClient) UpdateOrder(orderId int64, _order *model.TransactionOrder) (*model.TransactionOrder, error) {
	result, err := c.invoke.Invoke(c.Type, "UpdateOrder", orderId, _order)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "UpdateOrder", err)
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "UpdateOrder", err2)
		return nil, err2
	}
	return v, nil
}

func (c TransactionModClient) GetOrder(orderId int64) (*model.TransactionOrder) {
	result, err := c.invoke.Invoke(c.Type, "GetOrder", orderId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "GetOrder", err)
		return nil
	}

	if result == nil {
		return nil
	}

	v, err2 := As[*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "GetOrder", err2)
		return nil
	}
	return v
}

func (c TransactionModClient) GetOrderList() ([]*model.TransactionOrder) {
	result, err := c.invoke.Invoke(c.Type, "GetOrderList")
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "GetOrderList", err)
		return nil
	}

	if result == nil {
		return nil
	}

	v, err2 := As[[]*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "GetOrderList", err2)
		return nil
	}
	return v
}

func (c TransactionModClient) ProcessOrder(orderId int64, buyerId int64) (*model.TransactionOrder, error) {
	result, err := c.invoke.Invoke(c.Type, "ProcessOrder", orderId, buyerId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "ProcessOrder", err)
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "ProcessOrder", err2)
		return nil, err2
	}
	return v, nil
}

func (c TransactionModClient) CancelOrder(orderId int64, playerId int64) (*model.TransactionOrder, error) {
	result, err := c.invoke.Invoke(c.Type, "CancelOrder", orderId, playerId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "CancelOrder", err)
		return nil, err
	}

	if result == nil {
		return nil, nil
	}

	v, err2 := As[*model.TransactionOrder](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "CancelOrder", err2)
		return nil, err2
	}
	return v, nil
}

func (c TransactionModClient) AddTransactionRecord(playerId int64, record *model.TransactionRecord) {
	result, err := c.invoke.Invoke(c.Type, "addTransactionRecord", playerId, record)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "addTransactionRecord", err)
		return
	}

	_ = result
	return
}

func (c TransactionModClient) GetTransactionRecords(playerId int64) ([]*model.TransactionRecord) {
	result, err := c.invoke.Invoke(c.Type, "getTransactionRecords", playerId)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "getTransactionRecords", err)
		return nil
	}

	if result == nil {
		return nil
	}

	v, err2 := As[[]*model.TransactionRecord](result)
	if err2 != nil {
		log.Error("invoke result type assert failed: type=%s method=%s err=%v", c.Type, "getTransactionRecords", err2)
		return nil
	}
	return v
}

func (c TransactionModClient) UpdateTransactionRecords(playerId int64, record *model.TransactionRecord) {
	result, err := c.invoke.Invoke(c.Type, "updateTransactionRecords", playerId, record)
	if err != nil {
		log.Error("invoke failed: type=%s method=%s err=%v", c.Type, "updateTransactionRecords", err)
		return
	}

	_ = result
	return
}

