// Code generated by protoc-gen-go. DO NOT EDIT.
// source: danaotiangong.proto

package proto_danaotiangong

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取大闹天宫
type C2SReqTiangongData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SReqTiangongData) Reset()         { *m = C2SReqTiangongData{} }
func (m *C2SReqTiangongData) String() string { return proto.CompactTextString(m) }
func (*C2SReqTiangongData) ProtoMessage()    {}
func (*C2SReqTiangongData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{0}
}

func (m *C2SReqTiangongData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SReqTiangongData.Unmarshal(m, b)
}
func (m *C2SReqTiangongData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SReqTiangongData.Marshal(b, m, deterministic)
}
func (m *C2SReqTiangongData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SReqTiangongData.Merge(m, src)
}
func (m *C2SReqTiangongData) XXX_Size() int {
	return xxx_messageInfo_C2SReqTiangongData.Size(m)
}
func (m *C2SReqTiangongData) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SReqTiangongData.DiscardUnknown(m)
}

var xxx_messageInfo_C2SReqTiangongData proto.InternalMessageInfo

// 返回大闹天宫数据
type S2CRespTiangongData struct {
	Frequency            int32    `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	Stage                int32    `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	DaychallengeNum      int32    `protobuf:"varint,3,opt,name=daychallengeNum,proto3" json:"daychallengeNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRespTiangongData) Reset()         { *m = S2CRespTiangongData{} }
func (m *S2CRespTiangongData) String() string { return proto.CompactTextString(m) }
func (*S2CRespTiangongData) ProtoMessage()    {}
func (*S2CRespTiangongData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{1}
}

func (m *S2CRespTiangongData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRespTiangongData.Unmarshal(m, b)
}
func (m *S2CRespTiangongData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRespTiangongData.Marshal(b, m, deterministic)
}
func (m *S2CRespTiangongData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRespTiangongData.Merge(m, src)
}
func (m *S2CRespTiangongData) XXX_Size() int {
	return xxx_messageInfo_S2CRespTiangongData.Size(m)
}
func (m *S2CRespTiangongData) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRespTiangongData.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRespTiangongData proto.InternalMessageInfo

func (m *S2CRespTiangongData) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

func (m *S2CRespTiangongData) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *S2CRespTiangongData) GetDaychallengeNum() int32 {
	if m != nil {
		return m.DaychallengeNum
	}
	return 0
}

//请求记录
type C2SReqTiangongRecord struct {
	Stage                int32    `protobuf:"varint,1,opt,name=stage,proto3" json:"stage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SReqTiangongRecord) Reset()         { *m = C2SReqTiangongRecord{} }
func (m *C2SReqTiangongRecord) String() string { return proto.CompactTextString(m) }
func (*C2SReqTiangongRecord) ProtoMessage()    {}
func (*C2SReqTiangongRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{2}
}

func (m *C2SReqTiangongRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SReqTiangongRecord.Unmarshal(m, b)
}
func (m *C2SReqTiangongRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SReqTiangongRecord.Marshal(b, m, deterministic)
}
func (m *C2SReqTiangongRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SReqTiangongRecord.Merge(m, src)
}
func (m *C2SReqTiangongRecord) XXX_Size() int {
	return xxx_messageInfo_C2SReqTiangongRecord.Size(m)
}
func (m *C2SReqTiangongRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SReqTiangongRecord.DiscardUnknown(m)
}

var xxx_messageInfo_C2SReqTiangongRecord proto.InternalMessageInfo

func (m *C2SReqTiangongRecord) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

type S2CRespTiangongRecord struct {
	Records              []*TiangongRecordItem `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2CRespTiangongRecord) Reset()         { *m = S2CRespTiangongRecord{} }
func (m *S2CRespTiangongRecord) String() string { return proto.CompactTextString(m) }
func (*S2CRespTiangongRecord) ProtoMessage()    {}
func (*S2CRespTiangongRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{3}
}

func (m *S2CRespTiangongRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRespTiangongRecord.Unmarshal(m, b)
}
func (m *S2CRespTiangongRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRespTiangongRecord.Marshal(b, m, deterministic)
}
func (m *S2CRespTiangongRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRespTiangongRecord.Merge(m, src)
}
func (m *S2CRespTiangongRecord) XXX_Size() int {
	return xxx_messageInfo_S2CRespTiangongRecord.Size(m)
}
func (m *S2CRespTiangongRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRespTiangongRecord.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRespTiangongRecord proto.InternalMessageInfo

func (m *S2CRespTiangongRecord) GetRecords() []*TiangongRecordItem {
	if m != nil {
		return m.Records
	}
	return nil
}

type TiangongRecordItem struct {
	Id                   int32                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Time                 int32                                      `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	IsWin                bool                                       `protobuf:"varint,4,opt,name=isWin,proto3" json:"isWin,omitempty"`
	HeroId               []*proto_public.CommonPlayerLineUpItemInfo `protobuf:"bytes,5,rep,name=HeroId,proto3" json:"HeroId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *TiangongRecordItem) Reset()         { *m = TiangongRecordItem{} }
func (m *TiangongRecordItem) String() string { return proto.CompactTextString(m) }
func (*TiangongRecordItem) ProtoMessage()    {}
func (*TiangongRecordItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{4}
}

func (m *TiangongRecordItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TiangongRecordItem.Unmarshal(m, b)
}
func (m *TiangongRecordItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TiangongRecordItem.Marshal(b, m, deterministic)
}
func (m *TiangongRecordItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TiangongRecordItem.Merge(m, src)
}
func (m *TiangongRecordItem) XXX_Size() int {
	return xxx_messageInfo_TiangongRecordItem.Size(m)
}
func (m *TiangongRecordItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TiangongRecordItem.DiscardUnknown(m)
}

var xxx_messageInfo_TiangongRecordItem proto.InternalMessageInfo

func (m *TiangongRecordItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TiangongRecordItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TiangongRecordItem) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TiangongRecordItem) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *TiangongRecordItem) GetHeroId() []*proto_public.CommonPlayerLineUpItemInfo {
	if m != nil {
		return m.HeroId
	}
	return nil
}

//请求战斗
type C2SChallengeDanaoTiangongBattle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChallengeDanaoTiangongBattle) Reset()         { *m = C2SChallengeDanaoTiangongBattle{} }
func (m *C2SChallengeDanaoTiangongBattle) String() string { return proto.CompactTextString(m) }
func (*C2SChallengeDanaoTiangongBattle) ProtoMessage()    {}
func (*C2SChallengeDanaoTiangongBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{5}
}

func (m *C2SChallengeDanaoTiangongBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChallengeDanaoTiangongBattle.Unmarshal(m, b)
}
func (m *C2SChallengeDanaoTiangongBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChallengeDanaoTiangongBattle.Marshal(b, m, deterministic)
}
func (m *C2SChallengeDanaoTiangongBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChallengeDanaoTiangongBattle.Merge(m, src)
}
func (m *C2SChallengeDanaoTiangongBattle) XXX_Size() int {
	return xxx_messageInfo_C2SChallengeDanaoTiangongBattle.Size(m)
}
func (m *C2SChallengeDanaoTiangongBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChallengeDanaoTiangongBattle.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChallengeDanaoTiangongBattle proto.InternalMessageInfo

type S2CChallengeDanaoTiangongBattle struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	BattleId             int64                        `protobuf:"varint,2,opt,name=BattleId,proto3" json:"BattleId,omitempty"`
	Data                 *proto_public.BattleHeroData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	StageId              int32                        `protobuf:"varint,4,opt,name=StageId,proto3" json:"StageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CChallengeDanaoTiangongBattle) Reset()         { *m = S2CChallengeDanaoTiangongBattle{} }
func (m *S2CChallengeDanaoTiangongBattle) String() string { return proto.CompactTextString(m) }
func (*S2CChallengeDanaoTiangongBattle) ProtoMessage()    {}
func (*S2CChallengeDanaoTiangongBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{6}
}

func (m *S2CChallengeDanaoTiangongBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChallengeDanaoTiangongBattle.Unmarshal(m, b)
}
func (m *S2CChallengeDanaoTiangongBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChallengeDanaoTiangongBattle.Marshal(b, m, deterministic)
}
func (m *S2CChallengeDanaoTiangongBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChallengeDanaoTiangongBattle.Merge(m, src)
}
func (m *S2CChallengeDanaoTiangongBattle) XXX_Size() int {
	return xxx_messageInfo_S2CChallengeDanaoTiangongBattle.Size(m)
}
func (m *S2CChallengeDanaoTiangongBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChallengeDanaoTiangongBattle.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChallengeDanaoTiangongBattle proto.InternalMessageInfo

func (m *S2CChallengeDanaoTiangongBattle) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CChallengeDanaoTiangongBattle) GetBattleId() int64 {
	if m != nil {
		return m.BattleId
	}
	return 0
}

func (m *S2CChallengeDanaoTiangongBattle) GetData() *proto_public.BattleHeroData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *S2CChallengeDanaoTiangongBattle) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

//战斗结算
type S2CTiangongSettle struct {
	IsWin                bool                 `protobuf:"varint,1,opt,name=isWin,proto3" json:"isWin,omitempty"`
	Stage                int32                `protobuf:"varint,2,opt,name=stage,proto3" json:"stage,omitempty"`
	DaychallengeNum      int32                `protobuf:"varint,3,opt,name=daychallengeNum,proto3" json:"daychallengeNum,omitempty"`
	Awards               []*proto_public.Item `protobuf:"bytes,4,rep,name=awards,proto3" json:"awards,omitempty"`
	Yincangawards        []*proto_public.Item `protobuf:"bytes,5,rep,name=yincangawards,proto3" json:"yincangawards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S2CTiangongSettle) Reset()         { *m = S2CTiangongSettle{} }
func (m *S2CTiangongSettle) String() string { return proto.CompactTextString(m) }
func (*S2CTiangongSettle) ProtoMessage()    {}
func (*S2CTiangongSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_0819b9997e98abdd, []int{7}
}

func (m *S2CTiangongSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CTiangongSettle.Unmarshal(m, b)
}
func (m *S2CTiangongSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CTiangongSettle.Marshal(b, m, deterministic)
}
func (m *S2CTiangongSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CTiangongSettle.Merge(m, src)
}
func (m *S2CTiangongSettle) XXX_Size() int {
	return xxx_messageInfo_S2CTiangongSettle.Size(m)
}
func (m *S2CTiangongSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CTiangongSettle.DiscardUnknown(m)
}

var xxx_messageInfo_S2CTiangongSettle proto.InternalMessageInfo

func (m *S2CTiangongSettle) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *S2CTiangongSettle) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *S2CTiangongSettle) GetDaychallengeNum() int32 {
	if m != nil {
		return m.DaychallengeNum
	}
	return 0
}

func (m *S2CTiangongSettle) GetAwards() []*proto_public.Item {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *S2CTiangongSettle) GetYincangawards() []*proto_public.Item {
	if m != nil {
		return m.Yincangawards
	}
	return nil
}

func init() {
	proto.RegisterType((*C2SReqTiangongData)(nil), "Proto.Danaotiangong.C2SReqTiangongData")
	proto.RegisterType((*S2CRespTiangongData)(nil), "Proto.Danaotiangong.S2CRespTiangongData")
	proto.RegisterType((*C2SReqTiangongRecord)(nil), "Proto.Danaotiangong.C2SReqTiangongRecord")
	proto.RegisterType((*S2CRespTiangongRecord)(nil), "Proto.Danaotiangong.S2CRespTiangongRecord")
	proto.RegisterType((*TiangongRecordItem)(nil), "Proto.Danaotiangong.TiangongRecordItem")
	proto.RegisterType((*C2SChallengeDanaoTiangongBattle)(nil), "Proto.Danaotiangong.C2SChallengeDanaoTiangongBattle")
	proto.RegisterType((*S2CChallengeDanaoTiangongBattle)(nil), "Proto.Danaotiangong.S2CChallengeDanaoTiangongBattle")
	proto.RegisterType((*S2CTiangongSettle)(nil), "Proto.Danaotiangong.S2CTiangongSettle")
}

func init() {
	proto.RegisterFile("danaotiangong.proto", fileDescriptor_0819b9997e98abdd)
}

var fileDescriptor_0819b9997e98abdd = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x86, 0xe5, 0xdd, 0x64, 0xdb, 0x4e, 0xa1, 0x08, 0xef, 0x82, 0xa2, 0xaa, 0xa8, 0x4b, 0x2e,
	0x44, 0x08, 0x2d, 0x10, 0x2e, 0x1c, 0xa1, 0x29, 0x12, 0x91, 0x10, 0x5a, 0x39, 0x20, 0xa4, 0x5e,
	0x90, 0x1b, 0xbb, 0xc1, 0x52, 0x62, 0x6f, 0x1d, 0xaf, 0xd0, 0xbe, 0x0f, 0x8f, 0xc1, 0x3b, 0xf0,
	0x4a, 0x28, 0x93, 0xa4, 0xdd, 0x94, 0xc2, 0x85, 0x53, 0x3c, 0x33, 0xff, 0x58, 0xdf, 0xfc, 0x9e,
	0xc0, 0x54, 0x70, 0xcd, 0x8d, 0x53, 0x5c, 0x17, 0x46, 0x17, 0x8b, 0x95, 0x35, 0xce, 0xd0, 0xe9,
	0xb2, 0xf9, 0x2c, 0x4e, 0xb7, 0x4b, 0x87, 0x77, 0x56, 0xeb, 0xf3, 0x52, 0xe5, 0xad, 0x24, 0x9c,
	0x01, 0x4d, 0xe2, 0x8c, 0xc9, 0xcb, 0x4f, 0x5d, 0xfd, 0x94, 0x3b, 0x1e, 0xd6, 0x30, 0xcd, 0xe2,
	0x84, 0xc9, 0x7a, 0xb5, 0x9d, 0xa6, 0x47, 0xb0, 0x77, 0x61, 0xe5, 0xe5, 0x5a, 0xea, 0x7c, 0x13,
	0x90, 0x39, 0x89, 0x7c, 0x76, 0x9d, 0xa0, 0x33, 0xf0, 0x6b, 0xc7, 0x0b, 0x19, 0x8c, 0xb0, 0xd2,
	0x06, 0x34, 0x82, 0x7b, 0x82, 0x6f, 0xf2, 0x6f, 0xbc, 0x2c, 0xa5, 0x2e, 0xe4, 0xc7, 0x75, 0x15,
	0x8c, 0xb1, 0x7e, 0x33, 0x1d, 0x3e, 0x83, 0xd9, 0x10, 0x85, 0xc9, 0xdc, 0x58, 0x71, 0x7d, 0x2f,
	0xd9, 0xba, 0x37, 0x3c, 0x83, 0x07, 0x37, 0x10, 0x3b, 0xf9, 0x5b, 0xd8, 0xb1, 0x78, 0xaa, 0x03,
	0x32, 0x1f, 0x47, 0xfb, 0xf1, 0x93, 0xc5, 0x2d, 0x36, 0x2c, 0x86, 0x5d, 0xa9, 0x93, 0x15, 0xeb,
	0xfb, 0xc2, 0x1f, 0x04, 0xe8, 0x9f, 0x75, 0x7a, 0x00, 0x23, 0x25, 0x3a, 0x8a, 0x91, 0x12, 0x94,
	0x82, 0xa7, 0x79, 0xd5, 0xce, 0xbb, 0xc7, 0xf0, 0xdc, 0xe4, 0x9c, 0xaa, 0x64, 0x37, 0x23, 0x9e,
	0x9b, 0x01, 0x54, 0xfd, 0x45, 0xe9, 0xc0, 0x9b, 0x93, 0x68, 0x97, 0xb5, 0x01, 0x7d, 0x03, 0x93,
	0xf7, 0xd2, 0x9a, 0x54, 0x04, 0x3e, 0x62, 0x46, 0x1d, 0xe6, 0xb2, 0x7d, 0x9e, 0xc4, 0x54, 0x95,
	0xd1, 0xcb, 0x92, 0x6f, 0xa4, 0xfd, 0xa0, 0xb4, 0xfc, 0xbc, 0x6a, 0x18, 0x52, 0x7d, 0x61, 0x58,
	0xd7, 0x17, 0x3e, 0x86, 0xe3, 0x24, 0xce, 0x92, 0xde, 0x43, 0x9c, 0xaf, 0xc7, 0x3e, 0xe1, 0xce,
	0x95, 0x32, 0xfc, 0x49, 0xe0, 0x38, 0x8b, 0x93, 0x7f, 0x69, 0xe8, 0x4b, 0xf0, 0x72, 0x23, 0x5a,
	0x7b, 0x0f, 0xe2, 0x47, 0xb7, 0x61, 0xbc, 0xb3, 0xd6, 0xd8, 0xc4, 0x08, 0xc9, 0x50, 0x4a, 0x0f,
	0x61, 0xb7, 0x6d, 0x4e, 0x05, 0x4e, 0x3f, 0x66, 0x57, 0x31, 0x7d, 0x01, 0x9e, 0xe0, 0x8e, 0xa3,
	0x03, 0xfb, 0xf1, 0xd1, 0xf0, 0xba, 0x56, 0xd5, 0xf0, 0x37, 0x0b, 0xc5, 0x50, 0x49, 0x03, 0xd8,
	0xc9, 0x9a, 0x37, 0x4d, 0x05, 0x3a, 0xe4, 0xb3, 0x3e, 0x0c, 0x7f, 0x11, 0xb8, 0x9f, 0xc5, 0x49,
	0x0f, 0x9c, 0x49, 0x04, 0xbe, 0xf2, 0x93, 0x6c, 0xfb, 0xf9, 0x9f, 0xeb, 0x47, 0x9f, 0xc2, 0x84,
	0x7f, 0xe7, 0xcd, 0xda, 0x78, 0xf8, 0x1e, 0x74, 0x48, 0x8e, 0x1b, 0xd2, 0x29, 0xe8, 0x6b, 0xb8,
	0xbb, 0x51, 0x3a, 0xe7, 0xba, 0xe8, 0x5a, 0xfc, 0xbf, 0xb6, 0x0c, 0x85, 0x27, 0x0f, 0xcf, 0x66,
	0xcf, 0xf1, 0xcf, 0xfb, 0x3a, 0xf8, 0x61, 0xcf, 0x27, 0x98, 0x7c, 0xf5, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0xba, 0xa2, 0xed, 0x37, 0xc8, 0x03, 0x00, 0x00,
}
