// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mail.proto

package proto_mail

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 邮件
type Mail struct {
	Id                   int64                          `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Infos                map[string]*MailInfo           `protobuf:"bytes,2,rep,name=Infos,proto3" json:"Infos,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OpenTime             int64                          `protobuf:"varint,3,opt,name=OpenTime,proto3" json:"OpenTime,omitempty"`
	CreateTime           int64                          `protobuf:"varint,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Item                 []*proto_public.Item           `protobuf:"bytes,5,rep,name=Item,proto3" json:"Item,omitempty"`
	GotItem              bool                           `protobuf:"varint,6,opt,name=GotItem,proto3" json:"GotItem,omitempty"`
	CfgId                int32                          `protobuf:"varint,7,opt,name=CfgId,proto3" json:"CfgId,omitempty"`
	Params               []string                       `protobuf:"bytes,8,rep,name=Params,proto3" json:"Params,omitempty"`
	ExpireTime           int64                          `protobuf:"varint,9,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
	SenderName           string                         `protobuf:"bytes,10,opt,name=SenderName,proto3" json:"SenderName,omitempty"`
	MailType             int32                          `protobuf:"varint,11,opt,name=MailType,proto3" json:"MailType,omitempty"`
	IsHasAttachment      bool                           `protobuf:"varint,12,opt,name=isHasAttachment,proto3" json:"isHasAttachment,omitempty"`
	AttachmentInfo       *proto_public.AttachmentOption `protobuf:"bytes,13,opt,name=AttachmentInfo,proto3" json:"AttachmentInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Mail) Reset()         { *m = Mail{} }
func (m *Mail) String() string { return proto.CompactTextString(m) }
func (*Mail) ProtoMessage()    {}
func (*Mail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{0}
}

func (m *Mail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mail.Unmarshal(m, b)
}
func (m *Mail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mail.Marshal(b, m, deterministic)
}
func (m *Mail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mail.Merge(m, src)
}
func (m *Mail) XXX_Size() int {
	return xxx_messageInfo_Mail.Size(m)
}
func (m *Mail) XXX_DiscardUnknown() {
	xxx_messageInfo_Mail.DiscardUnknown(m)
}

var xxx_messageInfo_Mail proto.InternalMessageInfo

func (m *Mail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Mail) GetInfos() map[string]*MailInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *Mail) GetOpenTime() int64 {
	if m != nil {
		return m.OpenTime
	}
	return 0
}

func (m *Mail) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Mail) GetItem() []*proto_public.Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Mail) GetGotItem() bool {
	if m != nil {
		return m.GotItem
	}
	return false
}

func (m *Mail) GetCfgId() int32 {
	if m != nil {
		return m.CfgId
	}
	return 0
}

func (m *Mail) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Mail) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *Mail) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *Mail) GetMailType() int32 {
	if m != nil {
		return m.MailType
	}
	return 0
}

func (m *Mail) GetIsHasAttachment() bool {
	if m != nil {
		return m.IsHasAttachment
	}
	return false
}

func (m *Mail) GetAttachmentInfo() *proto_public.AttachmentOption {
	if m != nil {
		return m.AttachmentInfo
	}
	return nil
}

type MailInfo struct {
	Title                string   `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailInfo) Reset()         { *m = MailInfo{} }
func (m *MailInfo) String() string { return proto.CompactTextString(m) }
func (*MailInfo) ProtoMessage()    {}
func (*MailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{1}
}

func (m *MailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailInfo.Unmarshal(m, b)
}
func (m *MailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailInfo.Marshal(b, m, deterministic)
}
func (m *MailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailInfo.Merge(m, src)
}
func (m *MailInfo) XXX_Size() int {
	return xxx_messageInfo_MailInfo.Size(m)
}
func (m *MailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MailInfo proto.InternalMessageInfo

func (m *MailInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MailInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 获取邮件列表
type C2SMailList struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SMailList) Reset()         { *m = C2SMailList{} }
func (m *C2SMailList) String() string { return proto.CompactTextString(m) }
func (*C2SMailList) ProtoMessage()    {}
func (*C2SMailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{2}
}

func (m *C2SMailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMailList.Unmarshal(m, b)
}
func (m *C2SMailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMailList.Marshal(b, m, deterministic)
}
func (m *C2SMailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMailList.Merge(m, src)
}
func (m *C2SMailList) XXX_Size() int {
	return xxx_messageInfo_C2SMailList.Size(m)
}
func (m *C2SMailList) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMailList.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMailList proto.InternalMessageInfo

func (m *C2SMailList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type S2CMailList struct {
	Mails                []*Mail  `protobuf:"bytes,1,rep,name=Mails,proto3" json:"Mails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CMailList) Reset()         { *m = S2CMailList{} }
func (m *S2CMailList) String() string { return proto.CompactTextString(m) }
func (*S2CMailList) ProtoMessage()    {}
func (*S2CMailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{3}
}

func (m *S2CMailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CMailList.Unmarshal(m, b)
}
func (m *S2CMailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CMailList.Marshal(b, m, deterministic)
}
func (m *S2CMailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CMailList.Merge(m, src)
}
func (m *S2CMailList) XXX_Size() int {
	return xxx_messageInfo_S2CMailList.Size(m)
}
func (m *S2CMailList) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CMailList.DiscardUnknown(m)
}

var xxx_messageInfo_S2CMailList proto.InternalMessageInfo

func (m *S2CMailList) GetMails() []*Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

// 打开邮件
type C2SOpenMail struct {
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SOpenMail) Reset()         { *m = C2SOpenMail{} }
func (m *C2SOpenMail) String() string { return proto.CompactTextString(m) }
func (*C2SOpenMail) ProtoMessage()    {}
func (*C2SOpenMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{4}
}

func (m *C2SOpenMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SOpenMail.Unmarshal(m, b)
}
func (m *C2SOpenMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SOpenMail.Marshal(b, m, deterministic)
}
func (m *C2SOpenMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SOpenMail.Merge(m, src)
}
func (m *C2SOpenMail) XXX_Size() int {
	return xxx_messageInfo_C2SOpenMail.Size(m)
}
func (m *C2SOpenMail) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SOpenMail.DiscardUnknown(m)
}

var xxx_messageInfo_C2SOpenMail proto.InternalMessageInfo

func (m *C2SOpenMail) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type S2COpenMail struct {
	Mail                 []*Mail  `protobuf:"bytes,1,rep,name=Mail,proto3" json:"Mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2COpenMail) Reset()         { *m = S2COpenMail{} }
func (m *S2COpenMail) String() string { return proto.CompactTextString(m) }
func (*S2COpenMail) ProtoMessage()    {}
func (*S2COpenMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{5}
}

func (m *S2COpenMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COpenMail.Unmarshal(m, b)
}
func (m *S2COpenMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COpenMail.Marshal(b, m, deterministic)
}
func (m *S2COpenMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COpenMail.Merge(m, src)
}
func (m *S2COpenMail) XXX_Size() int {
	return xxx_messageInfo_S2COpenMail.Size(m)
}
func (m *S2COpenMail) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COpenMail.DiscardUnknown(m)
}

var xxx_messageInfo_S2COpenMail proto.InternalMessageInfo

func (m *S2COpenMail) GetMail() []*Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

// 删除邮件
type C2SDelMail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Action               int32    `protobuf:"varint,2,opt,name=Action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SDelMail) Reset()         { *m = C2SDelMail{} }
func (m *C2SDelMail) String() string { return proto.CompactTextString(m) }
func (*C2SDelMail) ProtoMessage()    {}
func (*C2SDelMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{6}
}

func (m *C2SDelMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SDelMail.Unmarshal(m, b)
}
func (m *C2SDelMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SDelMail.Marshal(b, m, deterministic)
}
func (m *C2SDelMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SDelMail.Merge(m, src)
}
func (m *C2SDelMail) XXX_Size() int {
	return xxx_messageInfo_C2SDelMail.Size(m)
}
func (m *C2SDelMail) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SDelMail.DiscardUnknown(m)
}

var xxx_messageInfo_C2SDelMail proto.InternalMessageInfo

func (m *C2SDelMail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SDelMail) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type S2CDelMail struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CDelMail) Reset()         { *m = S2CDelMail{} }
func (m *S2CDelMail) String() string { return proto.CompactTextString(m) }
func (*S2CDelMail) ProtoMessage()    {}
func (*S2CDelMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{7}
}

func (m *S2CDelMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CDelMail.Unmarshal(m, b)
}
func (m *S2CDelMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CDelMail.Marshal(b, m, deterministic)
}
func (m *S2CDelMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CDelMail.Merge(m, src)
}
func (m *S2CDelMail) XXX_Size() int {
	return xxx_messageInfo_S2CDelMail.Size(m)
}
func (m *S2CDelMail) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CDelMail.DiscardUnknown(m)
}

var xxx_messageInfo_S2CDelMail proto.InternalMessageInfo

func (m *S2CDelMail) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *S2CDelMail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// 删除所有邮件
type C2SDelAllMail struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SDelAllMail) Reset()         { *m = C2SDelAllMail{} }
func (m *C2SDelAllMail) String() string { return proto.CompactTextString(m) }
func (*C2SDelAllMail) ProtoMessage()    {}
func (*C2SDelAllMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{8}
}

func (m *C2SDelAllMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SDelAllMail.Unmarshal(m, b)
}
func (m *C2SDelAllMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SDelAllMail.Marshal(b, m, deterministic)
}
func (m *C2SDelAllMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SDelAllMail.Merge(m, src)
}
func (m *C2SDelAllMail) XXX_Size() int {
	return xxx_messageInfo_C2SDelAllMail.Size(m)
}
func (m *C2SDelAllMail) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SDelAllMail.DiscardUnknown(m)
}

var xxx_messageInfo_C2SDelAllMail proto.InternalMessageInfo

type S2CDelAllMail struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CDelAllMail) Reset()         { *m = S2CDelAllMail{} }
func (m *S2CDelAllMail) String() string { return proto.CompactTextString(m) }
func (*S2CDelAllMail) ProtoMessage()    {}
func (*S2CDelAllMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{9}
}

func (m *S2CDelAllMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CDelAllMail.Unmarshal(m, b)
}
func (m *S2CDelAllMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CDelAllMail.Marshal(b, m, deterministic)
}
func (m *S2CDelAllMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CDelAllMail.Merge(m, src)
}
func (m *S2CDelAllMail) XXX_Size() int {
	return xxx_messageInfo_S2CDelAllMail.Size(m)
}
func (m *S2CDelAllMail) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CDelAllMail.DiscardUnknown(m)
}

var xxx_messageInfo_S2CDelAllMail proto.InternalMessageInfo

func (m *S2CDelAllMail) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

// 收取邮件道具请求
type C2SCollectMailItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Action               int32    `protobuf:"varint,2,opt,name=Action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SCollectMailItem) Reset()         { *m = C2SCollectMailItem{} }
func (m *C2SCollectMailItem) String() string { return proto.CompactTextString(m) }
func (*C2SCollectMailItem) ProtoMessage()    {}
func (*C2SCollectMailItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{10}
}

func (m *C2SCollectMailItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SCollectMailItem.Unmarshal(m, b)
}
func (m *C2SCollectMailItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SCollectMailItem.Marshal(b, m, deterministic)
}
func (m *C2SCollectMailItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SCollectMailItem.Merge(m, src)
}
func (m *C2SCollectMailItem) XXX_Size() int {
	return xxx_messageInfo_C2SCollectMailItem.Size(m)
}
func (m *C2SCollectMailItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SCollectMailItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SCollectMailItem proto.InternalMessageInfo

func (m *C2SCollectMailItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SCollectMailItem) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type S2CCollectMailItem struct {
	Mail                 *Mail    `protobuf:"bytes,1,opt,name=Mail,proto3" json:"Mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CCollectMailItem) Reset()         { *m = S2CCollectMailItem{} }
func (m *S2CCollectMailItem) String() string { return proto.CompactTextString(m) }
func (*S2CCollectMailItem) ProtoMessage()    {}
func (*S2CCollectMailItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{11}
}

func (m *S2CCollectMailItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CCollectMailItem.Unmarshal(m, b)
}
func (m *S2CCollectMailItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CCollectMailItem.Marshal(b, m, deterministic)
}
func (m *S2CCollectMailItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CCollectMailItem.Merge(m, src)
}
func (m *S2CCollectMailItem) XXX_Size() int {
	return xxx_messageInfo_S2CCollectMailItem.Size(m)
}
func (m *S2CCollectMailItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CCollectMailItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CCollectMailItem proto.InternalMessageInfo

func (m *S2CCollectMailItem) GetMail() *Mail {
	if m != nil {
		return m.Mail
	}
	return nil
}

// 一键读取请求
type C2SCollectAllMailItems struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SCollectAllMailItems) Reset()         { *m = C2SCollectAllMailItems{} }
func (m *C2SCollectAllMailItems) String() string { return proto.CompactTextString(m) }
func (*C2SCollectAllMailItems) ProtoMessage()    {}
func (*C2SCollectAllMailItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{12}
}

func (m *C2SCollectAllMailItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SCollectAllMailItems.Unmarshal(m, b)
}
func (m *C2SCollectAllMailItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SCollectAllMailItems.Marshal(b, m, deterministic)
}
func (m *C2SCollectAllMailItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SCollectAllMailItems.Merge(m, src)
}
func (m *C2SCollectAllMailItems) XXX_Size() int {
	return xxx_messageInfo_C2SCollectAllMailItems.Size(m)
}
func (m *C2SCollectAllMailItems) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SCollectAllMailItems.DiscardUnknown(m)
}

var xxx_messageInfo_C2SCollectAllMailItems proto.InternalMessageInfo

type S2CCollectAllMailItems struct {
	Mails                []*Mail  `protobuf:"bytes,1,rep,name=Mails,proto3" json:"Mails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CCollectAllMailItems) Reset()         { *m = S2CCollectAllMailItems{} }
func (m *S2CCollectAllMailItems) String() string { return proto.CompactTextString(m) }
func (*S2CCollectAllMailItems) ProtoMessage()    {}
func (*S2CCollectAllMailItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{13}
}

func (m *S2CCollectAllMailItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CCollectAllMailItems.Unmarshal(m, b)
}
func (m *S2CCollectAllMailItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CCollectAllMailItems.Marshal(b, m, deterministic)
}
func (m *S2CCollectAllMailItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CCollectAllMailItems.Merge(m, src)
}
func (m *S2CCollectAllMailItems) XXX_Size() int {
	return xxx_messageInfo_S2CCollectAllMailItems.Size(m)
}
func (m *S2CCollectAllMailItems) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CCollectAllMailItems.DiscardUnknown(m)
}

var xxx_messageInfo_S2CCollectAllMailItems proto.InternalMessageInfo

func (m *S2CCollectAllMailItems) GetMails() []*Mail {
	if m != nil {
		return m.Mails
	}
	return nil
}

// 收到新邮件推送
type PushNewMail struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushNewMail) Reset()         { *m = PushNewMail{} }
func (m *PushNewMail) String() string { return proto.CompactTextString(m) }
func (*PushNewMail) ProtoMessage()    {}
func (*PushNewMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cda5f053e74676b, []int{14}
}

func (m *PushNewMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushNewMail.Unmarshal(m, b)
}
func (m *PushNewMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushNewMail.Marshal(b, m, deterministic)
}
func (m *PushNewMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushNewMail.Merge(m, src)
}
func (m *PushNewMail) XXX_Size() int {
	return xxx_messageInfo_PushNewMail.Size(m)
}
func (m *PushNewMail) XXX_DiscardUnknown() {
	xxx_messageInfo_PushNewMail.DiscardUnknown(m)
}

var xxx_messageInfo_PushNewMail proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Mail)(nil), "Proto.Mail.Mail")
	proto.RegisterMapType((map[string]*MailInfo)(nil), "Proto.Mail.Mail.InfosEntry")
	proto.RegisterType((*MailInfo)(nil), "Proto.Mail.MailInfo")
	proto.RegisterType((*C2SMailList)(nil), "Proto.Mail.C2SMailList")
	proto.RegisterType((*S2CMailList)(nil), "Proto.Mail.S2CMailList")
	proto.RegisterType((*C2SOpenMail)(nil), "Proto.Mail.C2SOpenMail")
	proto.RegisterType((*S2COpenMail)(nil), "Proto.Mail.S2COpenMail")
	proto.RegisterType((*C2SDelMail)(nil), "Proto.Mail.C2SDelMail")
	proto.RegisterType((*S2CDelMail)(nil), "Proto.Mail.S2CDelMail")
	proto.RegisterType((*C2SDelAllMail)(nil), "Proto.Mail.C2SDelAllMail")
	proto.RegisterType((*S2CDelAllMail)(nil), "Proto.Mail.S2CDelAllMail")
	proto.RegisterType((*C2SCollectMailItem)(nil), "Proto.Mail.C2SCollectMailItem")
	proto.RegisterType((*S2CCollectMailItem)(nil), "Proto.Mail.S2CCollectMailItem")
	proto.RegisterType((*C2SCollectAllMailItems)(nil), "Proto.Mail.C2SCollectAllMailItems")
	proto.RegisterType((*S2CCollectAllMailItems)(nil), "Proto.Mail.S2CCollectAllMailItems")
	proto.RegisterType((*PushNewMail)(nil), "Proto.Mail.PushNewMail")
}

func init() {
	proto.RegisterFile("mail.proto", fileDescriptor_7cda5f053e74676b)
}

var fileDescriptor_7cda5f053e74676b = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x38, 0x4d, 0xc6, 0x4d, 0x5b, 0xad, 0xaa, 0x68, 0x55, 0x44, 0xe5, 0xae, 0x50,
	0x65, 0x71, 0x28, 0xc2, 0x05, 0x84, 0x2a, 0x0e, 0x14, 0x53, 0xc0, 0x12, 0xb4, 0xd1, 0x3a, 0x27,
	0x2e, 0xc8, 0x75, 0xb6, 0xad, 0x85, 0xbf, 0x64, 0x6f, 0x80, 0xfc, 0x0e, 0xfe, 0x30, 0x9a, 0x5d,
	0x27, 0x4e, 0x23, 0x40, 0xbd, 0xb4, 0xfb, 0xe6, 0xcd, 0xbc, 0xf9, 0x8c, 0x01, 0xf2, 0x38, 0xcd,
	0x4e, 0xaa, 0xba, 0x94, 0x25, 0x81, 0x09, 0xfe, 0x3b, 0xf9, 0x12, 0xa7, 0xd9, 0xc1, 0x76, 0x35,
	0xbf, 0xce, 0xd2, 0x44, 0x33, 0xec, 0x77, 0x0f, 0x7a, 0x68, 0x26, 0x3b, 0x60, 0x86, 0x33, 0x6a,
	0xb8, 0x86, 0x67, 0x71, 0x33, 0x9c, 0x91, 0xe7, 0x60, 0x87, 0xc5, 0x4d, 0xd9, 0x50, 0xd3, 0xb5,
	0x3c, 0xc7, 0x7f, 0x74, 0xd2, 0x49, 0xe8, 0x3f, 0x8a, 0xbd, 0x28, 0x64, 0xbd, 0xe0, 0xda, 0x93,
	0x1c, 0xc0, 0xe0, 0xaa, 0x12, 0xc5, 0x34, 0xcd, 0x05, 0xb5, 0x94, 0xd0, 0x0a, 0x93, 0x43, 0x80,
	0xa0, 0x16, 0xb1, 0x14, 0x8a, 0xed, 0x29, 0x76, 0xcd, 0x42, 0x8e, 0xa1, 0x17, 0x4a, 0x91, 0x53,
	0x5b, 0x65, 0x23, 0x6d, 0xb6, 0x89, 0x2e, 0x15, 0x19, 0xae, 0x78, 0x42, 0x61, 0xeb, 0x63, 0x29,
	0x95, 0x6b, 0xdf, 0x35, 0xbc, 0x01, 0x5f, 0x42, 0xb2, 0x0f, 0x76, 0x70, 0x73, 0x1b, 0xce, 0xe8,
	0x96, 0x6b, 0x78, 0x36, 0xd7, 0x80, 0x8c, 0xa1, 0x3f, 0x89, 0xeb, 0x38, 0x6f, 0xe8, 0xc0, 0xb5,
	0xbc, 0x21, 0x6f, 0x11, 0xd6, 0x73, 0xf1, 0xab, 0x4a, 0x6b, 0x5d, 0xcf, 0x50, 0xd7, 0xd3, 0x59,
	0x90, 0x8f, 0x44, 0x31, 0x13, 0xf5, 0x65, 0x9c, 0x0b, 0x0a, 0xae, 0xe1, 0x0d, 0xf9, 0x9a, 0x05,
	0x7b, 0xc5, 0x29, 0x4c, 0x17, 0x95, 0xa0, 0x8e, 0x4a, 0xb8, 0xc2, 0xc4, 0x83, 0xdd, 0xb4, 0xf9,
	0x14, 0x37, 0xe7, 0x52, 0xc6, 0xc9, 0x5d, 0x2e, 0x0a, 0x49, 0xb7, 0x55, 0xad, 0x9b, 0x66, 0xf2,
	0x01, 0x76, 0x3a, 0x84, 0x43, 0xa4, 0x23, 0xd7, 0xf0, 0x1c, 0xff, 0xf0, 0x7e, 0xff, 0x9d, 0xcf,
	0x55, 0x25, 0xd3, 0xb2, 0xe0, 0x1b, 0x51, 0x07, 0x97, 0x00, 0xdd, 0x3a, 0xc8, 0x1e, 0x58, 0xdf,
	0xc5, 0x42, 0xed, 0x72, 0xc8, 0xf1, 0x49, 0x9e, 0x82, 0xfd, 0x23, 0xce, 0xe6, 0x82, 0x9a, 0x4a,
	0x7e, 0x7f, 0x73, 0x99, 0x18, 0xcc, 0xb5, 0xcb, 0x99, 0xf9, 0xda, 0x60, 0x67, 0xba, 0x3b, 0x34,
	0xe3, 0x5c, 0xa7, 0xa9, 0xcc, 0x44, 0xab, 0xa7, 0x01, 0xee, 0x21, 0x28, 0x0b, 0x89, 0xbd, 0x99,
	0xca, 0xbe, 0x84, 0xec, 0x08, 0x9c, 0xc0, 0x8f, 0x30, 0xfc, 0x73, 0xda, 0x48, 0x42, 0xa0, 0x37,
	0x89, 0x6f, 0x75, 0xb4, 0xcd, 0xd5, 0x9b, 0xbd, 0x04, 0x27, 0xf2, 0x83, 0x95, 0xcb, 0x31, 0xd8,
	0xf8, 0x6e, 0xa8, 0xa1, 0x96, 0xbf, 0xb7, 0x59, 0x1d, 0xd7, 0x34, 0x7b, 0xac, 0x94, 0xf1, 0xa4,
	0xee, 0x5d, 0xac, 0xa5, 0x2f, 0x96, 0x9d, 0x2a, 0xd5, 0x15, 0xfd, 0x44, 0x1f, 0xf6, 0x3f, 0x45,
	0x15, 0xcb, 0x5e, 0x00, 0x04, 0x7e, 0xf4, 0x5e, 0x64, 0x7f, 0xfd, 0x11, 0x8c, 0xa1, 0x7f, 0x9e,
	0xe0, 0xc4, 0x55, 0x93, 0x36, 0x6f, 0x11, 0x7b, 0x05, 0x10, 0xf9, 0xc1, 0x32, 0x8a, 0xc2, 0x56,
	0x34, 0x4f, 0x12, 0xd1, 0x34, 0x2a, 0x74, 0xc0, 0x97, 0xb0, 0xd5, 0x33, 0x97, 0x7a, 0x6c, 0x17,
	0x46, 0x3a, 0xdb, 0x79, 0xa6, 0x42, 0xd9, 0x11, 0x8c, 0xb4, 0x50, 0x6b, 0xc0, 0xdd, 0x85, 0xb3,
	0xa6, 0xed, 0x0a, 0x9f, 0xec, 0x0d, 0x90, 0xc0, 0x8f, 0x82, 0x32, 0xcb, 0x44, 0x22, 0xd5, 0x56,
	0xf0, 0xda, 0x1f, 0x5a, 0xe9, 0x19, 0x90, 0xc8, 0x0f, 0x36, 0xa3, 0xbb, 0xd9, 0x18, 0xff, 0x99,
	0x0d, 0x85, 0x71, 0x97, 0xb9, 0x2d, 0x10, 0xc3, 0x1b, 0xf6, 0x16, 0xc6, 0x9d, 0xea, 0x3a, 0xf3,
	0xe0, 0x5d, 0x8e, 0xc0, 0x99, 0xcc, 0x9b, 0xbb, 0x4b, 0xf1, 0x13, 0xf1, 0xbb, 0xd1, 0x57, 0xe7,
	0x99, 0xfa, 0x20, 0x7d, 0xc3, 0xaf, 0xd6, 0x75, 0x5f, 0xbd, 0x4f, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xb4, 0xd0, 0x60, 0xc4, 0x04, 0x00, 0x00,
}
