// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package proto_task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2SGetTasks struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetTasks) Reset()         { *m = C2SGetTasks{} }
func (m *C2SGetTasks) String() string { return proto.CompactTextString(m) }
func (*C2SGetTasks) ProtoMessage()    {}
func (*C2SGetTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *C2SGetTasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetTasks.Unmarshal(m, b)
}
func (m *C2SGetTasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetTasks.Marshal(b, m, deterministic)
}
func (m *C2SGetTasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetTasks.Merge(m, src)
}
func (m *C2SGetTasks) XXX_Size() int {
	return xxx_messageInfo_C2SGetTasks.Size(m)
}
func (m *C2SGetTasks) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetTasks.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetTasks proto.InternalMessageInfo

type C2SGetReward struct {
	BucketType           int32    `protobuf:"varint,1,opt,name=bucket_type,json=bucketType,proto3" json:"bucket_type,omitempty"`
	TaskId               int32    `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetReward) Reset()         { *m = C2SGetReward{} }
func (m *C2SGetReward) String() string { return proto.CompactTextString(m) }
func (*C2SGetReward) ProtoMessage()    {}
func (*C2SGetReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *C2SGetReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetReward.Unmarshal(m, b)
}
func (m *C2SGetReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetReward.Marshal(b, m, deterministic)
}
func (m *C2SGetReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetReward.Merge(m, src)
}
func (m *C2SGetReward) XXX_Size() int {
	return xxx_messageInfo_C2SGetReward.Size(m)
}
func (m *C2SGetReward) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetReward.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetReward proto.InternalMessageInfo

func (m *C2SGetReward) GetBucketType() int32 {
	if m != nil {
		return m.BucketType
	}
	return 0
}

func (m *C2SGetReward) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type C2SGetActivePointReward struct {
	RewardId             int32    `protobuf:"varint,1,opt,name=reward_id,json=rewardId,proto3" json:"reward_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetActivePointReward) Reset()         { *m = C2SGetActivePointReward{} }
func (m *C2SGetActivePointReward) String() string { return proto.CompactTextString(m) }
func (*C2SGetActivePointReward) ProtoMessage()    {}
func (*C2SGetActivePointReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *C2SGetActivePointReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetActivePointReward.Unmarshal(m, b)
}
func (m *C2SGetActivePointReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetActivePointReward.Marshal(b, m, deterministic)
}
func (m *C2SGetActivePointReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetActivePointReward.Merge(m, src)
}
func (m *C2SGetActivePointReward) XXX_Size() int {
	return xxx_messageInfo_C2SGetActivePointReward.Size(m)
}
func (m *C2SGetActivePointReward) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetActivePointReward.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetActivePointReward proto.InternalMessageInfo

func (m *C2SGetActivePointReward) GetRewardId() int32 {
	if m != nil {
		return m.RewardId
	}
	return 0
}

type TaskState struct {
	Progress             int32    `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Rewarded             bool     `protobuf:"varint,2,opt,name=rewarded,proto3" json:"rewarded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskState) Reset()         { *m = TaskState{} }
func (m *TaskState) String() string { return proto.CompactTextString(m) }
func (*TaskState) ProtoMessage()    {}
func (*TaskState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *TaskState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskState.Unmarshal(m, b)
}
func (m *TaskState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskState.Marshal(b, m, deterministic)
}
func (m *TaskState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskState.Merge(m, src)
}
func (m *TaskState) XXX_Size() int {
	return xxx_messageInfo_TaskState.Size(m)
}
func (m *TaskState) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskState.DiscardUnknown(m)
}

var xxx_messageInfo_TaskState proto.InternalMessageInfo

func (m *TaskState) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *TaskState) GetRewarded() bool {
	if m != nil {
		return m.Rewarded
	}
	return false
}

type TaskGroup struct {
	BucketType           int32                `protobuf:"varint,1,opt,name=bucket_type,json=bucketType,proto3" json:"bucket_type,omitempty"`
	Tasks                map[int32]*TaskState `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ClaimRecord          map[int32]bool       `protobuf:"bytes,3,rep,name=claim_record,json=claimRecord,proto3" json:"claim_record,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Point                int32                `protobuf:"varint,4,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskGroup) Reset()         { *m = TaskGroup{} }
func (m *TaskGroup) String() string { return proto.CompactTextString(m) }
func (*TaskGroup) ProtoMessage()    {}
func (*TaskGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *TaskGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskGroup.Unmarshal(m, b)
}
func (m *TaskGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskGroup.Marshal(b, m, deterministic)
}
func (m *TaskGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskGroup.Merge(m, src)
}
func (m *TaskGroup) XXX_Size() int {
	return xxx_messageInfo_TaskGroup.Size(m)
}
func (m *TaskGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TaskGroup proto.InternalMessageInfo

func (m *TaskGroup) GetBucketType() int32 {
	if m != nil {
		return m.BucketType
	}
	return 0
}

func (m *TaskGroup) GetTasks() map[int32]*TaskState {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *TaskGroup) GetClaimRecord() map[int32]bool {
	if m != nil {
		return m.ClaimRecord
	}
	return nil
}

func (m *TaskGroup) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

type S2CGetTasks struct {
	Groups               []*TaskGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2CGetTasks) Reset()         { *m = S2CGetTasks{} }
func (m *S2CGetTasks) String() string { return proto.CompactTextString(m) }
func (*S2CGetTasks) ProtoMessage()    {}
func (*S2CGetTasks) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *S2CGetTasks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetTasks.Unmarshal(m, b)
}
func (m *S2CGetTasks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetTasks.Marshal(b, m, deterministic)
}
func (m *S2CGetTasks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetTasks.Merge(m, src)
}
func (m *S2CGetTasks) XXX_Size() int {
	return xxx_messageInfo_S2CGetTasks.Size(m)
}
func (m *S2CGetTasks) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetTasks.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetTasks proto.InternalMessageInfo

func (m *S2CGetTasks) GetGroups() []*TaskGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type PushTask struct {
	Groups               []*TaskGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PushTask) Reset()         { *m = PushTask{} }
func (m *PushTask) String() string { return proto.CompactTextString(m) }
func (*PushTask) ProtoMessage()    {}
func (*PushTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *PushTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushTask.Unmarshal(m, b)
}
func (m *PushTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushTask.Marshal(b, m, deterministic)
}
func (m *PushTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushTask.Merge(m, src)
}
func (m *PushTask) XXX_Size() int {
	return xxx_messageInfo_PushTask.Size(m)
}
func (m *PushTask) XXX_DiscardUnknown() {
	xxx_messageInfo_PushTask.DiscardUnknown(m)
}

var xxx_messageInfo_PushTask proto.InternalMessageInfo

func (m *PushTask) GetGroups() []*TaskGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type S2CGetReward struct {
	Succ                 bool     `protobuf:"varint,1,opt,name=succ,proto3" json:"succ,omitempty"`
	TaskId               int32    `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGetReward) Reset()         { *m = S2CGetReward{} }
func (m *S2CGetReward) String() string { return proto.CompactTextString(m) }
func (*S2CGetReward) ProtoMessage()    {}
func (*S2CGetReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *S2CGetReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetReward.Unmarshal(m, b)
}
func (m *S2CGetReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetReward.Marshal(b, m, deterministic)
}
func (m *S2CGetReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetReward.Merge(m, src)
}
func (m *S2CGetReward) XXX_Size() int {
	return xxx_messageInfo_S2CGetReward.Size(m)
}
func (m *S2CGetReward) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetReward.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetReward proto.InternalMessageInfo

func (m *S2CGetReward) GetSucc() bool {
	if m != nil {
		return m.Succ
	}
	return false
}

func (m *S2CGetReward) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type S2CGetActivePointReward struct {
	Succ                 bool     `protobuf:"varint,1,opt,name=succ,proto3" json:"succ,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGetActivePointReward) Reset()         { *m = S2CGetActivePointReward{} }
func (m *S2CGetActivePointReward) String() string { return proto.CompactTextString(m) }
func (*S2CGetActivePointReward) ProtoMessage()    {}
func (*S2CGetActivePointReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *S2CGetActivePointReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetActivePointReward.Unmarshal(m, b)
}
func (m *S2CGetActivePointReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetActivePointReward.Marshal(b, m, deterministic)
}
func (m *S2CGetActivePointReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetActivePointReward.Merge(m, src)
}
func (m *S2CGetActivePointReward) XXX_Size() int {
	return xxx_messageInfo_S2CGetActivePointReward.Size(m)
}
func (m *S2CGetActivePointReward) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetActivePointReward.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetActivePointReward proto.InternalMessageInfo

func (m *S2CGetActivePointReward) GetSucc() bool {
	if m != nil {
		return m.Succ
	}
	return false
}

func init() {
	proto.RegisterType((*C2SGetTasks)(nil), "Proto.Task.C2SGetTasks")
	proto.RegisterType((*C2SGetReward)(nil), "Proto.Task.C2SGetReward")
	proto.RegisterType((*C2SGetActivePointReward)(nil), "Proto.Task.C2SGetActivePointReward")
	proto.RegisterType((*TaskState)(nil), "Proto.Task.TaskState")
	proto.RegisterType((*TaskGroup)(nil), "Proto.Task.TaskGroup")
	proto.RegisterMapType((map[int32]bool)(nil), "Proto.Task.TaskGroup.ClaimRecordEntry")
	proto.RegisterMapType((map[int32]*TaskState)(nil), "Proto.Task.TaskGroup.TasksEntry")
	proto.RegisterType((*S2CGetTasks)(nil), "Proto.Task.S2CGetTasks")
	proto.RegisterType((*PushTask)(nil), "Proto.Task.PushTask")
	proto.RegisterType((*S2CGetReward)(nil), "Proto.Task.S2CGetReward")
	proto.RegisterType((*S2CGetActivePointReward)(nil), "Proto.Task.S2CGetActivePointReward")
}

func init() {
	proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff)
}

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdf, 0x8b, 0xda, 0x40,
	0x10, 0xc6, 0xc4, 0xd8, 0x38, 0xb1, 0x20, 0x8b, 0xad, 0xc1, 0x3e, 0x54, 0xf2, 0x50, 0x84, 0x62,
	0x0a, 0x29, 0x48, 0x7f, 0x51, 0x68, 0x43, 0xb1, 0x3e, 0x9d, 0xac, 0x3e, 0xdd, 0x4b, 0x88, 0xc9,
	0x9e, 0x17, 0xe2, 0x99, 0xb0, 0xbb, 0xf1, 0xcc, 0x3f, 0x7a, 0x7f, 0xcf, 0xb1, 0xbb, 0x46, 0xc5,
	0xcb, 0x71, 0xdc, 0x4b, 0x32, 0xb3, 0xfb, 0x7d, 0xdf, 0x7c, 0x33, 0x99, 0x00, 0xf0, 0x90, 0xa5,
	0x6e, 0x4e, 0x33, 0x9e, 0x21, 0x98, 0x8b, 0x97, 0xbb, 0x0c, 0x59, 0xea, 0xbc, 0x05, 0xcb, 0xf7,
	0x16, 0x53, 0xc2, 0x45, 0xc6, 0x9c, 0xff, 0xd0, 0x51, 0x29, 0x26, 0xf7, 0x21, 0x8d, 0xd1, 0x47,
	0xb0, 0x56, 0x45, 0x94, 0x12, 0x1e, 0xf0, 0x32, 0x27, 0x76, 0x63, 0xd8, 0x18, 0x19, 0x18, 0xd4,
	0xd1, 0xb2, 0xcc, 0x09, 0xea, 0xc3, 0x1b, 0xa1, 0x1c, 0x24, 0xb1, 0xad, 0xc9, 0xcb, 0x96, 0x48,
	0x67, 0xb1, 0x33, 0x81, 0xbe, 0x52, 0xfa, 0x13, 0xf1, 0x64, 0x47, 0xe6, 0x59, 0xb2, 0xad, 0x44,
	0x3f, 0x40, 0x9b, 0xca, 0x48, 0xb0, 0x94, 0xa4, 0xa9, 0x0e, 0x66, 0xb1, 0xe3, 0x43, 0x5b, 0x58,
	0x59, 0xf0, 0x90, 0x13, 0x34, 0x00, 0x33, 0xa7, 0xd9, 0x9a, 0x12, 0xc6, 0x2a, 0x60, 0x95, 0x8b,
	0x3b, 0x45, 0x22, 0xaa, 0xb4, 0x89, 0x8f, 0xb9, 0xf3, 0xa0, 0x29, 0x95, 0x29, 0xcd, 0x8a, 0xfc,
	0xe5, 0x26, 0x26, 0x60, 0x08, 0xd7, 0xcc, 0xd6, 0x86, 0xfa, 0xc8, 0xf2, 0x86, 0xee, 0x69, 0x40,
	0xee, 0x51, 0x46, 0x46, 0xec, 0xdf, 0x96, 0xd3, 0x12, 0x2b, 0x38, 0x9a, 0x41, 0x27, 0xda, 0x84,
	0xc9, 0x5d, 0x40, 0x49, 0x94, 0xd1, 0xd8, 0xd6, 0x25, 0xfd, 0x53, 0x3d, 0xdd, 0x17, 0x48, 0x2c,
	0x81, 0x4a, 0xc4, 0x8a, 0x4e, 0x27, 0xa8, 0x07, 0x46, 0x2e, 0x46, 0x64, 0x37, 0xa5, 0x3b, 0x95,
	0x0c, 0xae, 0x00, 0x4e, 0x55, 0x51, 0x17, 0xf4, 0x94, 0x94, 0x07, 0xff, 0x22, 0x44, 0x9f, 0xc1,
	0xd8, 0x85, 0x9b, 0x82, 0xc8, 0x01, 0x58, 0xde, 0xbb, 0xcb, 0xca, 0x72, 0x8a, 0x58, 0x61, 0x7e,
	0x68, 0xdf, 0x1a, 0x83, 0xdf, 0xd0, 0xbd, 0xf4, 0x51, 0x23, 0xdb, 0x3b, 0x97, 0x35, 0xcf, 0xf8,
	0xce, 0x2f, 0xb0, 0x16, 0x9e, 0x5f, 0xad, 0x0b, 0x1a, 0x43, 0x6b, 0x2d, 0x9a, 0x13, 0x5f, 0x47,
	0xaf, 0x33, 0x20, 0x5b, 0xc7, 0x07, 0x90, 0xf3, 0x1d, 0xcc, 0x79, 0xc1, 0x6e, 0xc5, 0xc5, 0x6b,
	0xa9, 0x3f, 0xa1, 0xa3, 0x0a, 0x1f, 0x76, 0x08, 0x41, 0x93, 0x15, 0x51, 0x24, 0x5d, 0x9b, 0x58,
	0xc6, 0xcf, 0xef, 0xe2, 0x18, 0xfa, 0x8a, 0xfc, 0x74, 0x17, 0x6b, 0x74, 0xfe, 0xbe, 0xbf, 0xee,
	0xed, 0x6f, 0xf6, 0x5f, 0xe4, 0xcf, 0xa2, 0x9e, 0x81, 0x10, 0x5a, 0xb5, 0x64, 0xfc, 0xf5, 0x31,
	0x00, 0x00, 0xff, 0xff, 0xb5, 0x92, 0x9c, 0xf6, 0x4c, 0x03, 0x00, 0x00,
}
