SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS admin_mail;
DROP TABLE IF EXISTS player_mail_info;
DROP TABLE IF EXISTS sys_mail_info;
DROP TABLE IF EXISTS server_group;
DROP TABLE IF EXISTS pay_cache_order;
DROP TABLE IF EXISTS pay_order;
DROP TABLE IF EXISTS friend_apply;
DROP TABLE IF EXISTS friend_block;
DROP TABLE IF EXISTS guild;
DROP TABLE IF EXISTS guild_apply;
DROP TABLE IF EXISTS guild_log;
DROP TABLE IF EXISTS hot_update;
DROP TABLE IF EXISTS notice;
DROP TABLE IF EXISTS game_server;

SET FOREIGN_KEY_CHECKS = 1;
