// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package proto_item

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求背包信息
type C2SBag struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SBag) Reset()         { *m = C2SBag{} }
func (m *C2SBag) String() string { return proto.CompactTextString(m) }
func (*C2SBag) ProtoMessage()    {}
func (*C2SBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *C2SBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SBag.Unmarshal(m, b)
}
func (m *C2SBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SBag.Marshal(b, m, deterministic)
}
func (m *C2SBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SBag.Merge(m, src)
}
func (m *C2SBag) XXX_Size() int {
	return xxx_messageInfo_C2SBag.Size(m)
}
func (m *C2SBag) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SBag.DiscardUnknown(m)
}

var xxx_messageInfo_C2SBag proto.InternalMessageInfo

type S2CBag struct {
	Bag                  map[int32]int32 `protobuf:"bytes,1,rep,name=Bag,proto3" json:"Bag,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *S2CBag) Reset()         { *m = S2CBag{} }
func (m *S2CBag) String() string { return proto.CompactTextString(m) }
func (*S2CBag) ProtoMessage()    {}
func (*S2CBag) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *S2CBag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CBag.Unmarshal(m, b)
}
func (m *S2CBag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CBag.Marshal(b, m, deterministic)
}
func (m *S2CBag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CBag.Merge(m, src)
}
func (m *S2CBag) XXX_Size() int {
	return xxx_messageInfo_S2CBag.Size(m)
}
func (m *S2CBag) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CBag.DiscardUnknown(m)
}

var xxx_messageInfo_S2CBag proto.InternalMessageInfo

func (m *S2CBag) GetBag() map[int32]int32 {
	if m != nil {
		return m.Bag
	}
	return nil
}

// 道具数量变化推送
type PushChange struct {
	Change               map[int32]int32 `protobuf:"bytes,1,rep,name=Change,proto3" json:"Change,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PushChange) Reset()         { *m = PushChange{} }
func (m *PushChange) String() string { return proto.CompactTextString(m) }
func (*PushChange) ProtoMessage()    {}
func (*PushChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *PushChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChange.Unmarshal(m, b)
}
func (m *PushChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChange.Marshal(b, m, deterministic)
}
func (m *PushChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChange.Merge(m, src)
}
func (m *PushChange) XXX_Size() int {
	return xxx_messageInfo_PushChange.Size(m)
}
func (m *PushChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushChange proto.InternalMessageInfo

func (m *PushChange) GetChange() map[int32]int32 {
	if m != nil {
		return m.Change
	}
	return nil
}

// 使用道具
type C2SUseItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	ItemNum              int32    `protobuf:"varint,2,opt,name=ItemNum,proto3" json:"ItemNum,omitempty"`
	AppointId            int32    `protobuf:"varint,3,opt,name=AppointId,proto3" json:"AppointId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUseItem) Reset()         { *m = C2SUseItem{} }
func (m *C2SUseItem) String() string { return proto.CompactTextString(m) }
func (*C2SUseItem) ProtoMessage()    {}
func (*C2SUseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *C2SUseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUseItem.Unmarshal(m, b)
}
func (m *C2SUseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUseItem.Marshal(b, m, deterministic)
}
func (m *C2SUseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUseItem.Merge(m, src)
}
func (m *C2SUseItem) XXX_Size() int {
	return xxx_messageInfo_C2SUseItem.Size(m)
}
func (m *C2SUseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUseItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUseItem proto.InternalMessageInfo

func (m *C2SUseItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *C2SUseItem) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *C2SUseItem) GetAppointId() int32 {
	if m != nil {
		return m.AppointId
	}
	return 0
}

type S2CUseItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CUseItem) Reset()         { *m = S2CUseItem{} }
func (m *S2CUseItem) String() string { return proto.CompactTextString(m) }
func (*S2CUseItem) ProtoMessage()    {}
func (*S2CUseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *S2CUseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUseItem.Unmarshal(m, b)
}
func (m *S2CUseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUseItem.Marshal(b, m, deterministic)
}
func (m *S2CUseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUseItem.Merge(m, src)
}
func (m *S2CUseItem) XXX_Size() int {
	return xxx_messageInfo_S2CUseItem.Size(m)
}
func (m *S2CUseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUseItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUseItem proto.InternalMessageInfo

func (m *S2CUseItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 合成道具
type C2SCompositionItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SCompositionItem) Reset()         { *m = C2SCompositionItem{} }
func (m *C2SCompositionItem) String() string { return proto.CompactTextString(m) }
func (*C2SCompositionItem) ProtoMessage()    {}
func (*C2SCompositionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *C2SCompositionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SCompositionItem.Unmarshal(m, b)
}
func (m *C2SCompositionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SCompositionItem.Marshal(b, m, deterministic)
}
func (m *C2SCompositionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SCompositionItem.Merge(m, src)
}
func (m *C2SCompositionItem) XXX_Size() int {
	return xxx_messageInfo_C2SCompositionItem.Size(m)
}
func (m *C2SCompositionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SCompositionItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SCompositionItem proto.InternalMessageInfo

func (m *C2SCompositionItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type S2CCompositionItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CCompositionItem) Reset()         { *m = S2CCompositionItem{} }
func (m *S2CCompositionItem) String() string { return proto.CompactTextString(m) }
func (*S2CCompositionItem) ProtoMessage()    {}
func (*S2CCompositionItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *S2CCompositionItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CCompositionItem.Unmarshal(m, b)
}
func (m *S2CCompositionItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CCompositionItem.Marshal(b, m, deterministic)
}
func (m *S2CCompositionItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CCompositionItem.Merge(m, src)
}
func (m *S2CCompositionItem) XXX_Size() int {
	return xxx_messageInfo_S2CCompositionItem.Size(m)
}
func (m *S2CCompositionItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CCompositionItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CCompositionItem proto.InternalMessageInfo

func (m *S2CCompositionItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 出售道具
type C2SSellItem struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SSellItem) Reset()         { *m = C2SSellItem{} }
func (m *C2SSellItem) String() string { return proto.CompactTextString(m) }
func (*C2SSellItem) ProtoMessage()    {}
func (*C2SSellItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *C2SSellItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SSellItem.Unmarshal(m, b)
}
func (m *C2SSellItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SSellItem.Marshal(b, m, deterministic)
}
func (m *C2SSellItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SSellItem.Merge(m, src)
}
func (m *C2SSellItem) XXX_Size() int {
	return xxx_messageInfo_C2SSellItem.Size(m)
}
func (m *C2SSellItem) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SSellItem.DiscardUnknown(m)
}

var xxx_messageInfo_C2SSellItem proto.InternalMessageInfo

func (m *C2SSellItem) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type S2CSellItem struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CSellItem) Reset()         { *m = S2CSellItem{} }
func (m *S2CSellItem) String() string { return proto.CompactTextString(m) }
func (*S2CSellItem) ProtoMessage()    {}
func (*S2CSellItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *S2CSellItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CSellItem.Unmarshal(m, b)
}
func (m *S2CSellItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CSellItem.Marshal(b, m, deterministic)
}
func (m *S2CSellItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CSellItem.Merge(m, src)
}
func (m *S2CSellItem) XXX_Size() int {
	return xxx_messageInfo_S2CSellItem.Size(m)
}
func (m *S2CSellItem) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CSellItem.DiscardUnknown(m)
}

var xxx_messageInfo_S2CSellItem proto.InternalMessageInfo

func (m *S2CSellItem) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

// 推送奖励弹框
type PushPopReward struct {
	Items                []*proto_public.Item `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
	Src                  int32                `protobuf:"varint,2,opt,name=Src,proto3" json:"Src,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PushPopReward) Reset()         { *m = PushPopReward{} }
func (m *PushPopReward) String() string { return proto.CompactTextString(m) }
func (*PushPopReward) ProtoMessage()    {}
func (*PushPopReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *PushPopReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPopReward.Unmarshal(m, b)
}
func (m *PushPopReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPopReward.Marshal(b, m, deterministic)
}
func (m *PushPopReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPopReward.Merge(m, src)
}
func (m *PushPopReward) XXX_Size() int {
	return xxx_messageInfo_PushPopReward.Size(m)
}
func (m *PushPopReward) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPopReward.DiscardUnknown(m)
}

var xxx_messageInfo_PushPopReward proto.InternalMessageInfo

func (m *PushPopReward) GetItems() []*proto_public.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PushPopReward) GetSrc() int32 {
	if m != nil {
		return m.Src
	}
	return 0
}

//兑换码
type C2SExchangeCDKey struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SExchangeCDKey) Reset()         { *m = C2SExchangeCDKey{} }
func (m *C2SExchangeCDKey) String() string { return proto.CompactTextString(m) }
func (*C2SExchangeCDKey) ProtoMessage()    {}
func (*C2SExchangeCDKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{10}
}

func (m *C2SExchangeCDKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SExchangeCDKey.Unmarshal(m, b)
}
func (m *C2SExchangeCDKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SExchangeCDKey.Marshal(b, m, deterministic)
}
func (m *C2SExchangeCDKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SExchangeCDKey.Merge(m, src)
}
func (m *C2SExchangeCDKey) XXX_Size() int {
	return xxx_messageInfo_C2SExchangeCDKey.Size(m)
}
func (m *C2SExchangeCDKey) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SExchangeCDKey.DiscardUnknown(m)
}

var xxx_messageInfo_C2SExchangeCDKey proto.InternalMessageInfo

func (m *C2SExchangeCDKey) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type S2CExchangeCDKey struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	Items                []*proto_public.Item         `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
	CdKeys               *CDKeyOption                 `protobuf:"bytes,3,opt,name=CdKeys,proto3" json:"CdKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CExchangeCDKey) Reset()         { *m = S2CExchangeCDKey{} }
func (m *S2CExchangeCDKey) String() string { return proto.CompactTextString(m) }
func (*S2CExchangeCDKey) ProtoMessage()    {}
func (*S2CExchangeCDKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{11}
}

func (m *S2CExchangeCDKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CExchangeCDKey.Unmarshal(m, b)
}
func (m *S2CExchangeCDKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CExchangeCDKey.Marshal(b, m, deterministic)
}
func (m *S2CExchangeCDKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CExchangeCDKey.Merge(m, src)
}
func (m *S2CExchangeCDKey) XXX_Size() int {
	return xxx_messageInfo_S2CExchangeCDKey.Size(m)
}
func (m *S2CExchangeCDKey) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CExchangeCDKey.DiscardUnknown(m)
}

var xxx_messageInfo_S2CExchangeCDKey proto.InternalMessageInfo

func (m *S2CExchangeCDKey) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CExchangeCDKey) GetItems() []*proto_public.Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *S2CExchangeCDKey) GetCdKeys() *CDKeyOption {
	if m != nil {
		return m.CdKeys
	}
	return nil
}

type C2SInitCDKey struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitCDKey) Reset()         { *m = C2SInitCDKey{} }
func (m *C2SInitCDKey) String() string { return proto.CompactTextString(m) }
func (*C2SInitCDKey) ProtoMessage()    {}
func (*C2SInitCDKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{12}
}

func (m *C2SInitCDKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitCDKey.Unmarshal(m, b)
}
func (m *C2SInitCDKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitCDKey.Marshal(b, m, deterministic)
}
func (m *C2SInitCDKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitCDKey.Merge(m, src)
}
func (m *C2SInitCDKey) XXX_Size() int {
	return xxx_messageInfo_C2SInitCDKey.Size(m)
}
func (m *C2SInitCDKey) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitCDKey.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitCDKey proto.InternalMessageInfo

type S2CInitCDKey struct {
	CdKeys               []*CDKeyOption `protobuf:"bytes,1,rep,name=CdKeys,proto3" json:"CdKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CInitCDKey) Reset()         { *m = S2CInitCDKey{} }
func (m *S2CInitCDKey) String() string { return proto.CompactTextString(m) }
func (*S2CInitCDKey) ProtoMessage()    {}
func (*S2CInitCDKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{13}
}

func (m *S2CInitCDKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitCDKey.Unmarshal(m, b)
}
func (m *S2CInitCDKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitCDKey.Marshal(b, m, deterministic)
}
func (m *S2CInitCDKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitCDKey.Merge(m, src)
}
func (m *S2CInitCDKey) XXX_Size() int {
	return xxx_messageInfo_S2CInitCDKey.Size(m)
}
func (m *S2CInitCDKey) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitCDKey.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitCDKey proto.InternalMessageInfo

func (m *S2CInitCDKey) GetCdKeys() []*CDKeyOption {
	if m != nil {
		return m.CdKeys
	}
	return nil
}

type CDKeyOption struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	ExpireTime           int64    `protobuf:"varint,3,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDKeyOption) Reset()         { *m = CDKeyOption{} }
func (m *CDKeyOption) String() string { return proto.CompactTextString(m) }
func (*CDKeyOption) ProtoMessage()    {}
func (*CDKeyOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{14}
}

func (m *CDKeyOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDKeyOption.Unmarshal(m, b)
}
func (m *CDKeyOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDKeyOption.Marshal(b, m, deterministic)
}
func (m *CDKeyOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDKeyOption.Merge(m, src)
}
func (m *CDKeyOption) XXX_Size() int {
	return xxx_messageInfo_CDKeyOption.Size(m)
}
func (m *CDKeyOption) XXX_DiscardUnknown() {
	xxx_messageInfo_CDKeyOption.DiscardUnknown(m)
}

var xxx_messageInfo_CDKeyOption proto.InternalMessageInfo

func (m *CDKeyOption) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CDKeyOption) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CDKeyOption) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SBag)(nil), "Proto.Item.C2SBag")
	proto.RegisterType((*S2CBag)(nil), "Proto.Item.S2CBag")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Item.S2CBag.BagEntry")
	proto.RegisterType((*PushChange)(nil), "Proto.Item.PushChange")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Item.PushChange.ChangeEntry")
	proto.RegisterType((*C2SUseItem)(nil), "Proto.Item.C2SUseItem")
	proto.RegisterType((*S2CUseItem)(nil), "Proto.Item.S2CUseItem")
	proto.RegisterType((*C2SCompositionItem)(nil), "Proto.Item.C2SCompositionItem")
	proto.RegisterType((*S2CCompositionItem)(nil), "Proto.Item.S2CCompositionItem")
	proto.RegisterType((*C2SSellItem)(nil), "Proto.Item.C2SSellItem")
	proto.RegisterType((*S2CSellItem)(nil), "Proto.Item.S2CSellItem")
	proto.RegisterType((*PushPopReward)(nil), "Proto.Item.PushPopReward")
	proto.RegisterType((*C2SExchangeCDKey)(nil), "Proto.Item.C2SExchangeCDKey")
	proto.RegisterType((*S2CExchangeCDKey)(nil), "Proto.Item.S2CExchangeCDKey")
	proto.RegisterType((*C2SInitCDKey)(nil), "Proto.Item.C2SInitCDKey")
	proto.RegisterType((*S2CInitCDKey)(nil), "Proto.Item.S2CInitCDKey")
	proto.RegisterType((*CDKeyOption)(nil), "Proto.Item.CDKeyOption")
}

func init() {
	proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df)
}

var fileDescriptor_6007f868cf6553df = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6b, 0xd4, 0x4e,
	0x14, 0x25, 0x9b, 0x6e, 0x7e, 0xed, 0xcd, 0xb6, 0x2c, 0xc3, 0x0f, 0x0d, 0xeb, 0x07, 0x65, 0x40,
	0xd9, 0x07, 0x4d, 0x71, 0x04, 0xd1, 0xbe, 0x54, 0x73, 0x5d, 0x64, 0x59, 0xd0, 0x25, 0xa3, 0x08,
	0x22, 0x48, 0xba, 0x19, 0xd2, 0xe0, 0x26, 0x13, 0xf2, 0xa1, 0xdd, 0x67, 0xff, 0x11, 0xff, 0x54,
	0x99, 0xc9, 0xa4, 0x9b, 0x8a, 0xb4, 0xb4, 0x4f, 0x73, 0x3f, 0xce, 0x9c, 0x73, 0x92, 0x7b, 0x13,
	0x80, 0xb4, 0x16, 0x99, 0x5f, 0x94, 0xb2, 0x96, 0x04, 0x96, 0xea, 0xf0, 0xe7, 0xb5, 0xc8, 0x26,
	0xa3, 0xa2, 0x39, 0x5d, 0xa7, 0xab, 0xb6, 0x43, 0x77, 0xc1, 0x41, 0xc6, 0x83, 0x28, 0xa1, 0x12,
	0x1c, 0xce, 0x30, 0x88, 0x12, 0xf2, 0x14, 0xec, 0x20, 0x4a, 0x3c, 0xeb, 0xd0, 0x9e, 0xba, 0xec,
	0x9e, 0xbf, 0xbd, 0xeb, 0xb7, 0x00, 0x3f, 0x88, 0x92, 0x59, 0x5e, 0x97, 0x9b, 0x50, 0xe1, 0x26,
	0x2f, 0x60, 0xb7, 0x2b, 0x90, 0x31, 0xd8, 0xdf, 0xc5, 0xc6, 0xb3, 0x0e, 0xad, 0xe9, 0x30, 0x54,
	0x21, 0xf9, 0x1f, 0x86, 0x3f, 0xa2, 0x75, 0x23, 0xbc, 0x81, 0xae, 0xb5, 0xc9, 0xf1, 0xe0, 0xa5,
	0x45, 0x7f, 0x59, 0x00, 0xcb, 0xa6, 0x3a, 0xc3, 0xb3, 0x28, 0x4f, 0x04, 0x39, 0x06, 0xa7, 0x8d,
	0x8c, 0x30, 0xed, 0x0b, 0x6f, 0x71, 0x7e, 0x7b, 0xb4, 0xfa, 0xe6, 0xc6, 0xe4, 0x15, 0xb8, 0xbd,
	0xf2, 0x8d, 0x5c, 0x7c, 0x05, 0x40, 0xc6, 0x3f, 0x55, 0x42, 0xe9, 0x90, 0x3b, 0xe0, 0xa8, 0x73,
	0x1e, 0x9b, 0xcb, 0x26, 0x23, 0x1e, 0xfc, 0xa7, 0xa2, 0xf7, 0x4d, 0x66, 0x18, 0xba, 0x94, 0xdc,
	0x87, 0xbd, 0x37, 0x45, 0x21, 0xd3, 0xbc, 0x9e, 0xc7, 0x9e, 0xad, 0x7b, 0xdb, 0x02, 0x3d, 0x01,
	0xe0, 0x0c, 0x3b, 0xf6, 0x67, 0xb0, 0xb3, 0x92, 0xb1, 0xd0, 0xdc, 0x07, 0xec, 0x81, 0x79, 0xc0,
	0x65, 0x3b, 0x0f, 0x94, 0x59, 0x26, 0xf3, 0x59, 0x59, 0xca, 0x12, 0x65, 0x2c, 0x42, 0x0d, 0xa5,
	0x4f, 0x80, 0x20, 0xe3, 0x28, 0xb3, 0x42, 0x56, 0x69, 0x9d, 0xca, 0xfc, 0x2a, 0x9b, 0xf4, 0x1d,
	0x10, 0xce, 0xf0, 0x6f, 0xf4, 0x2d, 0x64, 0x1f, 0x81, 0x8b, 0x8c, 0x73, 0xb1, 0x5e, 0x5f, 0xa9,
	0xf7, 0x1a, 0x5c, 0xce, 0xf0, 0x02, 0x76, 0x0b, 0xa1, 0x05, 0xec, 0xab, 0xd9, 0x2e, 0x65, 0x11,
	0x8a, 0x9f, 0x51, 0x19, 0x93, 0x29, 0x0c, 0x15, 0x57, 0x65, 0xb6, 0x80, 0x5c, 0x26, 0x51, 0xad,
	0xb0, 0x05, 0xa8, 0x29, 0xf3, 0x72, 0x65, 0xe6, 0xa1, 0x42, 0xfa, 0x18, 0xc6, 0xc8, 0xf8, 0xec,
	0x7c, 0xa5, 0x77, 0x01, 0xdf, 0x2e, 0xc4, 0x86, 0x10, 0xd8, 0xc1, 0xce, 0xd3, 0x5e, 0xa8, 0x63,
	0xfa, 0xdb, 0x82, 0x31, 0x67, 0x78, 0x19, 0x78, 0x73, 0xf3, 0x5b, 0xaf, 0x83, 0xeb, 0xbc, 0x1e,
	0x81, 0x83, 0xf1, 0x42, 0x6c, 0x2a, 0xbd, 0x22, 0x2e, 0xbb, 0xdb, 0x5f, 0x6e, 0xad, 0xff, 0xa1,
	0x50, 0xf3, 0x0a, 0x0d, 0x8c, 0x1e, 0xc0, 0x08, 0x19, 0x9f, 0xe7, 0x69, 0xad, 0xbb, 0xf4, 0x04,
	0x46, 0x9c, 0xe1, 0x45, 0xde, 0x23, 0x6c, 0xdf, 0xd3, 0xb5, 0x84, 0x9f, 0xc1, 0xed, 0x95, 0xff,
	0xf5, 0x5a, 0xd4, 0x47, 0x82, 0xb2, 0xc9, 0xeb, 0xee, 0x23, 0xd1, 0x09, 0x79, 0x08, 0x30, 0x3b,
	0x2f, 0xd2, 0x52, 0x7c, 0x4c, 0x33, 0xa1, 0xed, 0xdb, 0x61, 0xaf, 0x12, 0xec, 0x7f, 0x71, 0x8f,
	0xf4, 0xbf, 0xe4, 0x9b, 0xfa, 0xe1, 0x9c, 0x3a, 0x3a, 0x7e, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x63, 0x4c, 0x72, 0x3a, 0x7f, 0x04, 0x00, 0x00,
}
