// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stage.proto

package proto_stage

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//错误码
type ERRORSTAGECODE int32

const (
	ERRORSTAGECODE_ERROR_Ok              ERRORSTAGECODE = 0
	ERRORSTAGECODE_ERROR_ModeErr         ERRORSTAGECODE = 1
	ERRORSTAGECODE_ERROR_NoStageErr      ERRORSTAGECODE = 2
	ERRORSTAGECODE_ERROR_NoMatchStageErr ERRORSTAGECODE = 3
	ERRORSTAGECODE_ERROR_PARAMERROR      ERRORSTAGECODE = 4
	ERRORSTAGECODE_ERROR_ALPASSERROR     ERRORSTAGECODE = 5
)

var ERRORSTAGECODE_name = map[int32]string{
	0: "ERROR_Ok",
	1: "ERROR_ModeErr",
	2: "ERROR_NoStageErr",
	3: "ERROR_NoMatchStageErr",
	4: "ERROR_PARAMERROR",
	5: "ERROR_ALPASSERROR",
}

var ERRORSTAGECODE_value = map[string]int32{
	"ERROR_Ok":              0,
	"ERROR_ModeErr":         1,
	"ERROR_NoStageErr":      2,
	"ERROR_NoMatchStageErr": 3,
	"ERROR_PARAMERROR":      4,
	"ERROR_ALPASSERROR":     5,
}

func (x ERRORSTAGECODE) String() string {
	return proto.EnumName(ERRORSTAGECODE_name, int32(x))
}

func (ERRORSTAGECODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{0}
}

type C2SInitStage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitStage) Reset()         { *m = C2SInitStage{} }
func (m *C2SInitStage) String() string { return proto.CompactTextString(m) }
func (*C2SInitStage) ProtoMessage()    {}
func (*C2SInitStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{0}
}

func (m *C2SInitStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitStage.Unmarshal(m, b)
}
func (m *C2SInitStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitStage.Marshal(b, m, deterministic)
}
func (m *C2SInitStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitStage.Merge(m, src)
}
func (m *C2SInitStage) XXX_Size() int {
	return xxx_messageInfo_C2SInitStage.Size(m)
}
func (m *C2SInitStage) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitStage.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitStage proto.InternalMessageInfo

type S2CInitStage struct {
	CurChapter           int32                   `protobuf:"varint,1,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	CurStageId           int32                   `protobuf:"varint,2,opt,name=CurStageId,proto3" json:"CurStageId,omitempty"`
	Id                   map[int32]*CycleChapter `protobuf:"bytes,3,rep,name=Id,proto3" json:"Id,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurCycle             int32                   `protobuf:"varint,4,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *S2CInitStage) Reset()         { *m = S2CInitStage{} }
func (m *S2CInitStage) String() string { return proto.CompactTextString(m) }
func (*S2CInitStage) ProtoMessage()    {}
func (*S2CInitStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{1}
}

func (m *S2CInitStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitStage.Unmarshal(m, b)
}
func (m *S2CInitStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitStage.Marshal(b, m, deterministic)
}
func (m *S2CInitStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitStage.Merge(m, src)
}
func (m *S2CInitStage) XXX_Size() int {
	return xxx_messageInfo_S2CInitStage.Size(m)
}
func (m *S2CInitStage) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitStage.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitStage proto.InternalMessageInfo

func (m *S2CInitStage) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

func (m *S2CInitStage) GetCurStageId() int32 {
	if m != nil {
		return m.CurStageId
	}
	return 0
}

func (m *S2CInitStage) GetId() map[int32]*CycleChapter {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *S2CInitStage) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

type CycleChapter struct {
	Id                   map[int32]*StageChapter `protobuf:"bytes,1,rep,name=Id,proto3" json:"Id,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CycleChapter) Reset()         { *m = CycleChapter{} }
func (m *CycleChapter) String() string { return proto.CompactTextString(m) }
func (*CycleChapter) ProtoMessage()    {}
func (*CycleChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{2}
}

func (m *CycleChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CycleChapter.Unmarshal(m, b)
}
func (m *CycleChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CycleChapter.Marshal(b, m, deterministic)
}
func (m *CycleChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CycleChapter.Merge(m, src)
}
func (m *CycleChapter) XXX_Size() int {
	return xxx_messageInfo_CycleChapter.Size(m)
}
func (m *CycleChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_CycleChapter.DiscardUnknown(m)
}

var xxx_messageInfo_CycleChapter proto.InternalMessageInfo

func (m *CycleChapter) GetId() map[int32]*StageChapter {
	if m != nil {
		return m.Id
	}
	return nil
}

type StageChapter struct {
	Id                   map[int32]*StateOption `protobuf:"bytes,1,rep,name=Id,proto3" json:"Id,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Story                *HiddenStoryline       `protobuf:"bytes,2,opt,name=Story,proto3" json:"Story,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StageChapter) Reset()         { *m = StageChapter{} }
func (m *StageChapter) String() string { return proto.CompactTextString(m) }
func (*StageChapter) ProtoMessage()    {}
func (*StageChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{3}
}

func (m *StageChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StageChapter.Unmarshal(m, b)
}
func (m *StageChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StageChapter.Marshal(b, m, deterministic)
}
func (m *StageChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StageChapter.Merge(m, src)
}
func (m *StageChapter) XXX_Size() int {
	return xxx_messageInfo_StageChapter.Size(m)
}
func (m *StageChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_StageChapter.DiscardUnknown(m)
}

var xxx_messageInfo_StageChapter proto.InternalMessageInfo

func (m *StageChapter) GetId() map[int32]*StateOption {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *StageChapter) GetStory() *HiddenStoryline {
	if m != nil {
		return m.Story
	}
	return nil
}

type StateOption struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Exp                  int32    `protobuf:"varint,2,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Pass                 bool     `protobuf:"varint,3,opt,name=Pass,proto3" json:"Pass,omitempty"`
	PassBoss             int32    `protobuf:"varint,4,opt,name=PassBoss,proto3" json:"PassBoss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateOption) Reset()         { *m = StateOption{} }
func (m *StateOption) String() string { return proto.CompactTextString(m) }
func (*StateOption) ProtoMessage()    {}
func (*StateOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{4}
}

func (m *StateOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateOption.Unmarshal(m, b)
}
func (m *StateOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateOption.Marshal(b, m, deterministic)
}
func (m *StateOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateOption.Merge(m, src)
}
func (m *StateOption) XXX_Size() int {
	return xxx_messageInfo_StateOption.Size(m)
}
func (m *StateOption) XXX_DiscardUnknown() {
	xxx_messageInfo_StateOption.DiscardUnknown(m)
}

var xxx_messageInfo_StateOption proto.InternalMessageInfo

func (m *StateOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StateOption) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *StateOption) GetPass() bool {
	if m != nil {
		return m.Pass
	}
	return false
}

func (m *StateOption) GetPassBoss() int32 {
	if m != nil {
		return m.PassBoss
	}
	return 0
}

//隐藏剧情
type HiddenStoryline struct {
	UnlockHidden         bool     `protobuf:"varint,1,opt,name=UnlockHidden,proto3" json:"UnlockHidden,omitempty"`
	FinishStory          bool     `protobuf:"varint,2,opt,name=FinishStory,proto3" json:"FinishStory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiddenStoryline) Reset()         { *m = HiddenStoryline{} }
func (m *HiddenStoryline) String() string { return proto.CompactTextString(m) }
func (*HiddenStoryline) ProtoMessage()    {}
func (*HiddenStoryline) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{5}
}

func (m *HiddenStoryline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiddenStoryline.Unmarshal(m, b)
}
func (m *HiddenStoryline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiddenStoryline.Marshal(b, m, deterministic)
}
func (m *HiddenStoryline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiddenStoryline.Merge(m, src)
}
func (m *HiddenStoryline) XXX_Size() int {
	return xxx_messageInfo_HiddenStoryline.Size(m)
}
func (m *HiddenStoryline) XXX_DiscardUnknown() {
	xxx_messageInfo_HiddenStoryline.DiscardUnknown(m)
}

var xxx_messageInfo_HiddenStoryline proto.InternalMessageInfo

func (m *HiddenStoryline) GetUnlockHidden() bool {
	if m != nil {
		return m.UnlockHidden
	}
	return false
}

func (m *HiddenStoryline) GetFinishStory() bool {
	if m != nil {
		return m.FinishStory
	}
	return false
}

//解锁隐藏剧情
type C2SUnLockHiddenStory struct {
	CurChapter           int32    `protobuf:"varint,1,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	CurStageId           int32    `protobuf:"varint,2,opt,name=CurStageId,proto3" json:"CurStageId,omitempty"`
	CurCycle             int32    `protobuf:"varint,3,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUnLockHiddenStory) Reset()         { *m = C2SUnLockHiddenStory{} }
func (m *C2SUnLockHiddenStory) String() string { return proto.CompactTextString(m) }
func (*C2SUnLockHiddenStory) ProtoMessage()    {}
func (*C2SUnLockHiddenStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{6}
}

func (m *C2SUnLockHiddenStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUnLockHiddenStory.Unmarshal(m, b)
}
func (m *C2SUnLockHiddenStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUnLockHiddenStory.Marshal(b, m, deterministic)
}
func (m *C2SUnLockHiddenStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUnLockHiddenStory.Merge(m, src)
}
func (m *C2SUnLockHiddenStory) XXX_Size() int {
	return xxx_messageInfo_C2SUnLockHiddenStory.Size(m)
}
func (m *C2SUnLockHiddenStory) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUnLockHiddenStory.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUnLockHiddenStory proto.InternalMessageInfo

func (m *C2SUnLockHiddenStory) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

func (m *C2SUnLockHiddenStory) GetCurStageId() int32 {
	if m != nil {
		return m.CurStageId
	}
	return 0
}

func (m *C2SUnLockHiddenStory) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

type S2CUnLockHiddenStory struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CUnLockHiddenStory) Reset()         { *m = S2CUnLockHiddenStory{} }
func (m *S2CUnLockHiddenStory) String() string { return proto.CompactTextString(m) }
func (*S2CUnLockHiddenStory) ProtoMessage()    {}
func (*S2CUnLockHiddenStory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{7}
}

func (m *S2CUnLockHiddenStory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUnLockHiddenStory.Unmarshal(m, b)
}
func (m *S2CUnLockHiddenStory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUnLockHiddenStory.Marshal(b, m, deterministic)
}
func (m *S2CUnLockHiddenStory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUnLockHiddenStory.Merge(m, src)
}
func (m *S2CUnLockHiddenStory) XXX_Size() int {
	return xxx_messageInfo_S2CUnLockHiddenStory.Size(m)
}
func (m *S2CUnLockHiddenStory) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUnLockHiddenStory.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUnLockHiddenStory proto.InternalMessageInfo

func (m *S2CUnLockHiddenStory) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

//关卡变化
type PushChange struct {
	Id                   map[int32]*CycleChapter `protobuf:"bytes,1,rep,name=Id,proto3" json:"Id,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurChapter           int32                   `protobuf:"varint,2,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	CurStageId           int32                   `protobuf:"varint,3,opt,name=CurStageId,proto3" json:"CurStageId,omitempty"`
	Awards               []*proto_public.Item    `protobuf:"bytes,4,rep,name=Awards,proto3" json:"Awards,omitempty"`
	KillBoss             bool                    `protobuf:"varint,5,opt,name=KillBoss,proto3" json:"KillBoss,omitempty"`
	CurCycle             int32                   `protobuf:"varint,6,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PushChange) Reset()         { *m = PushChange{} }
func (m *PushChange) String() string { return proto.CompactTextString(m) }
func (*PushChange) ProtoMessage()    {}
func (*PushChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{8}
}

func (m *PushChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChange.Unmarshal(m, b)
}
func (m *PushChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChange.Marshal(b, m, deterministic)
}
func (m *PushChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChange.Merge(m, src)
}
func (m *PushChange) XXX_Size() int {
	return xxx_messageInfo_PushChange.Size(m)
}
func (m *PushChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushChange proto.InternalMessageInfo

func (m *PushChange) GetId() map[int32]*CycleChapter {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PushChange) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

func (m *PushChange) GetCurStageId() int32 {
	if m != nil {
		return m.CurStageId
	}
	return 0
}

func (m *PushChange) GetAwards() []*proto_public.Item {
	if m != nil {
		return m.Awards
	}
	return nil
}

func (m *PushChange) GetKillBoss() bool {
	if m != nil {
		return m.KillBoss
	}
	return false
}

func (m *PushChange) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

//击杀敌人
type C2SKillEnemy struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	StageId              int32    `protobuf:"varint,3,opt,name=StageId,proto3" json:"StageId,omitempty"`
	Index                int32    `protobuf:"varint,4,opt,name=Index,proto3" json:"Index,omitempty"`
	CurCycle             int32    `protobuf:"varint,5,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	CurChapter           int32    `protobuf:"varint,6,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SKillEnemy) Reset()         { *m = C2SKillEnemy{} }
func (m *C2SKillEnemy) String() string { return proto.CompactTextString(m) }
func (*C2SKillEnemy) ProtoMessage()    {}
func (*C2SKillEnemy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{9}
}

func (m *C2SKillEnemy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SKillEnemy.Unmarshal(m, b)
}
func (m *C2SKillEnemy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SKillEnemy.Marshal(b, m, deterministic)
}
func (m *C2SKillEnemy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SKillEnemy.Merge(m, src)
}
func (m *C2SKillEnemy) XXX_Size() int {
	return xxx_messageInfo_C2SKillEnemy.Size(m)
}
func (m *C2SKillEnemy) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SKillEnemy.DiscardUnknown(m)
}

var xxx_messageInfo_C2SKillEnemy proto.InternalMessageInfo

func (m *C2SKillEnemy) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *C2SKillEnemy) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SKillEnemy) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

func (m *C2SKillEnemy) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *C2SKillEnemy) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

func (m *C2SKillEnemy) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

type S2CKillEnemy struct {
	Code                 ERRORSTAGECODE `protobuf:"varint,1,opt,name=Code,proto3,enum=Proto.Stage.ERRORSTAGECODE" json:"Code,omitempty"`
	Type                 int32          `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Id                   int32          `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	StageId              int32          `protobuf:"varint,4,opt,name=StageId,proto3" json:"StageId,omitempty"`
	Chapter              int32          `protobuf:"varint,5,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	CurCycle             int32          `protobuf:"varint,6,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CKillEnemy) Reset()         { *m = S2CKillEnemy{} }
func (m *S2CKillEnemy) String() string { return proto.CompactTextString(m) }
func (*S2CKillEnemy) ProtoMessage()    {}
func (*S2CKillEnemy) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{10}
}

func (m *S2CKillEnemy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CKillEnemy.Unmarshal(m, b)
}
func (m *S2CKillEnemy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CKillEnemy.Marshal(b, m, deterministic)
}
func (m *S2CKillEnemy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CKillEnemy.Merge(m, src)
}
func (m *S2CKillEnemy) XXX_Size() int {
	return xxx_messageInfo_S2CKillEnemy.Size(m)
}
func (m *S2CKillEnemy) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CKillEnemy.DiscardUnknown(m)
}

var xxx_messageInfo_S2CKillEnemy proto.InternalMessageInfo

func (m *S2CKillEnemy) GetCode() ERRORSTAGECODE {
	if m != nil {
		return m.Code
	}
	return ERRORSTAGECODE_ERROR_Ok
}

func (m *S2CKillEnemy) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *S2CKillEnemy) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *S2CKillEnemy) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

func (m *S2CKillEnemy) GetChapter() int32 {
	if m != nil {
		return m.Chapter
	}
	return 0
}

func (m *S2CKillEnemy) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

//挑战关卡boss
type C2SChallengeStageBossBattle struct {
	CurChapter           int32    `protobuf:"varint,1,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	CurStageId           int32    `protobuf:"varint,2,opt,name=CurStageId,proto3" json:"CurStageId,omitempty"`
	CurCycle             int32    `protobuf:"varint,3,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChallengeStageBossBattle) Reset()         { *m = C2SChallengeStageBossBattle{} }
func (m *C2SChallengeStageBossBattle) String() string { return proto.CompactTextString(m) }
func (*C2SChallengeStageBossBattle) ProtoMessage()    {}
func (*C2SChallengeStageBossBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{11}
}

func (m *C2SChallengeStageBossBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChallengeStageBossBattle.Unmarshal(m, b)
}
func (m *C2SChallengeStageBossBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChallengeStageBossBattle.Marshal(b, m, deterministic)
}
func (m *C2SChallengeStageBossBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChallengeStageBossBattle.Merge(m, src)
}
func (m *C2SChallengeStageBossBattle) XXX_Size() int {
	return xxx_messageInfo_C2SChallengeStageBossBattle.Size(m)
}
func (m *C2SChallengeStageBossBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChallengeStageBossBattle.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChallengeStageBossBattle proto.InternalMessageInfo

func (m *C2SChallengeStageBossBattle) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

func (m *C2SChallengeStageBossBattle) GetCurStageId() int32 {
	if m != nil {
		return m.CurStageId
	}
	return 0
}

func (m *C2SChallengeStageBossBattle) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

type S2CChallengeStageBattle struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	BattleId             int64                        `protobuf:"varint,2,opt,name=BattleId,proto3" json:"BattleId,omitempty"`
	Data                 *proto_public.BattleHeroData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CurChapter           int32                        `protobuf:"varint,4,opt,name=CurChapter,proto3" json:"CurChapter,omitempty"`
	CurStageId           int32                        `protobuf:"varint,5,opt,name=CurStageId,proto3" json:"CurStageId,omitempty"`
	CurCycle             int32                        `protobuf:"varint,6,opt,name=CurCycle,proto3" json:"CurCycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CChallengeStageBattle) Reset()         { *m = S2CChallengeStageBattle{} }
func (m *S2CChallengeStageBattle) String() string { return proto.CompactTextString(m) }
func (*S2CChallengeStageBattle) ProtoMessage()    {}
func (*S2CChallengeStageBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{12}
}

func (m *S2CChallengeStageBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChallengeStageBattle.Unmarshal(m, b)
}
func (m *S2CChallengeStageBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChallengeStageBattle.Marshal(b, m, deterministic)
}
func (m *S2CChallengeStageBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChallengeStageBattle.Merge(m, src)
}
func (m *S2CChallengeStageBattle) XXX_Size() int {
	return xxx_messageInfo_S2CChallengeStageBattle.Size(m)
}
func (m *S2CChallengeStageBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChallengeStageBattle.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChallengeStageBattle proto.InternalMessageInfo

func (m *S2CChallengeStageBattle) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CChallengeStageBattle) GetBattleId() int64 {
	if m != nil {
		return m.BattleId
	}
	return 0
}

func (m *S2CChallengeStageBattle) GetData() *proto_public.BattleHeroData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *S2CChallengeStageBattle) GetCurChapter() int32 {
	if m != nil {
		return m.CurChapter
	}
	return 0
}

func (m *S2CChallengeStageBattle) GetCurStageId() int32 {
	if m != nil {
		return m.CurStageId
	}
	return 0
}

func (m *S2CChallengeStageBattle) GetCurCycle() int32 {
	if m != nil {
		return m.CurCycle
	}
	return 0
}

//获取自由移动的玩家
type C2SGetFreePlayer struct {
	Chapter              int32    `protobuf:"varint,1,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	StageId              int32    `protobuf:"varint,2,opt,name=StageId,proto3" json:"StageId,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
	Cycle                int32    `protobuf:"varint,4,opt,name=Cycle,proto3" json:"Cycle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetFreePlayer) Reset()         { *m = C2SGetFreePlayer{} }
func (m *C2SGetFreePlayer) String() string { return proto.CompactTextString(m) }
func (*C2SGetFreePlayer) ProtoMessage()    {}
func (*C2SGetFreePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{13}
}

func (m *C2SGetFreePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetFreePlayer.Unmarshal(m, b)
}
func (m *C2SGetFreePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetFreePlayer.Marshal(b, m, deterministic)
}
func (m *C2SGetFreePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetFreePlayer.Merge(m, src)
}
func (m *C2SGetFreePlayer) XXX_Size() int {
	return xxx_messageInfo_C2SGetFreePlayer.Size(m)
}
func (m *C2SGetFreePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetFreePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetFreePlayer proto.InternalMessageInfo

func (m *C2SGetFreePlayer) GetChapter() int32 {
	if m != nil {
		return m.Chapter
	}
	return 0
}

func (m *C2SGetFreePlayer) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

func (m *C2SGetFreePlayer) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *C2SGetFreePlayer) GetCycle() int32 {
	if m != nil {
		return m.Cycle
	}
	return 0
}

type S2CGetFreePlayer struct {
	Code                 proto_public.CommonErrorCode   `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	HeroInfos            []*proto_public.BattleHeroData `protobuf:"bytes,2,rep,name=HeroInfos,proto3" json:"HeroInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *S2CGetFreePlayer) Reset()         { *m = S2CGetFreePlayer{} }
func (m *S2CGetFreePlayer) String() string { return proto.CompactTextString(m) }
func (*S2CGetFreePlayer) ProtoMessage()    {}
func (*S2CGetFreePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{14}
}

func (m *S2CGetFreePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetFreePlayer.Unmarshal(m, b)
}
func (m *S2CGetFreePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetFreePlayer.Marshal(b, m, deterministic)
}
func (m *S2CGetFreePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetFreePlayer.Merge(m, src)
}
func (m *S2CGetFreePlayer) XXX_Size() int {
	return xxx_messageInfo_S2CGetFreePlayer.Size(m)
}
func (m *S2CGetFreePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetFreePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetFreePlayer proto.InternalMessageInfo

func (m *S2CGetFreePlayer) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CGetFreePlayer) GetHeroInfos() []*proto_public.BattleHeroData {
	if m != nil {
		return m.HeroInfos
	}
	return nil
}

//---------------结算-------------------
type S2CStageSettle struct {
	IsWin                bool       `protobuf:"varint,1,opt,name=IsWin,proto3" json:"IsWin,omitempty"`
	PlayerId             int64      `protobuf:"varint,2,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	Items                []*Items   `protobuf:"bytes,3,rep,name=Items,proto3" json:"Items,omitempty"`
	PvePlayer            *PvePlayer `protobuf:"bytes,4,opt,name=PvePlayer,proto3" json:"PvePlayer,omitempty"`
	StageId              int32      `protobuf:"varint,5,opt,name=StageId,proto3" json:"StageId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *S2CStageSettle) Reset()         { *m = S2CStageSettle{} }
func (m *S2CStageSettle) String() string { return proto.CompactTextString(m) }
func (*S2CStageSettle) ProtoMessage()    {}
func (*S2CStageSettle) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{15}
}

func (m *S2CStageSettle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CStageSettle.Unmarshal(m, b)
}
func (m *S2CStageSettle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CStageSettle.Marshal(b, m, deterministic)
}
func (m *S2CStageSettle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CStageSettle.Merge(m, src)
}
func (m *S2CStageSettle) XXX_Size() int {
	return xxx_messageInfo_S2CStageSettle.Size(m)
}
func (m *S2CStageSettle) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CStageSettle.DiscardUnknown(m)
}

var xxx_messageInfo_S2CStageSettle proto.InternalMessageInfo

func (m *S2CStageSettle) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *S2CStageSettle) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *S2CStageSettle) GetItems() []*Items {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *S2CStageSettle) GetPvePlayer() *PvePlayer {
	if m != nil {
		return m.PvePlayer
	}
	return nil
}

func (m *S2CStageSettle) GetStageId() int32 {
	if m != nil {
		return m.StageId
	}
	return 0
}

type Items struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{16}
}

func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (m *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(m, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Items) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Items) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type PvePlayer struct {
	Damage               int64    `protobuf:"varint,1,opt,name=Damage,proto3" json:"Damage,omitempty"`
	WithStandDamage      int64    `protobuf:"varint,2,opt,name=WithStandDamage,proto3" json:"WithStandDamage,omitempty"`
	Heal                 int64    `protobuf:"varint,3,opt,name=Heal,proto3" json:"Heal,omitempty"`
	KillNum              int32    `protobuf:"varint,4,opt,name=KillNum,proto3" json:"KillNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PvePlayer) Reset()         { *m = PvePlayer{} }
func (m *PvePlayer) String() string { return proto.CompactTextString(m) }
func (*PvePlayer) ProtoMessage()    {}
func (*PvePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a92368e03f1c791, []int{17}
}

func (m *PvePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PvePlayer.Unmarshal(m, b)
}
func (m *PvePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PvePlayer.Marshal(b, m, deterministic)
}
func (m *PvePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PvePlayer.Merge(m, src)
}
func (m *PvePlayer) XXX_Size() int {
	return xxx_messageInfo_PvePlayer.Size(m)
}
func (m *PvePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_PvePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_PvePlayer proto.InternalMessageInfo

func (m *PvePlayer) GetDamage() int64 {
	if m != nil {
		return m.Damage
	}
	return 0
}

func (m *PvePlayer) GetWithStandDamage() int64 {
	if m != nil {
		return m.WithStandDamage
	}
	return 0
}

func (m *PvePlayer) GetHeal() int64 {
	if m != nil {
		return m.Heal
	}
	return 0
}

func (m *PvePlayer) GetKillNum() int32 {
	if m != nil {
		return m.KillNum
	}
	return 0
}

func init() {
	proto.RegisterEnum("Proto.Stage.ERRORSTAGECODE", ERRORSTAGECODE_name, ERRORSTAGECODE_value)
	proto.RegisterType((*C2SInitStage)(nil), "Proto.Stage.C2SInitStage")
	proto.RegisterType((*S2CInitStage)(nil), "Proto.Stage.S2CInitStage")
	proto.RegisterMapType((map[int32]*CycleChapter)(nil), "Proto.Stage.S2CInitStage.IdEntry")
	proto.RegisterType((*CycleChapter)(nil), "Proto.Stage.CycleChapter")
	proto.RegisterMapType((map[int32]*StageChapter)(nil), "Proto.Stage.CycleChapter.IdEntry")
	proto.RegisterType((*StageChapter)(nil), "Proto.Stage.StageChapter")
	proto.RegisterMapType((map[int32]*StateOption)(nil), "Proto.Stage.StageChapter.IdEntry")
	proto.RegisterType((*StateOption)(nil), "Proto.Stage.StateOption")
	proto.RegisterType((*HiddenStoryline)(nil), "Proto.Stage.HiddenStoryline")
	proto.RegisterType((*C2SUnLockHiddenStory)(nil), "Proto.Stage.C2SUnLockHiddenStory")
	proto.RegisterType((*S2CUnLockHiddenStory)(nil), "Proto.Stage.S2CUnLockHiddenStory")
	proto.RegisterType((*PushChange)(nil), "Proto.Stage.PushChange")
	proto.RegisterMapType((map[int32]*CycleChapter)(nil), "Proto.Stage.PushChange.IdEntry")
	proto.RegisterType((*C2SKillEnemy)(nil), "Proto.Stage.C2SKillEnemy")
	proto.RegisterType((*S2CKillEnemy)(nil), "Proto.Stage.S2CKillEnemy")
	proto.RegisterType((*C2SChallengeStageBossBattle)(nil), "Proto.Stage.C2SChallengeStageBossBattle")
	proto.RegisterType((*S2CChallengeStageBattle)(nil), "Proto.Stage.S2CChallengeStageBattle")
	proto.RegisterType((*C2SGetFreePlayer)(nil), "Proto.Stage.C2SGetFreePlayer")
	proto.RegisterType((*S2CGetFreePlayer)(nil), "Proto.Stage.S2CGetFreePlayer")
	proto.RegisterType((*S2CStageSettle)(nil), "Proto.Stage.S2CStageSettle")
	proto.RegisterType((*Items)(nil), "Proto.Stage.Items")
	proto.RegisterType((*PvePlayer)(nil), "Proto.Stage.PvePlayer")
}

func init() {
	proto.RegisterFile("stage.proto", fileDescriptor_8a92368e03f1c791)
}

var fileDescriptor_8a92368e03f1c791 = []byte{
	// 990 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x49, 0x51, 0x56, 0x46, 0xaa, 0xa2, 0x2c, 0x9c, 0x54, 0x71, 0xfa, 0xe3, 0xf2, 0x24,
	0xe4, 0x20, 0x37, 0x6c, 0x0f, 0x45, 0x80, 0x1e, 0x64, 0x5a, 0x89, 0x85, 0xc6, 0x91, 0xb0, 0x4c,
	0x60, 0xa0, 0x17, 0x83, 0x11, 0xb7, 0x16, 0x61, 0x8a, 0x14, 0xc8, 0x55, 0x1a, 0xa1, 0xa7, 0x3e,
	0x41, 0x0f, 0xbd, 0xf7, 0x25, 0x72, 0xed, 0xb9, 0xaf, 0xd3, 0x5b, 0xcf, 0xc5, 0xce, 0xae, 0xc4,
	0x5d, 0xd9, 0x50, 0xda, 0x06, 0xb9, 0x48, 0x3b, 0x3f, 0xbb, 0xf3, 0x7d, 0x33, 0xb3, 0xc3, 0x85,
	0x66, 0xc9, 0xa3, 0x4b, 0xd6, 0x5f, 0x14, 0x39, 0xcf, 0x49, 0x73, 0x22, 0xfe, 0xfa, 0xa1, 0x50,
	0x1d, 0xb4, 0x16, 0xcb, 0x57, 0x69, 0x32, 0x95, 0x26, 0xaf, 0x0d, 0xad, 0xc0, 0x0f, 0x47, 0x59,
	0xc2, 0xd1, 0xea, 0xfd, 0x65, 0x41, 0x2b, 0xf4, 0x83, 0x8d, 0x82, 0x7c, 0x0e, 0x10, 0x2c, 0x8b,
	0x60, 0x16, 0x2d, 0x38, 0x2b, 0xba, 0xd6, 0xa1, 0xd5, 0x73, 0xa9, 0xa6, 0x51, 0x76, 0xf4, 0x1d,
	0xc5, 0x5d, 0x7b, 0x63, 0x57, 0x1a, 0xf2, 0x08, 0xec, 0x51, 0xdc, 0x75, 0x0e, 0x9d, 0x5e, 0xd3,
	0xff, 0xb2, 0xaf, 0x01, 0xe9, 0xeb, 0x61, 0xfa, 0xa3, 0x78, 0x98, 0xf1, 0x62, 0x45, 0xed, 0x51,
	0x4c, 0x0e, 0xa0, 0x21, 0x02, 0xac, 0xa6, 0x29, 0xeb, 0xd6, 0xf0, 0xc0, 0x8d, 0x7c, 0x30, 0x81,
	0x3d, 0xe5, 0x4a, 0x3a, 0xe0, 0x5c, 0xb1, 0x95, 0x82, 0x24, 0x96, 0xe4, 0x08, 0xdc, 0xd7, 0x51,
	0xba, 0x64, 0x08, 0xa3, 0xe9, 0xdf, 0x37, 0xc2, 0xe1, 0x7e, 0x85, 0x9a, 0x4a, 0xbf, 0xc7, 0xf6,
	0xb7, 0x96, 0xf7, 0x9b, 0x05, 0x2d, 0xdd, 0xa6, 0x10, 0x5b, 0x37, 0x20, 0xd6, 0xdd, 0x74, 0xc4,
	0xef, 0x81, 0x0a, 0x7f, 0x6f, 0x40, 0xf5, 0xa7, 0xa8, 0x83, 0x66, 0xdb, 0x81, 0x4a, 0x77, 0x33,
	0xf2, 0xe8, 0x83, 0x1b, 0xf2, 0xbc, 0x58, 0xa9, 0xc0, 0x9f, 0x1a, 0xbb, 0x4e, 0x93, 0x38, 0x66,
	0x19, 0xda, 0xd3, 0x24, 0x63, 0x54, 0xba, 0x1e, 0x8c, 0x77, 0x31, 0xe9, 0x9b, 0x4c, 0xba, 0xdb,
	0x30, 0x38, 0x1b, 0x2f, 0x78, 0x92, 0x67, 0x3a, 0x91, 0x0b, 0x68, 0x6a, 0x16, 0xd2, 0x56, 0x34,
	0xc4, 0x99, 0x02, 0x63, 0x07, 0x9c, 0xe1, 0x9b, 0x85, 0xea, 0x1b, 0xb1, 0x24, 0x04, 0x6a, 0x93,
	0xa8, 0x2c, 0xbb, 0xce, 0xa1, 0xd5, 0x6b, 0x50, 0x5c, 0x8b, 0x8e, 0x10, 0xff, 0xc7, 0x79, 0x59,
	0xae, 0x3b, 0x62, 0x2d, 0x7b, 0xe7, 0x70, 0x7b, 0x8b, 0x0b, 0xf1, 0xa0, 0xf5, 0x32, 0x4b, 0xf3,
	0xe9, 0x95, 0x34, 0x60, 0xb8, 0x06, 0x35, 0x74, 0xe4, 0x10, 0x9a, 0x4f, 0x92, 0x2c, 0x29, 0x67,
	0x55, 0x8a, 0x1a, 0x54, 0x57, 0x79, 0x05, 0xec, 0x07, 0x7e, 0xf8, 0x32, 0x7b, 0xb6, 0xd9, 0x84,
	0xfa, 0xf7, 0xbe, 0x11, 0x7a, 0x7b, 0x3b, 0x66, 0x7b, 0x7b, 0x23, 0xd8, 0x0f, 0xfd, 0xe0, 0x7a,
	0xcc, 0x47, 0x50, 0x9b, 0xe6, 0x31, 0xc3, 0x68, 0x6d, 0xff, 0x33, 0x95, 0xf8, 0x89, 0xbc, 0xc9,
	0x41, 0x3e, 0x9f, 0xe7, 0xd9, 0xb0, 0x28, 0xf2, 0x22, 0xc8, 0x63, 0x46, 0xd1, 0xd5, 0x7b, 0x6b,
	0x03, 0x4c, 0x96, 0xe5, 0x2c, 0x98, 0x45, 0xd9, 0x25, 0x23, 0x47, 0x5a, 0xff, 0x7c, 0x61, 0x14,
	0xae, 0x72, 0x32, 0xba, 0xc7, 0xa4, 0x69, 0xbf, 0x83, 0xa6, 0x73, 0x8d, 0xe6, 0x43, 0xa8, 0x0f,
	0x7e, 0x8a, 0x8a, 0x58, 0x54, 0x4c, 0x04, 0x25, 0x26, 0xe8, 0x11, 0x67, 0x73, 0xaa, 0x3c, 0x44,
	0x4a, 0xbe, 0x4f, 0xd2, 0x14, 0xeb, 0xeb, 0x62, 0x25, 0x36, 0xb2, 0x91, 0xae, 0xfa, 0x07, 0x9f,
	0x06, 0xbf, 0x5b, 0x38, 0x10, 0x45, 0xf4, 0x61, 0xc6, 0xe6, 0x2b, 0xd1, 0x8e, 0x2f, 0x56, 0x0b,
	0xa6, 0x0e, 0xc6, 0xb5, 0x6a, 0x62, 0x7b, 0xd3, 0xc4, 0x5d, 0xd8, 0x33, 0xf3, 0xb0, 0x16, 0xc9,
	0x3e, 0xb8, 0xa3, 0x2c, 0x66, 0x6f, 0x54, 0xd7, 0x4a, 0xc1, 0xa0, 0xe4, 0x9a, 0x94, 0xb6, 0xd2,
	0x5e, 0xdf, 0x4e, 0xbb, 0xf7, 0x56, 0x0e, 0xe8, 0x0a, 0xe0, 0x11, 0xd4, 0x82, 0xaa, 0x35, 0x1e,
	0x18, 0x2c, 0x87, 0x94, 0x8e, 0x69, 0xf8, 0x62, 0xf0, 0x74, 0x18, 0x8c, 0x4f, 0x86, 0x14, 0x1d,
	0x37, 0x8c, 0xec, 0x6b, 0x8c, 0x9c, 0x9b, 0x18, 0xd5, 0x4c, 0x46, 0x5d, 0xd8, 0x5b, 0x83, 0x93,
	0xd0, 0xd7, 0xe2, 0xae, 0x42, 0x79, 0x2b, 0x78, 0x10, 0xf8, 0x61, 0x30, 0x8b, 0xd2, 0x94, 0x65,
	0x97, 0x0c, 0x0f, 0x13, 0xd5, 0x3d, 0x8e, 0x38, 0x4f, 0xd9, 0x07, 0xbd, 0x52, 0x7f, 0x5b, 0xf0,
	0x49, 0xe8, 0x07, 0x5b, 0xb1, 0x65, 0xdc, 0xff, 0x7e, 0xad, 0x44, 0x28, 0xb9, 0x59, 0x01, 0x71,
	0xe8, 0x46, 0x26, 0x5f, 0x41, 0x2d, 0x8e, 0x78, 0x84, 0x10, 0xaa, 0x79, 0xab, 0x8e, 0x93, 0x5e,
	0xa7, 0xac, 0xc8, 0x4f, 0x22, 0x1e, 0x51, 0xf4, 0xdc, 0x22, 0x5e, 0x7b, 0x07, 0x71, 0x77, 0x27,
	0xf1, 0xed, 0x9c, 0x17, 0xd0, 0x09, 0xfc, 0xf0, 0x29, 0xe3, 0x4f, 0x0a, 0xc6, 0x26, 0x69, 0xb4,
	0x62, 0x85, 0x5e, 0x3d, 0xcb, 0xac, 0x9e, 0x56, 0x71, 0xfb, 0x5a, 0x0f, 0x07, 0xf9, 0x32, 0xe3,
	0x2a, 0xb3, 0x52, 0x40, 0xad, 0xf6, 0x85, 0x96, 0x82, 0xf7, 0x8b, 0x05, 0x9d, 0xd0, 0x0f, 0xcc,
	0xa0, 0xff, 0x23, 0xcb, 0x8f, 0xe1, 0x96, 0xc8, 0xd4, 0x28, 0xfb, 0x31, 0x2f, 0xbb, 0x36, 0xce,
	0x8f, 0xdd, 0xe9, 0xac, 0xdc, 0xbd, 0x3f, 0x2c, 0x68, 0x87, 0x7e, 0x80, 0xf0, 0x43, 0x86, 0x75,
	0x16, 0xd7, 0xb0, 0x3c, 0x4f, 0xd6, 0x5f, 0x02, 0x29, 0xe0, 0x57, 0x05, 0x11, 0x56, 0xa5, 0x5c,
	0xcb, 0xa4, 0x07, 0xae, 0x98, 0x50, 0xa5, 0x7a, 0xb9, 0x10, 0xe3, 0x5a, 0xa1, 0x85, 0x4a, 0x07,
	0xf2, 0x0d, 0xdc, 0x9a, 0xbc, 0x56, 0x54, 0x31, 0x19, 0x4d, 0xff, 0x9e, 0x39, 0x5f, 0xd7, 0x56,
	0x5a, 0x39, 0xea, 0xe9, 0x76, 0x8d, 0x74, 0x7b, 0xdf, 0xa9, 0xc8, 0xff, 0x6a, 0xf2, 0x74, 0xc0,
	0x79, 0xbe, 0x9c, 0xab, 0xca, 0x88, 0xa5, 0xf7, 0xb3, 0x06, 0x87, 0xdc, 0x83, 0xfa, 0x49, 0x34,
	0x8f, 0x2e, 0xe5, 0x21, 0x0e, 0x55, 0x12, 0xe9, 0xc1, 0xed, 0xf3, 0x84, 0xcf, 0x42, 0x1e, 0x65,
	0xb1, 0x72, 0x90, 0x09, 0xd8, 0x56, 0x0b, 0x10, 0xa7, 0x2c, 0x4a, 0x31, 0x82, 0x43, 0x71, 0x2d,
	0xb0, 0x8b, 0xf1, 0x23, 0x02, 0xab, 0xe1, 0xa0, 0xc4, 0x87, 0xbf, 0x5a, 0xd0, 0x36, 0x67, 0x0e,
	0x69, 0x41, 0x03, 0x35, 0x17, 0xe3, 0xab, 0xce, 0x47, 0xe4, 0x0e, 0x7c, 0x2c, 0xa5, 0xb3, 0x3c,
	0x66, 0xc3, 0xa2, 0xe8, 0x58, 0x64, 0x1f, 0x3a, 0x52, 0xf5, 0x3c, 0xc7, 0x14, 0x08, 0xad, 0x4d,
	0xee, 0xc3, 0xdd, 0xb5, 0xf6, 0x2c, 0xe2, 0xd3, 0xd9, 0xc6, 0xe4, 0x54, 0x1b, 0x26, 0x03, 0x3a,
	0x38, 0xc3, 0x65, 0xa7, 0x46, 0xee, 0xc2, 0x1d, 0xa9, 0x1d, 0x3c, 0x9b, 0x0c, 0xc2, 0x50, 0xaa,
	0xdd, 0xe3, 0xf6, 0x0f, 0xad, 0x23, 0x7c, 0xe9, 0x5e, 0xe0, 0x83, 0xf8, 0x55, 0x1d, 0x85, 0xaf,
	0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x00, 0x6b, 0x35, 0x20, 0x0b, 0x00, 0x00,
}
