// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hero.proto

package proto_hero

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//英雄
type C2SInitHero struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitHero) Reset()         { *m = C2SInitHero{} }
func (m *C2SInitHero) String() string { return proto.CompactTextString(m) }
func (*C2SInitHero) ProtoMessage()    {}
func (*C2SInitHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{0}
}

func (m *C2SInitHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitHero.Unmarshal(m, b)
}
func (m *C2SInitHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitHero.Marshal(b, m, deterministic)
}
func (m *C2SInitHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitHero.Merge(m, src)
}
func (m *C2SInitHero) XXX_Size() int {
	return xxx_messageInfo_C2SInitHero.Size(m)
}
func (m *C2SInitHero) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitHero.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitHero proto.InternalMessageInfo

type S2CInitHero struct {
	Heros                map[int32]*HeroOption `protobuf:"bytes,1,rep,name=heros,proto3" json:"heros,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2CInitHero) Reset()         { *m = S2CInitHero{} }
func (m *S2CInitHero) String() string { return proto.CompactTextString(m) }
func (*S2CInitHero) ProtoMessage()    {}
func (*S2CInitHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{1}
}

func (m *S2CInitHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitHero.Unmarshal(m, b)
}
func (m *S2CInitHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitHero.Marshal(b, m, deterministic)
}
func (m *S2CInitHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitHero.Merge(m, src)
}
func (m *S2CInitHero) XXX_Size() int {
	return xxx_messageInfo_S2CInitHero.Size(m)
}
func (m *S2CInitHero) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitHero.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitHero proto.InternalMessageInfo

func (m *S2CInitHero) GetHeros() map[int32]*HeroOption {
	if m != nil {
		return m.Heros
	}
	return nil
}

//皮肤
type C2SInitSkin struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitSkin) Reset()         { *m = C2SInitSkin{} }
func (m *C2SInitSkin) String() string { return proto.CompactTextString(m) }
func (*C2SInitSkin) ProtoMessage()    {}
func (*C2SInitSkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{2}
}

func (m *C2SInitSkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitSkin.Unmarshal(m, b)
}
func (m *C2SInitSkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitSkin.Marshal(b, m, deterministic)
}
func (m *C2SInitSkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitSkin.Merge(m, src)
}
func (m *C2SInitSkin) XXX_Size() int {
	return xxx_messageInfo_C2SInitSkin.Size(m)
}
func (m *C2SInitSkin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitSkin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitSkin proto.InternalMessageInfo

type S2CInitSkin struct {
	Skins                map[int32]*SkinOption `protobuf:"bytes,1,rep,name=skins,proto3" json:"skins,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2CInitSkin) Reset()         { *m = S2CInitSkin{} }
func (m *S2CInitSkin) String() string { return proto.CompactTextString(m) }
func (*S2CInitSkin) ProtoMessage()    {}
func (*S2CInitSkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{3}
}

func (m *S2CInitSkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitSkin.Unmarshal(m, b)
}
func (m *S2CInitSkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitSkin.Marshal(b, m, deterministic)
}
func (m *S2CInitSkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitSkin.Merge(m, src)
}
func (m *S2CInitSkin) XXX_Size() int {
	return xxx_messageInfo_S2CInitSkin.Size(m)
}
func (m *S2CInitSkin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitSkin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitSkin proto.InternalMessageInfo

func (m *S2CInitSkin) GetSkins() map[int32]*SkinOption {
	if m != nil {
		return m.Skins
	}
	return nil
}

type HeroOption struct {
	Id                   int32           `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Star                 int32           `protobuf:"varint,2,opt,name=Star,proto3" json:"Star,omitempty"`
	Level                int32           `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Exp                  int32           `protobuf:"varint,4,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Stage                int32           `protobuf:"varint,5,opt,name=Stage,proto3" json:"Stage,omitempty"`
	Skin                 string          `protobuf:"bytes,6,opt,name=Skin,proto3" json:"Skin,omitempty"`
	Cultivation          map[int32]int32 `protobuf:"bytes,7,rep,name=Cultivation,proto3" json:"Cultivation,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HeroOption) Reset()         { *m = HeroOption{} }
func (m *HeroOption) String() string { return proto.CompactTextString(m) }
func (*HeroOption) ProtoMessage()    {}
func (*HeroOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{4}
}

func (m *HeroOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeroOption.Unmarshal(m, b)
}
func (m *HeroOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeroOption.Marshal(b, m, deterministic)
}
func (m *HeroOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeroOption.Merge(m, src)
}
func (m *HeroOption) XXX_Size() int {
	return xxx_messageInfo_HeroOption.Size(m)
}
func (m *HeroOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HeroOption.DiscardUnknown(m)
}

var xxx_messageInfo_HeroOption proto.InternalMessageInfo

func (m *HeroOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HeroOption) GetStar() int32 {
	if m != nil {
		return m.Star
	}
	return 0
}

func (m *HeroOption) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *HeroOption) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *HeroOption) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *HeroOption) GetSkin() string {
	if m != nil {
		return m.Skin
	}
	return ""
}

func (m *HeroOption) GetCultivation() map[int32]int32 {
	if m != nil {
		return m.Cultivation
	}
	return nil
}

type SkinOption struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SrcId                int32    `protobuf:"varint,2,opt,name=SrcId,proto3" json:"SrcId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkinOption) Reset()         { *m = SkinOption{} }
func (m *SkinOption) String() string { return proto.CompactTextString(m) }
func (*SkinOption) ProtoMessage()    {}
func (*SkinOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{5}
}

func (m *SkinOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkinOption.Unmarshal(m, b)
}
func (m *SkinOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkinOption.Marshal(b, m, deterministic)
}
func (m *SkinOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkinOption.Merge(m, src)
}
func (m *SkinOption) XXX_Size() int {
	return xxx_messageInfo_SkinOption.Size(m)
}
func (m *SkinOption) XXX_DiscardUnknown() {
	xxx_messageInfo_SkinOption.DiscardUnknown(m)
}

var xxx_messageInfo_SkinOption proto.InternalMessageInfo

func (m *SkinOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SkinOption) GetSrcId() int32 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

// 英雄变化推送
type PushHeroChange struct {
	HeroOption           *HeroOption `protobuf:"bytes,1,opt,name=HeroOption,proto3" json:"HeroOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushHeroChange) Reset()         { *m = PushHeroChange{} }
func (m *PushHeroChange) String() string { return proto.CompactTextString(m) }
func (*PushHeroChange) ProtoMessage()    {}
func (*PushHeroChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{6}
}

func (m *PushHeroChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushHeroChange.Unmarshal(m, b)
}
func (m *PushHeroChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushHeroChange.Marshal(b, m, deterministic)
}
func (m *PushHeroChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushHeroChange.Merge(m, src)
}
func (m *PushHeroChange) XXX_Size() int {
	return xxx_messageInfo_PushHeroChange.Size(m)
}
func (m *PushHeroChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushHeroChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushHeroChange proto.InternalMessageInfo

func (m *PushHeroChange) GetHeroOption() *HeroOption {
	if m != nil {
		return m.HeroOption
	}
	return nil
}

// 皮肤变化推送
type PushSkinChange struct {
	SkinOption           *SkinOption `protobuf:"bytes,1,opt,name=SkinOption,proto3" json:"SkinOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushSkinChange) Reset()         { *m = PushSkinChange{} }
func (m *PushSkinChange) String() string { return proto.CompactTextString(m) }
func (*PushSkinChange) ProtoMessage()    {}
func (*PushSkinChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{7}
}

func (m *PushSkinChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushSkinChange.Unmarshal(m, b)
}
func (m *PushSkinChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushSkinChange.Marshal(b, m, deterministic)
}
func (m *PushSkinChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushSkinChange.Merge(m, src)
}
func (m *PushSkinChange) XXX_Size() int {
	return xxx_messageInfo_PushSkinChange.Size(m)
}
func (m *PushSkinChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushSkinChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushSkinChange proto.InternalMessageInfo

func (m *PushSkinChange) GetSkinOption() *SkinOption {
	if m != nil {
		return m.SkinOption
	}
	return nil
}

//升级, 满100级就可以突破
type C2SHeroUpLevel struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeroUpLevel) Reset()         { *m = C2SHeroUpLevel{} }
func (m *C2SHeroUpLevel) String() string { return proto.CompactTextString(m) }
func (*C2SHeroUpLevel) ProtoMessage()    {}
func (*C2SHeroUpLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{8}
}

func (m *C2SHeroUpLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeroUpLevel.Unmarshal(m, b)
}
func (m *C2SHeroUpLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeroUpLevel.Marshal(b, m, deterministic)
}
func (m *C2SHeroUpLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeroUpLevel.Merge(m, src)
}
func (m *C2SHeroUpLevel) XXX_Size() int {
	return xxx_messageInfo_C2SHeroUpLevel.Size(m)
}
func (m *C2SHeroUpLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeroUpLevel.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeroUpLevel proto.InternalMessageInfo

func (m *C2SHeroUpLevel) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SHeroUpLevel) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *C2SHeroUpLevel) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

type S2CHeroUpLevel struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CHeroUpLevel) Reset()         { *m = S2CHeroUpLevel{} }
func (m *S2CHeroUpLevel) String() string { return proto.CompactTextString(m) }
func (*S2CHeroUpLevel) ProtoMessage()    {}
func (*S2CHeroUpLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{9}
}

func (m *S2CHeroUpLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeroUpLevel.Unmarshal(m, b)
}
func (m *S2CHeroUpLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeroUpLevel.Marshal(b, m, deterministic)
}
func (m *S2CHeroUpLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeroUpLevel.Merge(m, src)
}
func (m *S2CHeroUpLevel) XXX_Size() int {
	return xxx_messageInfo_S2CHeroUpLevel.Size(m)
}
func (m *S2CHeroUpLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeroUpLevel.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeroUpLevel proto.InternalMessageInfo

func (m *S2CHeroUpLevel) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

//升级修为
type C2SHeroUpCultivation struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeroUpCultivation) Reset()         { *m = C2SHeroUpCultivation{} }
func (m *C2SHeroUpCultivation) String() string { return proto.CompactTextString(m) }
func (*C2SHeroUpCultivation) ProtoMessage()    {}
func (*C2SHeroUpCultivation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{10}
}

func (m *C2SHeroUpCultivation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeroUpCultivation.Unmarshal(m, b)
}
func (m *C2SHeroUpCultivation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeroUpCultivation.Marshal(b, m, deterministic)
}
func (m *C2SHeroUpCultivation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeroUpCultivation.Merge(m, src)
}
func (m *C2SHeroUpCultivation) XXX_Size() int {
	return xxx_messageInfo_C2SHeroUpCultivation.Size(m)
}
func (m *C2SHeroUpCultivation) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeroUpCultivation.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeroUpCultivation proto.InternalMessageInfo

func (m *C2SHeroUpCultivation) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *C2SHeroUpCultivation) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type S2CHeroUpCultivation struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CHeroUpCultivation) Reset()         { *m = S2CHeroUpCultivation{} }
func (m *S2CHeroUpCultivation) String() string { return proto.CompactTextString(m) }
func (*S2CHeroUpCultivation) ProtoMessage()    {}
func (*S2CHeroUpCultivation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{11}
}

func (m *S2CHeroUpCultivation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeroUpCultivation.Unmarshal(m, b)
}
func (m *S2CHeroUpCultivation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeroUpCultivation.Marshal(b, m, deterministic)
}
func (m *S2CHeroUpCultivation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeroUpCultivation.Merge(m, src)
}
func (m *S2CHeroUpCultivation) XXX_Size() int {
	return xxx_messageInfo_S2CHeroUpCultivation.Size(m)
}
func (m *S2CHeroUpCultivation) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeroUpCultivation.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeroUpCultivation proto.InternalMessageInfo

func (m *S2CHeroUpCultivation) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

//升星
type C2SHeroUpStar struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeroUpStar) Reset()         { *m = C2SHeroUpStar{} }
func (m *C2SHeroUpStar) String() string { return proto.CompactTextString(m) }
func (*C2SHeroUpStar) ProtoMessage()    {}
func (*C2SHeroUpStar) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{12}
}

func (m *C2SHeroUpStar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeroUpStar.Unmarshal(m, b)
}
func (m *C2SHeroUpStar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeroUpStar.Marshal(b, m, deterministic)
}
func (m *C2SHeroUpStar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeroUpStar.Merge(m, src)
}
func (m *C2SHeroUpStar) XXX_Size() int {
	return xxx_messageInfo_C2SHeroUpStar.Size(m)
}
func (m *C2SHeroUpStar) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeroUpStar.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeroUpStar proto.InternalMessageInfo

func (m *C2SHeroUpStar) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CHeroUpStar struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CHeroUpStar) Reset()         { *m = S2CHeroUpStar{} }
func (m *S2CHeroUpStar) String() string { return proto.CompactTextString(m) }
func (*S2CHeroUpStar) ProtoMessage()    {}
func (*S2CHeroUpStar) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{13}
}

func (m *S2CHeroUpStar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeroUpStar.Unmarshal(m, b)
}
func (m *S2CHeroUpStar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeroUpStar.Marshal(b, m, deterministic)
}
func (m *S2CHeroUpStar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeroUpStar.Merge(m, src)
}
func (m *S2CHeroUpStar) XXX_Size() int {
	return xxx_messageInfo_S2CHeroUpStar.Size(m)
}
func (m *S2CHeroUpStar) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeroUpStar.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeroUpStar proto.InternalMessageInfo

func (m *S2CHeroUpStar) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

//升阶
type C2SHeroUpStage struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SHeroUpStage) Reset()         { *m = C2SHeroUpStage{} }
func (m *C2SHeroUpStage) String() string { return proto.CompactTextString(m) }
func (*C2SHeroUpStage) ProtoMessage()    {}
func (*C2SHeroUpStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{14}
}

func (m *C2SHeroUpStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SHeroUpStage.Unmarshal(m, b)
}
func (m *C2SHeroUpStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SHeroUpStage.Marshal(b, m, deterministic)
}
func (m *C2SHeroUpStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SHeroUpStage.Merge(m, src)
}
func (m *C2SHeroUpStage) XXX_Size() int {
	return xxx_messageInfo_C2SHeroUpStage.Size(m)
}
func (m *C2SHeroUpStage) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SHeroUpStage.DiscardUnknown(m)
}

var xxx_messageInfo_C2SHeroUpStage proto.InternalMessageInfo

func (m *C2SHeroUpStage) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CHeroUpStage struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CHeroUpStage) Reset()         { *m = S2CHeroUpStage{} }
func (m *S2CHeroUpStage) String() string { return proto.CompactTextString(m) }
func (*S2CHeroUpStage) ProtoMessage()    {}
func (*S2CHeroUpStage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{15}
}

func (m *S2CHeroUpStage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CHeroUpStage.Unmarshal(m, b)
}
func (m *S2CHeroUpStage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CHeroUpStage.Marshal(b, m, deterministic)
}
func (m *S2CHeroUpStage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CHeroUpStage.Merge(m, src)
}
func (m *S2CHeroUpStage) XXX_Size() int {
	return xxx_messageInfo_S2CHeroUpStage.Size(m)
}
func (m *S2CHeroUpStage) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CHeroUpStage.DiscardUnknown(m)
}

var xxx_messageInfo_S2CHeroUpStage proto.InternalMessageInfo

func (m *S2CHeroUpStage) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

//设置皮肤
type C2SSetHeroSkin struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Skin                 string   `protobuf:"bytes,2,opt,name=Skin,proto3" json:"Skin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SSetHeroSkin) Reset()         { *m = C2SSetHeroSkin{} }
func (m *C2SSetHeroSkin) String() string { return proto.CompactTextString(m) }
func (*C2SSetHeroSkin) ProtoMessage()    {}
func (*C2SSetHeroSkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{16}
}

func (m *C2SSetHeroSkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SSetHeroSkin.Unmarshal(m, b)
}
func (m *C2SSetHeroSkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SSetHeroSkin.Marshal(b, m, deterministic)
}
func (m *C2SSetHeroSkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SSetHeroSkin.Merge(m, src)
}
func (m *C2SSetHeroSkin) XXX_Size() int {
	return xxx_messageInfo_C2SSetHeroSkin.Size(m)
}
func (m *C2SSetHeroSkin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SSetHeroSkin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SSetHeroSkin proto.InternalMessageInfo

func (m *C2SSetHeroSkin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SSetHeroSkin) GetSkin() string {
	if m != nil {
		return m.Skin
	}
	return ""
}

//重生
type C2SReSetHero struct {
	Id                   []int32  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SReSetHero) Reset()         { *m = C2SReSetHero{} }
func (m *C2SReSetHero) String() string { return proto.CompactTextString(m) }
func (*C2SReSetHero) ProtoMessage()    {}
func (*C2SReSetHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{17}
}

func (m *C2SReSetHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SReSetHero.Unmarshal(m, b)
}
func (m *C2SReSetHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SReSetHero.Marshal(b, m, deterministic)
}
func (m *C2SReSetHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SReSetHero.Merge(m, src)
}
func (m *C2SReSetHero) XXX_Size() int {
	return xxx_messageInfo_C2SReSetHero.Size(m)
}
func (m *C2SReSetHero) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SReSetHero.DiscardUnknown(m)
}

var xxx_messageInfo_C2SReSetHero proto.InternalMessageInfo

func (m *C2SReSetHero) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type S2CReSetHero struct {
	Heros                map[int32]*HeroOption `protobuf:"bytes,1,rep,name=heros,proto3" json:"heros,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *S2CReSetHero) Reset()         { *m = S2CReSetHero{} }
func (m *S2CReSetHero) String() string { return proto.CompactTextString(m) }
func (*S2CReSetHero) ProtoMessage()    {}
func (*S2CReSetHero) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5c1be3f86b99613, []int{18}
}

func (m *S2CReSetHero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CReSetHero.Unmarshal(m, b)
}
func (m *S2CReSetHero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CReSetHero.Marshal(b, m, deterministic)
}
func (m *S2CReSetHero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CReSetHero.Merge(m, src)
}
func (m *S2CReSetHero) XXX_Size() int {
	return xxx_messageInfo_S2CReSetHero.Size(m)
}
func (m *S2CReSetHero) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CReSetHero.DiscardUnknown(m)
}

var xxx_messageInfo_S2CReSetHero proto.InternalMessageInfo

func (m *S2CReSetHero) GetHeros() map[int32]*HeroOption {
	if m != nil {
		return m.Heros
	}
	return nil
}

func init() {
	proto.RegisterType((*C2SInitHero)(nil), "Proto.Hero.C2SInitHero")
	proto.RegisterType((*S2CInitHero)(nil), "Proto.Hero.S2CInitHero")
	proto.RegisterMapType((map[int32]*HeroOption)(nil), "Proto.Hero.S2CInitHero.HerosEntry")
	proto.RegisterType((*C2SInitSkin)(nil), "Proto.Hero.C2SInitSkin")
	proto.RegisterType((*S2CInitSkin)(nil), "Proto.Hero.S2CInitSkin")
	proto.RegisterMapType((map[int32]*SkinOption)(nil), "Proto.Hero.S2CInitSkin.SkinsEntry")
	proto.RegisterType((*HeroOption)(nil), "Proto.Hero.HeroOption")
	proto.RegisterMapType((map[int32]int32)(nil), "Proto.Hero.HeroOption.CultivationEntry")
	proto.RegisterType((*SkinOption)(nil), "Proto.Hero.SkinOption")
	proto.RegisterType((*PushHeroChange)(nil), "Proto.Hero.PushHeroChange")
	proto.RegisterType((*PushSkinChange)(nil), "Proto.Hero.PushSkinChange")
	proto.RegisterType((*C2SHeroUpLevel)(nil), "Proto.Hero.C2SHeroUpLevel")
	proto.RegisterType((*S2CHeroUpLevel)(nil), "Proto.Hero.S2CHeroUpLevel")
	proto.RegisterType((*C2SHeroUpCultivation)(nil), "Proto.Hero.C2SHeroUpCultivation")
	proto.RegisterType((*S2CHeroUpCultivation)(nil), "Proto.Hero.S2CHeroUpCultivation")
	proto.RegisterType((*C2SHeroUpStar)(nil), "Proto.Hero.C2SHeroUpStar")
	proto.RegisterType((*S2CHeroUpStar)(nil), "Proto.Hero.S2CHeroUpStar")
	proto.RegisterType((*C2SHeroUpStage)(nil), "Proto.Hero.C2SHeroUpStage")
	proto.RegisterType((*S2CHeroUpStage)(nil), "Proto.Hero.S2CHeroUpStage")
	proto.RegisterType((*C2SSetHeroSkin)(nil), "Proto.Hero.C2SSetHeroSkin")
	proto.RegisterType((*C2SReSetHero)(nil), "Proto.Hero.C2SReSetHero")
	proto.RegisterType((*S2CReSetHero)(nil), "Proto.Hero.S2CReSetHero")
	proto.RegisterMapType((map[int32]*HeroOption)(nil), "Proto.Hero.S2CReSetHero.HerosEntry")
}

func init() {
	proto.RegisterFile("hero.proto", fileDescriptor_d5c1be3f86b99613)
}

var fileDescriptor_d5c1be3f86b99613 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0x26, 0xe9, 0x66, 0xc5, 0x97, 0xb6, 0x2c, 0xa1, 0x48, 0x28, 0xa8, 0x65, 0x3c, 0xd8, 0x83,
	0x44, 0x1c, 0x45, 0x56, 0x0f, 0x22, 0x3b, 0x14, 0x36, 0x22, 0x58, 0x32, 0x7a, 0xf1, 0x22, 0xdd,
	0x76, 0xd8, 0x86, 0x76, 0x33, 0x21, 0x4d, 0xcb, 0xf6, 0x47, 0xf8, 0x03, 0xc4, 0x3f, 0x2b, 0xef,
	0x4d, 0x9b, 0x8c, 0x35, 0x2b, 0xd8, 0x83, 0x97, 0x74, 0xde, 0xcc, 0xf7, 0xbe, 0xf7, 0xcd, 0xf7,
	0x66, 0xa6, 0x00, 0x73, 0x55, 0xe8, 0x28, 0x2f, 0x74, 0xa9, 0x03, 0x18, 0xe3, 0x4f, 0x74, 0xa9,
	0x0a, 0xdd, 0x6f, 0xe7, 0xeb, 0xab, 0x65, 0x3a, 0x35, 0x2b, 0xac, 0x03, 0xbe, 0xe0, 0x32, 0xce,
	0xd2, 0x12, 0x17, 0xd9, 0x0f, 0x07, 0x7c, 0xc9, 0xc5, 0x3e, 0x0e, 0xce, 0xc1, 0x43, 0x9a, 0x55,
	0xe8, 0x0c, 0x5a, 0x43, 0x9f, 0xb3, 0xa8, 0x26, 0x8a, 0x2c, 0x1c, 0x4d, 0xac, 0x46, 0x59, 0x59,
	0x6c, 0x13, 0x93, 0xd0, 0x1f, 0x03, 0xd4, 0x93, 0xc1, 0x19, 0xb4, 0x16, 0x6a, 0x1b, 0x3a, 0x03,
	0x67, 0xe8, 0x25, 0x38, 0x0c, 0x9e, 0x81, 0xb7, 0x99, 0x2c, 0xd7, 0x2a, 0x74, 0x07, 0xce, 0xd0,
	0xe7, 0x0f, 0x6c, 0x66, 0xfc, 0x7c, 0xca, 0xcb, 0x54, 0x67, 0x89, 0x01, 0xbd, 0x75, 0xcf, 0x1d,
	0x4b, 0xaa, 0x5c, 0xa4, 0x99, 0x2d, 0x15, 0x63, 0x94, 0xba, 0x5a, 0xa4, 0xd9, 0xdf, 0xa4, 0x22,
	0x2e, 0xc2, 0xcf, 0x5e, 0x2a, 0x25, 0xa0, 0xd4, 0x7a, 0xf2, 0x1f, 0xa5, 0x62, 0xe2, 0x9f, 0x52,
	0xbf, 0xbb, 0x66, 0xf7, 0x66, 0x25, 0xe8, 0x82, 0x1b, 0xcf, 0x76, 0x8c, 0x6e, 0x3c, 0x0b, 0x02,
	0x38, 0x91, 0xe5, 0xa4, 0x20, 0x3e, 0x2f, 0xa1, 0x71, 0xd0, 0x03, 0xef, 0xa3, 0xda, 0xa8, 0x65,
	0xd8, 0xa2, 0x49, 0x13, 0xa0, 0x98, 0xd1, 0x6d, 0x1e, 0x9e, 0x18, 0x31, 0xa3, 0xdb, 0x1c, 0x71,
	0xb2, 0x9c, 0x5c, 0xab, 0xd0, 0x33, 0x38, 0x0a, 0x88, 0x71, 0x91, 0x66, 0xe1, 0xe9, 0xc0, 0x19,
	0xde, 0x4f, 0x68, 0x1c, 0xc4, 0xe0, 0x8b, 0xf5, 0xb2, 0x4c, 0x37, 0x13, 0x14, 0x11, 0xde, 0x23,
	0x5b, 0x9e, 0x36, 0xfb, 0x1c, 0x59, 0x48, 0xe3, 0x8d, 0x9d, 0xdb, 0x7f, 0x07, 0x67, 0x87, 0x80,
	0x06, 0x9f, 0x7a, 0xb6, 0x4f, 0x9e, 0xed, 0x07, 0x37, 0x0e, 0xdf, 0x61, 0x07, 0x6e, 0xa9, 0x98,
	0xc6, 0xb3, 0x7d, 0x1e, 0x05, 0xec, 0x12, 0xba, 0xe3, 0xf5, 0x6a, 0x8e, 0x1a, 0xc5, 0x7c, 0x92,
	0x5d, 0xab, 0xe0, 0xb5, 0x6d, 0x2a, 0xe5, 0xdf, 0x7d, 0x6e, 0x2c, 0xe4, 0x9e, 0x09, 0x15, 0xd4,
	0x4c, 0xb5, 0x9e, 0x26, 0x26, 0xab, 0xad, 0x16, 0x92, 0x7d, 0x80, 0xae, 0xe0, 0x12, 0x11, 0x5f,
	0x72, 0xd3, 0xa0, 0x86, 0xbd, 0x08, 0xbd, 0xce, 0xca, 0xfd, 0x5e, 0x28, 0xc0, 0xf6, 0x7c, 0xde,
	0xe6, 0x6a, 0xd7, 0x5b, 0x1a, 0x33, 0x01, 0x5d, 0xc9, 0x85, 0xcd, 0xf5, 0x02, 0x4e, 0xa6, 0x7a,
	0xa6, 0x88, 0xad, 0xcb, 0x1f, 0xee, 0xf4, 0x8c, 0xcd, 0x75, 0x15, 0xfa, 0xe6, 0x46, 0x67, 0xa3,
	0xa2, 0xd0, 0x85, 0xd0, 0x33, 0x95, 0x10, 0x94, 0xbd, 0x87, 0x5e, 0x25, 0xc8, 0xea, 0x50, 0x55,
	0xd0, 0xa9, 0x0b, 0x36, 0x4b, 0x63, 0x31, 0xf4, 0x2a, 0x19, 0x36, 0xc3, 0x11, 0x62, 0x1e, 0x43,
	0xa7, 0x12, 0x43, 0x67, 0xfa, 0xc0, 0x1c, 0x76, 0x01, 0x9d, 0xaa, 0x16, 0x01, 0x8e, 0x28, 0x32,
	0xb0, 0x5a, 0x60, 0xce, 0xfe, 0x61, 0x15, 0xdb, 0x58, 0x83, 0x38, 0xa2, 0xcc, 0x2b, 0x2a, 0x23,
	0x15, 0x3d, 0x6f, 0x74, 0x9d, 0x9a, 0x2e, 0x31, 0x5e, 0x39, 0xb7, 0xbe, 0x72, 0xec, 0x11, 0xb4,
	0x05, 0x97, 0x89, 0xda, 0xe5, 0x55, 0x39, 0xad, 0x9d, 0xb4, 0x9f, 0x0e, 0xb4, 0x25, 0x17, 0x35,
	0xe0, 0xcd, 0xef, 0xef, 0xeb, 0x93, 0x83, 0x47, 0xab, 0x02, 0xfe, 0x8f, 0x07, 0xf6, 0xa2, 0xf3,
	0xd5, 0x7f, 0x4e, 0xff, 0x0a, 0xdf, 0xb0, 0xc2, 0xd5, 0x29, 0x8d, 0x5f, 0xfe, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0xab, 0x6a, 0xfd, 0xbe, 0x49, 0x06, 0x00, 0x00,
}
