// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fashion.proto

package proto_fashion

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//-----------------------------------时装--------------------------
//初始时装
type C2SInitFashion struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitFashion) Reset()         { *m = C2SInitFashion{} }
func (m *C2SInitFashion) String() string { return proto.CompactTextString(m) }
func (*C2SInitFashion) ProtoMessage()    {}
func (*C2SInitFashion) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{0}
}

func (m *C2SInitFashion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitFashion.Unmarshal(m, b)
}
func (m *C2SInitFashion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitFashion.Marshal(b, m, deterministic)
}
func (m *C2SInitFashion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitFashion.Merge(m, src)
}
func (m *C2SInitFashion) XXX_Size() int {
	return xxx_messageInfo_C2SInitFashion.Size(m)
}
func (m *C2SInitFashion) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitFashion.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitFashion proto.InternalMessageInfo

type S2CInitFashion struct {
	Fashions             map[int32]*FashionOption `protobuf:"bytes,1,rep,name=fashions,proto3" json:"fashions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HandbookExp          int32                    `protobuf:"varint,2,opt,name=HandbookExp,proto3" json:"HandbookExp,omitempty"`
	HandbookIds          []int32                  `protobuf:"varint,3,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *S2CInitFashion) Reset()         { *m = S2CInitFashion{} }
func (m *S2CInitFashion) String() string { return proto.CompactTextString(m) }
func (*S2CInitFashion) ProtoMessage()    {}
func (*S2CInitFashion) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{1}
}

func (m *S2CInitFashion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitFashion.Unmarshal(m, b)
}
func (m *S2CInitFashion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitFashion.Marshal(b, m, deterministic)
}
func (m *S2CInitFashion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitFashion.Merge(m, src)
}
func (m *S2CInitFashion) XXX_Size() int {
	return xxx_messageInfo_S2CInitFashion.Size(m)
}
func (m *S2CInitFashion) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitFashion.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitFashion proto.InternalMessageInfo

func (m *S2CInitFashion) GetFashions() map[int32]*FashionOption {
	if m != nil {
		return m.Fashions
	}
	return nil
}

func (m *S2CInitFashion) GetHandbookExp() int32 {
	if m != nil {
		return m.HandbookExp
	}
	return 0
}

func (m *S2CInitFashion) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

type FashionOption struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	IsUse                bool     `protobuf:"varint,2,opt,name=IsUse,proto3" json:"IsUse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FashionOption) Reset()         { *m = FashionOption{} }
func (m *FashionOption) String() string { return proto.CompactTextString(m) }
func (*FashionOption) ProtoMessage()    {}
func (*FashionOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{2}
}

func (m *FashionOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FashionOption.Unmarshal(m, b)
}
func (m *FashionOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FashionOption.Marshal(b, m, deterministic)
}
func (m *FashionOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FashionOption.Merge(m, src)
}
func (m *FashionOption) XXX_Size() int {
	return xxx_messageInfo_FashionOption.Size(m)
}
func (m *FashionOption) XXX_DiscardUnknown() {
	xxx_messageInfo_FashionOption.DiscardUnknown(m)
}

var xxx_messageInfo_FashionOption proto.InternalMessageInfo

func (m *FashionOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FashionOption) GetIsUse() bool {
	if m != nil {
		return m.IsUse
	}
	return false
}

//使用时装
type C2SUseFashion struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Wear                 bool     `protobuf:"varint,2,opt,name=Wear,proto3" json:"Wear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUseFashion) Reset()         { *m = C2SUseFashion{} }
func (m *C2SUseFashion) String() string { return proto.CompactTextString(m) }
func (*C2SUseFashion) ProtoMessage()    {}
func (*C2SUseFashion) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{3}
}

func (m *C2SUseFashion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUseFashion.Unmarshal(m, b)
}
func (m *C2SUseFashion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUseFashion.Marshal(b, m, deterministic)
}
func (m *C2SUseFashion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUseFashion.Merge(m, src)
}
func (m *C2SUseFashion) XXX_Size() int {
	return xxx_messageInfo_C2SUseFashion.Size(m)
}
func (m *C2SUseFashion) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUseFashion.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUseFashion proto.InternalMessageInfo

func (m *C2SUseFashion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SUseFashion) GetWear() bool {
	if m != nil {
		return m.Wear
	}
	return false
}

type S2CUseFashion struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	Fashions             map[int32]*FashionOption     `protobuf:"bytes,2,rep,name=fashions,proto3" json:"fashions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CUseFashion) Reset()         { *m = S2CUseFashion{} }
func (m *S2CUseFashion) String() string { return proto.CompactTextString(m) }
func (*S2CUseFashion) ProtoMessage()    {}
func (*S2CUseFashion) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{4}
}

func (m *S2CUseFashion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUseFashion.Unmarshal(m, b)
}
func (m *S2CUseFashion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUseFashion.Marshal(b, m, deterministic)
}
func (m *S2CUseFashion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUseFashion.Merge(m, src)
}
func (m *S2CUseFashion) XXX_Size() int {
	return xxx_messageInfo_S2CUseFashion.Size(m)
}
func (m *S2CUseFashion) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUseFashion.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUseFashion proto.InternalMessageInfo

func (m *S2CUseFashion) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CUseFashion) GetFashions() map[int32]*FashionOption {
	if m != nil {
		return m.Fashions
	}
	return nil
}

//领取奖励
type C2SGetFashionHandBookAward struct {
	Id                   []int32  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetFashionHandBookAward) Reset()         { *m = C2SGetFashionHandBookAward{} }
func (m *C2SGetFashionHandBookAward) String() string { return proto.CompactTextString(m) }
func (*C2SGetFashionHandBookAward) ProtoMessage()    {}
func (*C2SGetFashionHandBookAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{5}
}

func (m *C2SGetFashionHandBookAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetFashionHandBookAward.Unmarshal(m, b)
}
func (m *C2SGetFashionHandBookAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetFashionHandBookAward.Marshal(b, m, deterministic)
}
func (m *C2SGetFashionHandBookAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetFashionHandBookAward.Merge(m, src)
}
func (m *C2SGetFashionHandBookAward) XXX_Size() int {
	return xxx_messageInfo_C2SGetFashionHandBookAward.Size(m)
}
func (m *C2SGetFashionHandBookAward) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetFashionHandBookAward.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetFashionHandBookAward proto.InternalMessageInfo

func (m *C2SGetFashionHandBookAward) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type S2CGetFashionHandBookAward struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	HandbookIds          []int32                      `protobuf:"varint,2,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CGetFashionHandBookAward) Reset()         { *m = S2CGetFashionHandBookAward{} }
func (m *S2CGetFashionHandBookAward) String() string { return proto.CompactTextString(m) }
func (*S2CGetFashionHandBookAward) ProtoMessage()    {}
func (*S2CGetFashionHandBookAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{6}
}

func (m *S2CGetFashionHandBookAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetFashionHandBookAward.Unmarshal(m, b)
}
func (m *S2CGetFashionHandBookAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetFashionHandBookAward.Marshal(b, m, deterministic)
}
func (m *S2CGetFashionHandBookAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetFashionHandBookAward.Merge(m, src)
}
func (m *S2CGetFashionHandBookAward) XXX_Size() int {
	return xxx_messageInfo_S2CGetFashionHandBookAward.Size(m)
}
func (m *S2CGetFashionHandBookAward) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetFashionHandBookAward.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetFashionHandBookAward proto.InternalMessageInfo

func (m *S2CGetFashionHandBookAward) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CGetFashionHandBookAward) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

type PushFashionChange struct {
	Fashions             map[int32]*FashionOption `protobuf:"bytes,1,rep,name=fashions,proto3" json:"fashions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HandbookExp          int32                    `protobuf:"varint,2,opt,name=HandbookExp,proto3" json:"HandbookExp,omitempty"`
	HandbookIds          []int32                  `protobuf:"varint,3,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PushFashionChange) Reset()         { *m = PushFashionChange{} }
func (m *PushFashionChange) String() string { return proto.CompactTextString(m) }
func (*PushFashionChange) ProtoMessage()    {}
func (*PushFashionChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{7}
}

func (m *PushFashionChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushFashionChange.Unmarshal(m, b)
}
func (m *PushFashionChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushFashionChange.Marshal(b, m, deterministic)
}
func (m *PushFashionChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushFashionChange.Merge(m, src)
}
func (m *PushFashionChange) XXX_Size() int {
	return xxx_messageInfo_PushFashionChange.Size(m)
}
func (m *PushFashionChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushFashionChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushFashionChange proto.InternalMessageInfo

func (m *PushFashionChange) GetFashions() map[int32]*FashionOption {
	if m != nil {
		return m.Fashions
	}
	return nil
}

func (m *PushFashionChange) GetHandbookExp() int32 {
	if m != nil {
		return m.HandbookExp
	}
	return 0
}

func (m *PushFashionChange) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

//--------------------------------------头饰-------------------------------
type C2SInitHeadWear struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitHeadWear) Reset()         { *m = C2SInitHeadWear{} }
func (m *C2SInitHeadWear) String() string { return proto.CompactTextString(m) }
func (*C2SInitHeadWear) ProtoMessage()    {}
func (*C2SInitHeadWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{8}
}

func (m *C2SInitHeadWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitHeadWear.Unmarshal(m, b)
}
func (m *C2SInitHeadWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitHeadWear.Marshal(b, m, deterministic)
}
func (m *C2SInitHeadWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitHeadWear.Merge(m, src)
}
func (m *C2SInitHeadWear) XXX_Size() int {
	return xxx_messageInfo_C2SInitHeadWear.Size(m)
}
func (m *C2SInitHeadWear) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitHeadWear.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitHeadWear proto.InternalMessageInfo

type S2CInitHeadWear struct {
	Headwear             map[int32]*HeadWearOption `protobuf:"bytes,1,rep,name=headwear,proto3" json:"headwear,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HandbookExp          int32                     `protobuf:"varint,2,opt,name=HandbookExp,proto3" json:"HandbookExp,omitempty"`
	HandbookIds          []int32                   `protobuf:"varint,3,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *S2CInitHeadWear) Reset()         { *m = S2CInitHeadWear{} }
func (m *S2CInitHeadWear) String() string { return proto.CompactTextString(m) }
func (*S2CInitHeadWear) ProtoMessage()    {}
func (*S2CInitHeadWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{9}
}

func (m *S2CInitHeadWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitHeadWear.Unmarshal(m, b)
}
func (m *S2CInitHeadWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitHeadWear.Marshal(b, m, deterministic)
}
func (m *S2CInitHeadWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitHeadWear.Merge(m, src)
}
func (m *S2CInitHeadWear) XXX_Size() int {
	return xxx_messageInfo_S2CInitHeadWear.Size(m)
}
func (m *S2CInitHeadWear) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitHeadWear.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitHeadWear proto.InternalMessageInfo

func (m *S2CInitHeadWear) GetHeadwear() map[int32]*HeadWearOption {
	if m != nil {
		return m.Headwear
	}
	return nil
}

func (m *S2CInitHeadWear) GetHandbookExp() int32 {
	if m != nil {
		return m.HandbookExp
	}
	return 0
}

func (m *S2CInitHeadWear) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

type HeadWearOption struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	IsUse                bool     `protobuf:"varint,2,opt,name=IsUse,proto3" json:"IsUse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeadWearOption) Reset()         { *m = HeadWearOption{} }
func (m *HeadWearOption) String() string { return proto.CompactTextString(m) }
func (*HeadWearOption) ProtoMessage()    {}
func (*HeadWearOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{10}
}

func (m *HeadWearOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeadWearOption.Unmarshal(m, b)
}
func (m *HeadWearOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeadWearOption.Marshal(b, m, deterministic)
}
func (m *HeadWearOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeadWearOption.Merge(m, src)
}
func (m *HeadWearOption) XXX_Size() int {
	return xxx_messageInfo_HeadWearOption.Size(m)
}
func (m *HeadWearOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HeadWearOption.DiscardUnknown(m)
}

var xxx_messageInfo_HeadWearOption proto.InternalMessageInfo

func (m *HeadWearOption) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HeadWearOption) GetIsUse() bool {
	if m != nil {
		return m.IsUse
	}
	return false
}

//使用头饰
type C2SUseHeadWear struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Wear                 bool     `protobuf:"varint,2,opt,name=Wear,proto3" json:"Wear,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUseHeadWear) Reset()         { *m = C2SUseHeadWear{} }
func (m *C2SUseHeadWear) String() string { return proto.CompactTextString(m) }
func (*C2SUseHeadWear) ProtoMessage()    {}
func (*C2SUseHeadWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{11}
}

func (m *C2SUseHeadWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUseHeadWear.Unmarshal(m, b)
}
func (m *C2SUseHeadWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUseHeadWear.Marshal(b, m, deterministic)
}
func (m *C2SUseHeadWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUseHeadWear.Merge(m, src)
}
func (m *C2SUseHeadWear) XXX_Size() int {
	return xxx_messageInfo_C2SUseHeadWear.Size(m)
}
func (m *C2SUseHeadWear) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUseHeadWear.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUseHeadWear proto.InternalMessageInfo

func (m *C2SUseHeadWear) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SUseHeadWear) GetWear() bool {
	if m != nil {
		return m.Wear
	}
	return false
}

type S2CUseHeadWear struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	Headwear             map[int32]*HeadWearOption    `protobuf:"bytes,2,rep,name=headwear,proto3" json:"headwear,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CUseHeadWear) Reset()         { *m = S2CUseHeadWear{} }
func (m *S2CUseHeadWear) String() string { return proto.CompactTextString(m) }
func (*S2CUseHeadWear) ProtoMessage()    {}
func (*S2CUseHeadWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{12}
}

func (m *S2CUseHeadWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUseHeadWear.Unmarshal(m, b)
}
func (m *S2CUseHeadWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUseHeadWear.Marshal(b, m, deterministic)
}
func (m *S2CUseHeadWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUseHeadWear.Merge(m, src)
}
func (m *S2CUseHeadWear) XXX_Size() int {
	return xxx_messageInfo_S2CUseHeadWear.Size(m)
}
func (m *S2CUseHeadWear) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUseHeadWear.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUseHeadWear proto.InternalMessageInfo

func (m *S2CUseHeadWear) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CUseHeadWear) GetHeadwear() map[int32]*HeadWearOption {
	if m != nil {
		return m.Headwear
	}
	return nil
}

//领取奖励
type C2SGetHeadWearHandBookAward struct {
	Id                   []int32  `protobuf:"varint,1,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetHeadWearHandBookAward) Reset()         { *m = C2SGetHeadWearHandBookAward{} }
func (m *C2SGetHeadWearHandBookAward) String() string { return proto.CompactTextString(m) }
func (*C2SGetHeadWearHandBookAward) ProtoMessage()    {}
func (*C2SGetHeadWearHandBookAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{13}
}

func (m *C2SGetHeadWearHandBookAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetHeadWearHandBookAward.Unmarshal(m, b)
}
func (m *C2SGetHeadWearHandBookAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetHeadWearHandBookAward.Marshal(b, m, deterministic)
}
func (m *C2SGetHeadWearHandBookAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetHeadWearHandBookAward.Merge(m, src)
}
func (m *C2SGetHeadWearHandBookAward) XXX_Size() int {
	return xxx_messageInfo_C2SGetHeadWearHandBookAward.Size(m)
}
func (m *C2SGetHeadWearHandBookAward) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetHeadWearHandBookAward.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetHeadWearHandBookAward proto.InternalMessageInfo

func (m *C2SGetHeadWearHandBookAward) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type S2CGetHeadWearHandBookAward struct {
	Code                 proto_public.CommonErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=Proto.Public.CommonErrorCode" json:"code,omitempty"`
	HandbookIds          []int32                      `protobuf:"varint,2,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *S2CGetHeadWearHandBookAward) Reset()         { *m = S2CGetHeadWearHandBookAward{} }
func (m *S2CGetHeadWearHandBookAward) String() string { return proto.CompactTextString(m) }
func (*S2CGetHeadWearHandBookAward) ProtoMessage()    {}
func (*S2CGetHeadWearHandBookAward) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{14}
}

func (m *S2CGetHeadWearHandBookAward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetHeadWearHandBookAward.Unmarshal(m, b)
}
func (m *S2CGetHeadWearHandBookAward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetHeadWearHandBookAward.Marshal(b, m, deterministic)
}
func (m *S2CGetHeadWearHandBookAward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetHeadWearHandBookAward.Merge(m, src)
}
func (m *S2CGetHeadWearHandBookAward) XXX_Size() int {
	return xxx_messageInfo_S2CGetHeadWearHandBookAward.Size(m)
}
func (m *S2CGetHeadWearHandBookAward) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetHeadWearHandBookAward.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetHeadWearHandBookAward proto.InternalMessageInfo

func (m *S2CGetHeadWearHandBookAward) GetCode() proto_public.CommonErrorCode {
	if m != nil {
		return m.Code
	}
	return proto_public.CommonErrorCode_ERR_OK
}

func (m *S2CGetHeadWearHandBookAward) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

type PushHeadWearChange struct {
	Headwear             map[int32]*HeadWearOption `protobuf:"bytes,1,rep,name=headwear,proto3" json:"headwear,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HandbookExp          int32                     `protobuf:"varint,2,opt,name=HandbookExp,proto3" json:"HandbookExp,omitempty"`
	HandbookIds          []int32                   `protobuf:"varint,3,rep,packed,name=HandbookIds,proto3" json:"HandbookIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PushHeadWearChange) Reset()         { *m = PushHeadWearChange{} }
func (m *PushHeadWearChange) String() string { return proto.CompactTextString(m) }
func (*PushHeadWearChange) ProtoMessage()    {}
func (*PushHeadWearChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_839ca7bf5c6e3e7c, []int{15}
}

func (m *PushHeadWearChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushHeadWearChange.Unmarshal(m, b)
}
func (m *PushHeadWearChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushHeadWearChange.Marshal(b, m, deterministic)
}
func (m *PushHeadWearChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushHeadWearChange.Merge(m, src)
}
func (m *PushHeadWearChange) XXX_Size() int {
	return xxx_messageInfo_PushHeadWearChange.Size(m)
}
func (m *PushHeadWearChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushHeadWearChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushHeadWearChange proto.InternalMessageInfo

func (m *PushHeadWearChange) GetHeadwear() map[int32]*HeadWearOption {
	if m != nil {
		return m.Headwear
	}
	return nil
}

func (m *PushHeadWearChange) GetHandbookExp() int32 {
	if m != nil {
		return m.HandbookExp
	}
	return 0
}

func (m *PushHeadWearChange) GetHandbookIds() []int32 {
	if m != nil {
		return m.HandbookIds
	}
	return nil
}

func init() {
	proto.RegisterType((*C2SInitFashion)(nil), "Proto.Fashion.C2SInitFashion")
	proto.RegisterType((*S2CInitFashion)(nil), "Proto.Fashion.S2CInitFashion")
	proto.RegisterMapType((map[int32]*FashionOption)(nil), "Proto.Fashion.S2CInitFashion.FashionsEntry")
	proto.RegisterType((*FashionOption)(nil), "Proto.Fashion.FashionOption")
	proto.RegisterType((*C2SUseFashion)(nil), "Proto.Fashion.C2SUseFashion")
	proto.RegisterType((*S2CUseFashion)(nil), "Proto.Fashion.S2CUseFashion")
	proto.RegisterMapType((map[int32]*FashionOption)(nil), "Proto.Fashion.S2CUseFashion.FashionsEntry")
	proto.RegisterType((*C2SGetFashionHandBookAward)(nil), "Proto.Fashion.C2SGetFashionHandBookAward")
	proto.RegisterType((*S2CGetFashionHandBookAward)(nil), "Proto.Fashion.S2CGetFashionHandBookAward")
	proto.RegisterType((*PushFashionChange)(nil), "Proto.Fashion.PushFashionChange")
	proto.RegisterMapType((map[int32]*FashionOption)(nil), "Proto.Fashion.PushFashionChange.FashionsEntry")
	proto.RegisterType((*C2SInitHeadWear)(nil), "Proto.Fashion.C2SInitHeadWear")
	proto.RegisterType((*S2CInitHeadWear)(nil), "Proto.Fashion.S2CInitHeadWear")
	proto.RegisterMapType((map[int32]*HeadWearOption)(nil), "Proto.Fashion.S2CInitHeadWear.HeadwearEntry")
	proto.RegisterType((*HeadWearOption)(nil), "Proto.Fashion.HeadWearOption")
	proto.RegisterType((*C2SUseHeadWear)(nil), "Proto.Fashion.C2SUseHeadWear")
	proto.RegisterType((*S2CUseHeadWear)(nil), "Proto.Fashion.S2CUseHeadWear")
	proto.RegisterMapType((map[int32]*HeadWearOption)(nil), "Proto.Fashion.S2CUseHeadWear.HeadwearEntry")
	proto.RegisterType((*C2SGetHeadWearHandBookAward)(nil), "Proto.Fashion.C2SGetHeadWearHandBookAward")
	proto.RegisterType((*S2CGetHeadWearHandBookAward)(nil), "Proto.Fashion.S2CGetHeadWearHandBookAward")
	proto.RegisterType((*PushHeadWearChange)(nil), "Proto.Fashion.PushHeadWearChange")
	proto.RegisterMapType((map[int32]*HeadWearOption)(nil), "Proto.Fashion.PushHeadWearChange.HeadwearEntry")
}

func init() {
	proto.RegisterFile("fashion.proto", fileDescriptor_839ca7bf5c6e3e7c)
}

var fileDescriptor_839ca7bf5c6e3e7c = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x95, 0xed, 0xe6, 0x53, 0x34, 0xf9, 0xec, 0xa6, 0x2b, 0x0e, 0x51, 0x4a, 0xa5, 0xc8, 0xa7,
	0x0a, 0x8a, 0x2b, 0x36, 0x80, 0x10, 0x37, 0x6a, 0xa5, 0x89, 0xe1, 0x40, 0x64, 0x2b, 0x42, 0xf4,
	0x82, 0x9c, 0xee, 0x42, 0xa2, 0xb4, 0xde, 0xe0, 0x4d, 0x28, 0x3d, 0xf2, 0x63, 0x91, 0xf8, 0x09,
	0x48, 0x48, 0x08, 0x79, 0x77, 0x1d, 0xd6, 0x76, 0x82, 0xaa, 0x8a, 0x1c, 0x7a, 0xb2, 0x3d, 0x3b,
	0x6f, 0x66, 0xf2, 0xe6, 0xed, 0x53, 0xc0, 0xfe, 0x10, 0xf3, 0xc9, 0x94, 0x25, 0xde, 0x3c, 0x65,
	0x0b, 0x86, 0xec, 0x61, 0xf6, 0xf0, 0x4e, 0x65, 0xb0, 0xfd, 0xff, 0x7c, 0x39, 0xbe, 0x98, 0x9e,
	0xcb, 0x43, 0xb7, 0x09, 0x8e, 0x8f, 0xa3, 0x20, 0x99, 0x2e, 0xd4, 0xb9, 0xfb, 0xc3, 0x00, 0x27,
	0xc2, 0xbe, 0x16, 0x42, 0x7d, 0xa8, 0xab, 0x92, 0xbc, 0x65, 0x74, 0xac, 0xc3, 0x06, 0x7e, 0xe8,
	0x15, 0x8a, 0x7a, 0x45, 0x40, 0x1e, 0xe6, 0xbd, 0x64, 0x91, 0x5e, 0x87, 0x2b, 0x30, 0xea, 0x40,
	0x63, 0x10, 0x27, 0x64, 0xcc, 0xd8, 0xac, 0xf7, 0x65, 0xde, 0x32, 0x3b, 0xc6, 0x61, 0x2d, 0xd4,
	0x43, 0x7a, 0x46, 0x40, 0x78, 0xcb, 0xea, 0x58, 0x7a, 0x46, 0x40, 0x78, 0xfb, 0x1d, 0xd8, 0x85,
	0xf2, 0xa8, 0x09, 0xd6, 0x8c, 0x5e, 0xb7, 0x0c, 0x51, 0x2c, 0x7b, 0x45, 0x18, 0x6a, 0x9f, 0xe3,
	0x8b, 0x25, 0x15, 0x0d, 0x1a, 0xf8, 0x7e, 0x69, 0x58, 0xf5, 0x7c, 0x33, 0x5f, 0x4c, 0x59, 0x12,
	0xca, 0xd4, 0x17, 0xe6, 0x73, 0xc3, 0x7d, 0xba, 0x2a, 0x2d, 0xcf, 0x90, 0x03, 0x66, 0x40, 0x54,
	0x65, 0x33, 0x20, 0xe8, 0x1e, 0xd4, 0x02, 0x3e, 0xe2, 0xb2, 0x70, 0x3d, 0x94, 0x1f, 0x6e, 0x17,
	0x6c, 0x1f, 0x47, 0x23, 0x4e, 0x73, 0xbe, 0xca, 0x30, 0x04, 0x3b, 0x6f, 0x69, 0x9c, 0x2a, 0x94,
	0x78, 0x77, 0xbf, 0x19, 0x60, 0x47, 0xd8, 0xd7, 0x50, 0x8f, 0x61, 0xe7, 0x9c, 0x11, 0x2a, 0x70,
	0x0e, 0x3e, 0x50, 0x43, 0x0f, 0xe5, 0xb6, 0x7c, 0x76, 0x79, 0xc9, 0x92, 0x5e, 0x9a, 0xb2, 0xd4,
	0x67, 0x84, 0x86, 0x22, 0x15, 0x9d, 0x6a, 0x8b, 0x31, 0xc5, 0x62, 0x1e, 0x54, 0x17, 0xf3, 0xa7,
	0xc5, 0xa6, 0xbd, 0x6c, 0x93, 0xd3, 0x23, 0x68, 0xfb, 0x38, 0xea, 0xd3, 0x5c, 0x1b, 0xd9, 0x2a,
	0x4f, 0x18, 0x9b, 0xbd, 0xbc, 0x8a, 0x53, 0xb2, 0x62, 0xca, 0x92, 0x4c, 0xb9, 0x9f, 0xa0, 0x1d,
	0x61, 0x7f, 0x53, 0xf6, 0x2d, 0x18, 0x2a, 0xe9, 0xc9, 0xac, 0xe8, 0xc9, 0xfd, 0x65, 0xc0, 0xde,
	0x70, 0xc9, 0x27, 0xaa, 0xa3, 0x3f, 0x89, 0x93, 0x8f, 0x14, 0xbd, 0xaa, 0x48, 0xde, 0x2b, 0xfd,
	0xe2, 0x0a, 0xe6, 0xae, 0xaa, 0x7e, 0x0f, 0x76, 0x95, 0x05, 0x0c, 0x68, 0x4c, 0x84, 0x38, 0x7f,
	0x1a, 0xb0, 0xab, 0xae, 0x74, 0x1e, 0x43, 0x03, 0xa8, 0x4f, 0x68, 0x4c, 0xae, 0x32, 0x21, 0x4b,
	0x46, 0x8e, 0xd6, 0x9b, 0x40, 0x8e, 0xf0, 0x06, 0x2a, 0x5d, 0xf1, 0x91, 0xa3, 0xff, 0x09, 0x1f,
	0x67, 0x60, 0x17, 0xca, 0xaf, 0xe1, 0xa3, 0x5b, 0xe4, 0xe3, 0xa0, 0x34, 0x6d, 0x3e, 0x66, 0x95,
	0x90, 0x67, 0xe0, 0x14, 0x0f, 0x6f, 0xe8, 0x03, 0x4f, 0x84, 0x97, 0x8e, 0x38, 0x5d, 0x71, 0x76,
	0x13, 0x23, 0xf8, 0x2e, 0xfd, 0x56, 0x87, 0xdd, 0x42, 0xe7, 0x7d, 0x6d, 0x3b, 0xe6, 0x26, 0x8b,
	0xd6, 0x7a, 0x6c, 0x5a, 0xce, 0x56, 0x89, 0x7d, 0x04, 0xfb, 0xd2, 0x0b, 0xf2, 0x94, 0xbf, 0x9b,
	0x41, 0x0a, 0xfb, 0xd2, 0x0c, 0xd6, 0xa7, 0x6f, 0xc5, 0x0d, 0xbe, 0x9a, 0x80, 0xb2, 0x9b, 0x9d,
	0xb7, 0x54, 0x76, 0xf0, 0xba, 0x22, 0xfe, 0xe3, 0x35, 0x76, 0x50, 0x04, 0xdd, 0x55, 0xfd, 0x9f,
	0x34, 0xcf, 0x9c, 0x63, 0xf1, 0xef, 0xe0, 0xbd, 0xb2, 0xb0, 0xf1, 0x7f, 0xe2, 0xb3, 0xfb, 0x3b,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0xc2, 0xc3, 0xd0, 0x5a, 0x08, 0x00, 0x00,
}
