// Code generated by protoc-gen-go. DO NOT EDIT.
// source: player.proto

package proto_player

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginResult int32

const (
	LoginResult_LoginSuccess                LoginResult = 0
	LoginResult_LoginFail                   LoginResult = 1
	LoginResult_LoginDBError                LoginResult = 2
	LoginResult_LoginCreateError            LoginResult = 3
	LoginResult_LoginReplaceError           LoginResult = 4
	LoginResult_LoginAccountOrPasswordError LoginResult = 5
)

var LoginResult_name = map[int32]string{
	0: "LoginSuccess",
	1: "LoginFail",
	2: "LoginDBError",
	3: "LoginCreateError",
	4: "LoginReplaceError",
	5: "LoginAccountOrPasswordError",
}

var LoginResult_value = map[string]int32{
	"LoginSuccess":                0,
	"LoginFail":                   1,
	"LoginDBError":                2,
	"LoginCreateError":            3,
	"LoginReplaceError":           4,
	"LoginAccountOrPasswordError": 5,
}

func (x LoginResult) String() string {
	return proto.EnumName(LoginResult_name, int32(x))
}

func (LoginResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

type LOGINERRORCODE int32

const (
	LOGINERRORCODE_ERROR_OK             LOGINERRORCODE = 0
	LOGINERRORCODE_ERROR_NONAMECARD     LOGINERRORCODE = 1
	LOGINERRORCODE_ERROR_NOTITLE        LOGINERRORCODE = 2
	LOGINERRORCODE_ERROR_NOHERO         LOGINERRORCODE = 3
	LOGINERRORCODE_ERROR_SKIN           LOGINERRORCODE = 4
	LOGINERRORCODE_ERROR_SENSITIVEWORDS LOGINERRORCODE = 5
	LOGINERRORCODE_ERROR_ITEMNOENGTH    LOGINERRORCODE = 6
)

var LOGINERRORCODE_name = map[int32]string{
	0: "ERROR_OK",
	1: "ERROR_NONAMECARD",
	2: "ERROR_NOTITLE",
	3: "ERROR_NOHERO",
	4: "ERROR_SKIN",
	5: "ERROR_SENSITIVEWORDS",
	6: "ERROR_ITEMNOENGTH",
}

var LOGINERRORCODE_value = map[string]int32{
	"ERROR_OK":             0,
	"ERROR_NONAMECARD":     1,
	"ERROR_NOTITLE":        2,
	"ERROR_NOHERO":         3,
	"ERROR_SKIN":           4,
	"ERROR_SENSITIVEWORDS": 5,
	"ERROR_ITEMNOENGTH":    6,
}

func (x LOGINERRORCODE) String() string {
	return proto.EnumName(LOGINERRORCODE_name, int32(x))
}

func (LOGINERRORCODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

type C2SPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SPing) Reset()         { *m = C2SPing{} }
func (m *C2SPing) String() string { return proto.CompactTextString(m) }
func (*C2SPing) ProtoMessage()    {}
func (*C2SPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{0}
}

func (m *C2SPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SPing.Unmarshal(m, b)
}
func (m *C2SPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SPing.Marshal(b, m, deterministic)
}
func (m *C2SPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SPing.Merge(m, src)
}
func (m *C2SPing) XXX_Size() int {
	return xxx_messageInfo_C2SPing.Size(m)
}
func (m *C2SPing) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SPing.DiscardUnknown(m)
}

var xxx_messageInfo_C2SPing proto.InternalMessageInfo

type S2CPong struct {
	ZoneOffset           int64    `protobuf:"varint,1,opt,name=ZoneOffset,proto3" json:"ZoneOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CPong) Reset()         { *m = S2CPong{} }
func (m *S2CPong) String() string { return proto.CompactTextString(m) }
func (*S2CPong) ProtoMessage()    {}
func (*S2CPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{1}
}

func (m *S2CPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CPong.Unmarshal(m, b)
}
func (m *S2CPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CPong.Marshal(b, m, deterministic)
}
func (m *S2CPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CPong.Merge(m, src)
}
func (m *S2CPong) XXX_Size() int {
	return xxx_messageInfo_S2CPong.Size(m)
}
func (m *S2CPong) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CPong.DiscardUnknown(m)
}

var xxx_messageInfo_S2CPong proto.InternalMessageInfo

func (m *S2CPong) GetZoneOffset() int64 {
	if m != nil {
		return m.ZoneOffset
	}
	return 0
}

//登出游戏
type C2SLogout struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogout) Reset()         { *m = C2SLogout{} }
func (m *C2SLogout) String() string { return proto.CompactTextString(m) }
func (*C2SLogout) ProtoMessage()    {}
func (*C2SLogout) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{2}
}

func (m *C2SLogout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogout.Unmarshal(m, b)
}
func (m *C2SLogout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogout.Marshal(b, m, deterministic)
}
func (m *C2SLogout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogout.Merge(m, src)
}
func (m *C2SLogout) XXX_Size() int {
	return xxx_messageInfo_C2SLogout.Size(m)
}
func (m *C2SLogout) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogout.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogout proto.InternalMessageInfo

// 被踢下线
type S2CKick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CKick) Reset()         { *m = S2CKick{} }
func (m *S2CKick) String() string { return proto.CompactTextString(m) }
func (*S2CKick) ProtoMessage()    {}
func (*S2CKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{3}
}

func (m *S2CKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CKick.Unmarshal(m, b)
}
func (m *S2CKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CKick.Marshal(b, m, deterministic)
}
func (m *S2CKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CKick.Merge(m, src)
}
func (m *S2CKick) XXX_Size() int {
	return xxx_messageInfo_S2CKick.Size(m)
}
func (m *S2CKick) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CKick.DiscardUnknown(m)
}

var xxx_messageInfo_S2CKick proto.InternalMessageInfo

type Player struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	HeadIcon             int32    `protobuf:"varint,5,opt,name=HeadIcon,proto3" json:"HeadIcon,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Exp                  int32    `protobuf:"varint,7,opt,name=Exp,proto3" json:"Exp,omitempty"`
	Rank                 int32    `protobuf:"varint,8,opt,name=Rank,proto3" json:"Rank,omitempty"`
	HeadFrame            int32    `protobuf:"varint,9,opt,name=HeadFrame,proto3" json:"HeadFrame,omitempty"`
	Title                int32    `protobuf:"varint,10,opt,name=Title,proto3" json:"Title,omitempty"`
	Job                  int32    `protobuf:"varint,11,opt,name=Job,proto3" json:"Job,omitempty"`
	Sex                  int32    `protobuf:"varint,12,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Clan                 int32    `protobuf:"varint,13,opt,name=Clan,proto3" json:"Clan,omitempty"`
	ClanId               string   `protobuf:"bytes,14,opt,name=ClanId,proto3" json:"ClanId,omitempty"`
	HeroId               int32    `protobuf:"varint,15,opt,name=HeroId,proto3" json:"HeroId,omitempty"`
	Bubble               int32    `protobuf:"varint,16,opt,name=Bubble,proto3" json:"Bubble,omitempty"`
	ServerId             int32    `protobuf:"varint,17,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{4}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player) GetHeadIcon() int32 {
	if m != nil {
		return m.HeadIcon
	}
	return 0
}

func (m *Player) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Player) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Player) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Player) GetHeadFrame() int32 {
	if m != nil {
		return m.HeadFrame
	}
	return 0
}

func (m *Player) GetTitle() int32 {
	if m != nil {
		return m.Title
	}
	return 0
}

func (m *Player) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

func (m *Player) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Player) GetClan() int32 {
	if m != nil {
		return m.Clan
	}
	return 0
}

func (m *Player) GetClanId() string {
	if m != nil {
		return m.ClanId
	}
	return ""
}

func (m *Player) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Player) GetBubble() int32 {
	if m != nil {
		return m.Bubble
	}
	return 0
}

func (m *Player) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type Context struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Level                int64    `protobuf:"varint,4,opt,name=Level,proto3" json:"Level,omitempty"`
	Exp                  int64    `protobuf:"varint,5,opt,name=Exp,proto3" json:"Exp,omitempty"`
	FaceId               int64    `protobuf:"varint,6,opt,name=FaceId,proto3" json:"FaceId,omitempty"`
	FaceSlotId           int64    `protobuf:"varint,7,opt,name=FaceSlotId,proto3" json:"FaceSlotId,omitempty"`
	Rank                 int64    `protobuf:"varint,8,opt,name=Rank,proto3" json:"Rank,omitempty"`
	LineUp               int32    `protobuf:"varint,9,opt,name=LineUp,proto3" json:"LineUp,omitempty"`
	OfflineTime          int64    `protobuf:"varint,10,opt,name=OfflineTime,proto3" json:"OfflineTime,omitempty"`
	Chapter              int32    `protobuf:"varint,11,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	Stage                int32    `protobuf:"varint,12,opt,name=Stage,proto3" json:"Stage,omitempty"`
	OpenBoxLevel         int32    `protobuf:"varint,13,opt,name=OpenBoxLevel,proto3" json:"OpenBoxLevel,omitempty"`
	Job                  int32    `protobuf:"varint,14,opt,name=Job,proto3" json:"Job,omitempty"`
	ServerId             int32    `protobuf:"varint,15,opt,name=ServerId,proto3" json:"ServerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{5}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Context) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Context) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Context) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Context) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Context) GetFaceId() int64 {
	if m != nil {
		return m.FaceId
	}
	return 0
}

func (m *Context) GetFaceSlotId() int64 {
	if m != nil {
		return m.FaceSlotId
	}
	return 0
}

func (m *Context) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Context) GetLineUp() int32 {
	if m != nil {
		return m.LineUp
	}
	return 0
}

func (m *Context) GetOfflineTime() int64 {
	if m != nil {
		return m.OfflineTime
	}
	return 0
}

func (m *Context) GetChapter() int32 {
	if m != nil {
		return m.Chapter
	}
	return 0
}

func (m *Context) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *Context) GetOpenBoxLevel() int32 {
	if m != nil {
		return m.OpenBoxLevel
	}
	return 0
}

func (m *Context) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

func (m *Context) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type C2SLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Account              string   `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogin) Reset()         { *m = C2SLogin{} }
func (m *C2SLogin) String() string { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()    {}
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{6}
}

func (m *C2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogin.Unmarshal(m, b)
}
func (m *C2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogin.Marshal(b, m, deterministic)
}
func (m *C2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogin.Merge(m, src)
}
func (m *C2SLogin) XXX_Size() int {
	return xxx_messageInfo_C2SLogin.Size(m)
}
func (m *C2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogin proto.InternalMessageInfo

func (m *C2SLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *C2SLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type S2CLogin struct {
	Timestamp            int64                    `protobuf:"varint,1,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	EndTimeUnix          int64                    `protobuf:"varint,2,opt,name=EndTimeUnix,proto3" json:"EndTimeUnix,omitempty"`
	ZoneOffset           int64                    `protobuf:"varint,3,opt,name=ZoneOffset,proto3" json:"ZoneOffset,omitempty"`
	State                proto_public.CommonState `protobuf:"varint,4,opt,name=State,proto3,enum=Proto.Public.CommonState" json:"State,omitempty"`
	Player               *Player                  `protobuf:"bytes,5,opt,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{7}
}

func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (m *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(m, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func (m *S2CLogin) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *S2CLogin) GetEndTimeUnix() int64 {
	if m != nil {
		return m.EndTimeUnix
	}
	return 0
}

func (m *S2CLogin) GetZoneOffset() int64 {
	if m != nil {
		return m.ZoneOffset
	}
	return 0
}

func (m *S2CLogin) GetState() proto_public.CommonState {
	if m != nil {
		return m.State
	}
	return proto_public.CommonState_Faild
}

func (m *S2CLogin) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

//更改名字
type C2SChangeName struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeName) Reset()         { *m = C2SChangeName{} }
func (m *C2SChangeName) String() string { return proto.CompactTextString(m) }
func (*C2SChangeName) ProtoMessage()    {}
func (*C2SChangeName) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{8}
}

func (m *C2SChangeName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeName.Unmarshal(m, b)
}
func (m *C2SChangeName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeName.Marshal(b, m, deterministic)
}
func (m *C2SChangeName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeName.Merge(m, src)
}
func (m *C2SChangeName) XXX_Size() int {
	return xxx_messageInfo_C2SChangeName.Size(m)
}
func (m *C2SChangeName) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeName.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeName proto.InternalMessageInfo

func (m *C2SChangeName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type S2CChangeName struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeName) Reset()         { *m = S2CChangeName{} }
func (m *S2CChangeName) String() string { return proto.CompactTextString(m) }
func (*S2CChangeName) ProtoMessage()    {}
func (*S2CChangeName) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{9}
}

func (m *S2CChangeName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeName.Unmarshal(m, b)
}
func (m *S2CChangeName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeName.Marshal(b, m, deterministic)
}
func (m *S2CChangeName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeName.Merge(m, src)
}
func (m *S2CChangeName) XXX_Size() int {
	return xxx_messageInfo_S2CChangeName.Size(m)
}
func (m *S2CChangeName) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeName.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeName proto.InternalMessageInfo

func (m *S2CChangeName) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//更改称号
type C2SChangeTitle struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeTitle) Reset()         { *m = C2SChangeTitle{} }
func (m *C2SChangeTitle) String() string { return proto.CompactTextString(m) }
func (*C2SChangeTitle) ProtoMessage()    {}
func (*C2SChangeTitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{10}
}

func (m *C2SChangeTitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeTitle.Unmarshal(m, b)
}
func (m *C2SChangeTitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeTitle.Marshal(b, m, deterministic)
}
func (m *C2SChangeTitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeTitle.Merge(m, src)
}
func (m *C2SChangeTitle) XXX_Size() int {
	return xxx_messageInfo_C2SChangeTitle.Size(m)
}
func (m *C2SChangeTitle) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeTitle.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeTitle proto.InternalMessageInfo

func (m *C2SChangeTitle) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CChangeTitle struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeTitle) Reset()         { *m = S2CChangeTitle{} }
func (m *S2CChangeTitle) String() string { return proto.CompactTextString(m) }
func (*S2CChangeTitle) ProtoMessage()    {}
func (*S2CChangeTitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{11}
}

func (m *S2CChangeTitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeTitle.Unmarshal(m, b)
}
func (m *S2CChangeTitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeTitle.Marshal(b, m, deterministic)
}
func (m *S2CChangeTitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeTitle.Merge(m, src)
}
func (m *S2CChangeTitle) XXX_Size() int {
	return xxx_messageInfo_S2CChangeTitle.Size(m)
}
func (m *S2CChangeTitle) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeTitle.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeTitle proto.InternalMessageInfo

func (m *S2CChangeTitle) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//更改性别
type C2SChangeSex struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeSex) Reset()         { *m = C2SChangeSex{} }
func (m *C2SChangeSex) String() string { return proto.CompactTextString(m) }
func (*C2SChangeSex) ProtoMessage()    {}
func (*C2SChangeSex) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{12}
}

func (m *C2SChangeSex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeSex.Unmarshal(m, b)
}
func (m *C2SChangeSex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeSex.Marshal(b, m, deterministic)
}
func (m *C2SChangeSex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeSex.Merge(m, src)
}
func (m *C2SChangeSex) XXX_Size() int {
	return xxx_messageInfo_C2SChangeSex.Size(m)
}
func (m *C2SChangeSex) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeSex.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeSex proto.InternalMessageInfo

func (m *C2SChangeSex) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CChangeSex struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeSex) Reset()         { *m = S2CChangeSex{} }
func (m *S2CChangeSex) String() string { return proto.CompactTextString(m) }
func (*S2CChangeSex) ProtoMessage()    {}
func (*S2CChangeSex) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{13}
}

func (m *S2CChangeSex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeSex.Unmarshal(m, b)
}
func (m *S2CChangeSex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeSex.Marshal(b, m, deterministic)
}
func (m *S2CChangeSex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeSex.Merge(m, src)
}
func (m *S2CChangeSex) XXX_Size() int {
	return xxx_messageInfo_S2CChangeSex.Size(m)
}
func (m *S2CChangeSex) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeSex.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeSex proto.InternalMessageInfo

func (m *S2CChangeSex) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//更改泡泡
type C2SChangeBubble struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeBubble) Reset()         { *m = C2SChangeBubble{} }
func (m *C2SChangeBubble) String() string { return proto.CompactTextString(m) }
func (*C2SChangeBubble) ProtoMessage()    {}
func (*C2SChangeBubble) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{14}
}

func (m *C2SChangeBubble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeBubble.Unmarshal(m, b)
}
func (m *C2SChangeBubble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeBubble.Marshal(b, m, deterministic)
}
func (m *C2SChangeBubble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeBubble.Merge(m, src)
}
func (m *C2SChangeBubble) XXX_Size() int {
	return xxx_messageInfo_C2SChangeBubble.Size(m)
}
func (m *C2SChangeBubble) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeBubble.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeBubble proto.InternalMessageInfo

func (m *C2SChangeBubble) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CChangeBubble struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeBubble) Reset()         { *m = S2CChangeBubble{} }
func (m *S2CChangeBubble) String() string { return proto.CompactTextString(m) }
func (*S2CChangeBubble) ProtoMessage()    {}
func (*S2CChangeBubble) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{15}
}

func (m *S2CChangeBubble) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeBubble.Unmarshal(m, b)
}
func (m *S2CChangeBubble) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeBubble.Marshal(b, m, deterministic)
}
func (m *S2CChangeBubble) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeBubble.Merge(m, src)
}
func (m *S2CChangeBubble) XXX_Size() int {
	return xxx_messageInfo_S2CChangeBubble.Size(m)
}
func (m *S2CChangeBubble) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeBubble.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeBubble proto.InternalMessageInfo

func (m *S2CChangeBubble) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//更改头像
type C2SChangeHead struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeHead) Reset()         { *m = C2SChangeHead{} }
func (m *C2SChangeHead) String() string { return proto.CompactTextString(m) }
func (*C2SChangeHead) ProtoMessage()    {}
func (*C2SChangeHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{16}
}

func (m *C2SChangeHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeHead.Unmarshal(m, b)
}
func (m *C2SChangeHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeHead.Marshal(b, m, deterministic)
}
func (m *C2SChangeHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeHead.Merge(m, src)
}
func (m *C2SChangeHead) XXX_Size() int {
	return xxx_messageInfo_C2SChangeHead.Size(m)
}
func (m *C2SChangeHead) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeHead.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeHead proto.InternalMessageInfo

func (m *C2SChangeHead) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CChangeHead struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeHead) Reset()         { *m = S2CChangeHead{} }
func (m *S2CChangeHead) String() string { return proto.CompactTextString(m) }
func (*S2CChangeHead) ProtoMessage()    {}
func (*S2CChangeHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{17}
}

func (m *S2CChangeHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeHead.Unmarshal(m, b)
}
func (m *S2CChangeHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeHead.Marshal(b, m, deterministic)
}
func (m *S2CChangeHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeHead.Merge(m, src)
}
func (m *S2CChangeHead) XXX_Size() int {
	return xxx_messageInfo_S2CChangeHead.Size(m)
}
func (m *S2CChangeHead) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeHead.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeHead proto.InternalMessageInfo

func (m *S2CChangeHead) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//更换头像框
type C2SChangeHeadFrame struct {
	Frame                int32    `protobuf:"varint,1,opt,name=Frame,proto3" json:"Frame,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChangeHeadFrame) Reset()         { *m = C2SChangeHeadFrame{} }
func (m *C2SChangeHeadFrame) String() string { return proto.CompactTextString(m) }
func (*C2SChangeHeadFrame) ProtoMessage()    {}
func (*C2SChangeHeadFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{18}
}

func (m *C2SChangeHeadFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChangeHeadFrame.Unmarshal(m, b)
}
func (m *C2SChangeHeadFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChangeHeadFrame.Marshal(b, m, deterministic)
}
func (m *C2SChangeHeadFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChangeHeadFrame.Merge(m, src)
}
func (m *C2SChangeHeadFrame) XXX_Size() int {
	return xxx_messageInfo_C2SChangeHeadFrame.Size(m)
}
func (m *C2SChangeHeadFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChangeHeadFrame.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChangeHeadFrame proto.InternalMessageInfo

func (m *C2SChangeHeadFrame) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

type S2CChangeHeadFrame struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CChangeHeadFrame) Reset()         { *m = S2CChangeHeadFrame{} }
func (m *S2CChangeHeadFrame) String() string { return proto.CompactTextString(m) }
func (*S2CChangeHeadFrame) ProtoMessage()    {}
func (*S2CChangeHeadFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{19}
}

func (m *S2CChangeHeadFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChangeHeadFrame.Unmarshal(m, b)
}
func (m *S2CChangeHeadFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChangeHeadFrame.Marshal(b, m, deterministic)
}
func (m *S2CChangeHeadFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChangeHeadFrame.Merge(m, src)
}
func (m *S2CChangeHeadFrame) XXX_Size() int {
	return xxx_messageInfo_S2CChangeHeadFrame.Size(m)
}
func (m *S2CChangeHeadFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChangeHeadFrame.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChangeHeadFrame proto.InternalMessageInfo

func (m *S2CChangeHeadFrame) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

type PushPlayerInfo struct {
	Player               *Player  `protobuf:"bytes,1,opt,name=Player,proto3" json:"Player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPlayerInfo) Reset()         { *m = PushPlayerInfo{} }
func (m *PushPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PushPlayerInfo) ProtoMessage()    {}
func (*PushPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{20}
}

func (m *PushPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPlayerInfo.Unmarshal(m, b)
}
func (m *PushPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPlayerInfo.Marshal(b, m, deterministic)
}
func (m *PushPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPlayerInfo.Merge(m, src)
}
func (m *PushPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PushPlayerInfo.Size(m)
}
func (m *PushPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PushPlayerInfo proto.InternalMessageInfo

func (m *PushPlayerInfo) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

//切换职业
type C2STransformJob struct {
	Job                  int32    `protobuf:"varint,1,opt,name=Job,proto3" json:"Job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2STransformJob) Reset()         { *m = C2STransformJob{} }
func (m *C2STransformJob) String() string { return proto.CompactTextString(m) }
func (*C2STransformJob) ProtoMessage()    {}
func (*C2STransformJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{21}
}

func (m *C2STransformJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2STransformJob.Unmarshal(m, b)
}
func (m *C2STransformJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2STransformJob.Marshal(b, m, deterministic)
}
func (m *C2STransformJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2STransformJob.Merge(m, src)
}
func (m *C2STransformJob) XXX_Size() int {
	return xxx_messageInfo_C2STransformJob.Size(m)
}
func (m *C2STransformJob) XXX_DiscardUnknown() {
	xxx_messageInfo_C2STransformJob.DiscardUnknown(m)
}

var xxx_messageInfo_C2STransformJob proto.InternalMessageInfo

func (m *C2STransformJob) GetJob() int32 {
	if m != nil {
		return m.Job
	}
	return 0
}

type S2CTransformJob struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CTransformJob) Reset()         { *m = S2CTransformJob{} }
func (m *S2CTransformJob) String() string { return proto.CompactTextString(m) }
func (*S2CTransformJob) ProtoMessage()    {}
func (*S2CTransformJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{22}
}

func (m *S2CTransformJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CTransformJob.Unmarshal(m, b)
}
func (m *S2CTransformJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CTransformJob.Marshal(b, m, deterministic)
}
func (m *S2CTransformJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CTransformJob.Merge(m, src)
}
func (m *S2CTransformJob) XXX_Size() int {
	return xxx_messageInfo_S2CTransformJob.Size(m)
}
func (m *S2CTransformJob) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CTransformJob.DiscardUnknown(m)
}

var xxx_messageInfo_S2CTransformJob proto.InternalMessageInfo

func (m *S2CTransformJob) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

//获取人物属性道具相关
type C2SGetPlayerProp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetPlayerProp) Reset()         { *m = C2SGetPlayerProp{} }
func (m *C2SGetPlayerProp) String() string { return proto.CompactTextString(m) }
func (*C2SGetPlayerProp) ProtoMessage()    {}
func (*C2SGetPlayerProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{23}
}

func (m *C2SGetPlayerProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetPlayerProp.Unmarshal(m, b)
}
func (m *C2SGetPlayerProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetPlayerProp.Marshal(b, m, deterministic)
}
func (m *C2SGetPlayerProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetPlayerProp.Merge(m, src)
}
func (m *C2SGetPlayerProp) XXX_Size() int {
	return xxx_messageInfo_C2SGetPlayerProp.Size(m)
}
func (m *C2SGetPlayerProp) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetPlayerProp.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetPlayerProp proto.InternalMessageInfo

type S2CGetPlayerProp struct {
	HeadFrames           []int32  `protobuf:"varint,1,rep,packed,name=HeadFrames,proto3" json:"HeadFrames,omitempty"`
	Titles               []int32  `protobuf:"varint,2,rep,packed,name=Titles,proto3" json:"Titles,omitempty"`
	Bubbles              []int32  `protobuf:"varint,3,rep,packed,name=Bubbles,proto3" json:"Bubbles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CGetPlayerProp) Reset()         { *m = S2CGetPlayerProp{} }
func (m *S2CGetPlayerProp) String() string { return proto.CompactTextString(m) }
func (*S2CGetPlayerProp) ProtoMessage()    {}
func (*S2CGetPlayerProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{24}
}

func (m *S2CGetPlayerProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetPlayerProp.Unmarshal(m, b)
}
func (m *S2CGetPlayerProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetPlayerProp.Marshal(b, m, deterministic)
}
func (m *S2CGetPlayerProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetPlayerProp.Merge(m, src)
}
func (m *S2CGetPlayerProp) XXX_Size() int {
	return xxx_messageInfo_S2CGetPlayerProp.Size(m)
}
func (m *S2CGetPlayerProp) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetPlayerProp.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetPlayerProp proto.InternalMessageInfo

func (m *S2CGetPlayerProp) GetHeadFrames() []int32 {
	if m != nil {
		return m.HeadFrames
	}
	return nil
}

func (m *S2CGetPlayerProp) GetTitles() []int32 {
	if m != nil {
		return m.Titles
	}
	return nil
}

func (m *S2CGetPlayerProp) GetBubbles() []int32 {
	if m != nil {
		return m.Bubbles
	}
	return nil
}

//同步所有
type PushChangePlayerProp struct {
	HeadFrames           []int32  `protobuf:"varint,1,rep,packed,name=HeadFrames,proto3" json:"HeadFrames,omitempty"`
	Titles               []int32  `protobuf:"varint,2,rep,packed,name=Titles,proto3" json:"Titles,omitempty"`
	Bubbles              []int32  `protobuf:"varint,3,rep,packed,name=Bubbles,proto3" json:"Bubbles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushChangePlayerProp) Reset()         { *m = PushChangePlayerProp{} }
func (m *PushChangePlayerProp) String() string { return proto.CompactTextString(m) }
func (*PushChangePlayerProp) ProtoMessage()    {}
func (*PushChangePlayerProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{25}
}

func (m *PushChangePlayerProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushChangePlayerProp.Unmarshal(m, b)
}
func (m *PushChangePlayerProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushChangePlayerProp.Marshal(b, m, deterministic)
}
func (m *PushChangePlayerProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushChangePlayerProp.Merge(m, src)
}
func (m *PushChangePlayerProp) XXX_Size() int {
	return xxx_messageInfo_PushChangePlayerProp.Size(m)
}
func (m *PushChangePlayerProp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushChangePlayerProp.DiscardUnknown(m)
}

var xxx_messageInfo_PushChangePlayerProp proto.InternalMessageInfo

func (m *PushChangePlayerProp) GetHeadFrames() []int32 {
	if m != nil {
		return m.HeadFrames
	}
	return nil
}

func (m *PushChangePlayerProp) GetTitles() []int32 {
	if m != nil {
		return m.Titles
	}
	return nil
}

func (m *PushChangePlayerProp) GetBubbles() []int32 {
	if m != nil {
		return m.Bubbles
	}
	return nil
}

//获取玩家数据通过id
type C2SGetPlayerById struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SGetPlayerById) Reset()         { *m = C2SGetPlayerById{} }
func (m *C2SGetPlayerById) String() string { return proto.CompactTextString(m) }
func (*C2SGetPlayerById) ProtoMessage()    {}
func (*C2SGetPlayerById) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{26}
}

func (m *C2SGetPlayerById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SGetPlayerById.Unmarshal(m, b)
}
func (m *C2SGetPlayerById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SGetPlayerById.Marshal(b, m, deterministic)
}
func (m *C2SGetPlayerById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SGetPlayerById.Merge(m, src)
}
func (m *C2SGetPlayerById) XXX_Size() int {
	return xxx_messageInfo_C2SGetPlayerById.Size(m)
}
func (m *C2SGetPlayerById) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SGetPlayerById.DiscardUnknown(m)
}

var xxx_messageInfo_C2SGetPlayerById proto.InternalMessageInfo

func (m *C2SGetPlayerById) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CGetPlayerById struct {
	Info                 *proto_public.CommonPlayerInfo                     `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	EquipInfo            map[int32]*proto_public.CommonPlayerEquipInfo      `protobuf:"bytes,2,rep,name=EquipInfo,proto3" json:"EquipInfo,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cards                map[int32]*proto_public.CommonPlayerLineUpInfo     `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Weapont              int32                                              `protobuf:"varint,4,opt,name=Weapont,proto3" json:"Weapont,omitempty"`
	MountId              int32                                              `protobuf:"varint,5,opt,name=MountId,proto3" json:"MountId,omitempty"`
	BracesId             int32                                              `protobuf:"varint,6,opt,name=BracesId,proto3" json:"BracesId,omitempty"`
	Collections          map[int32]*proto_public.CommonPlayerCollectionInfo `protobuf:"bytes,7,rep,name=collections,proto3" json:"collections,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 *proto_public.BattleHeroData                       `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *S2CGetPlayerById) Reset()         { *m = S2CGetPlayerById{} }
func (m *S2CGetPlayerById) String() string { return proto.CompactTextString(m) }
func (*S2CGetPlayerById) ProtoMessage()    {}
func (*S2CGetPlayerById) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{27}
}

func (m *S2CGetPlayerById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CGetPlayerById.Unmarshal(m, b)
}
func (m *S2CGetPlayerById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CGetPlayerById.Marshal(b, m, deterministic)
}
func (m *S2CGetPlayerById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CGetPlayerById.Merge(m, src)
}
func (m *S2CGetPlayerById) XXX_Size() int {
	return xxx_messageInfo_S2CGetPlayerById.Size(m)
}
func (m *S2CGetPlayerById) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CGetPlayerById.DiscardUnknown(m)
}

var xxx_messageInfo_S2CGetPlayerById proto.InternalMessageInfo

func (m *S2CGetPlayerById) GetInfo() *proto_public.CommonPlayerInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *S2CGetPlayerById) GetEquipInfo() map[int32]*proto_public.CommonPlayerEquipInfo {
	if m != nil {
		return m.EquipInfo
	}
	return nil
}

func (m *S2CGetPlayerById) GetCards() map[int32]*proto_public.CommonPlayerLineUpInfo {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *S2CGetPlayerById) GetWeapont() int32 {
	if m != nil {
		return m.Weapont
	}
	return 0
}

func (m *S2CGetPlayerById) GetMountId() int32 {
	if m != nil {
		return m.MountId
	}
	return 0
}

func (m *S2CGetPlayerById) GetBracesId() int32 {
	if m != nil {
		return m.BracesId
	}
	return 0
}

func (m *S2CGetPlayerById) GetCollections() map[int32]*proto_public.CommonPlayerCollectionInfo {
	if m != nil {
		return m.Collections
	}
	return nil
}

func (m *S2CGetPlayerById) GetData() *proto_public.BattleHeroData {
	if m != nil {
		return m.Data
	}
	return nil
}

//战力变化
type C2SPlayerPowerChange struct {
	Power                int64    `protobuf:"varint,1,opt,name=Power,proto3" json:"Power,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SPlayerPowerChange) Reset()         { *m = C2SPlayerPowerChange{} }
func (m *C2SPlayerPowerChange) String() string { return proto.CompactTextString(m) }
func (*C2SPlayerPowerChange) ProtoMessage()    {}
func (*C2SPlayerPowerChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{28}
}

func (m *C2SPlayerPowerChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SPlayerPowerChange.Unmarshal(m, b)
}
func (m *C2SPlayerPowerChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SPlayerPowerChange.Marshal(b, m, deterministic)
}
func (m *C2SPlayerPowerChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SPlayerPowerChange.Merge(m, src)
}
func (m *C2SPlayerPowerChange) XXX_Size() int {
	return xxx_messageInfo_C2SPlayerPowerChange.Size(m)
}
func (m *C2SPlayerPowerChange) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SPlayerPowerChange.DiscardUnknown(m)
}

var xxx_messageInfo_C2SPlayerPowerChange proto.InternalMessageInfo

func (m *C2SPlayerPowerChange) GetPower() int64 {
	if m != nil {
		return m.Power
	}
	return 0
}

type S2CPlayerPowerChange struct {
	CODE                 LOGINERRORCODE `protobuf:"varint,1,opt,name=CODE,proto3,enum=Proto.Player.LOGINERRORCODE" json:"CODE,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CPlayerPowerChange) Reset()         { *m = S2CPlayerPowerChange{} }
func (m *S2CPlayerPowerChange) String() string { return proto.CompactTextString(m) }
func (*S2CPlayerPowerChange) ProtoMessage()    {}
func (*S2CPlayerPowerChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d803d1b635d5c6, []int{29}
}

func (m *S2CPlayerPowerChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CPlayerPowerChange.Unmarshal(m, b)
}
func (m *S2CPlayerPowerChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CPlayerPowerChange.Marshal(b, m, deterministic)
}
func (m *S2CPlayerPowerChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CPlayerPowerChange.Merge(m, src)
}
func (m *S2CPlayerPowerChange) XXX_Size() int {
	return xxx_messageInfo_S2CPlayerPowerChange.Size(m)
}
func (m *S2CPlayerPowerChange) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CPlayerPowerChange.DiscardUnknown(m)
}

var xxx_messageInfo_S2CPlayerPowerChange proto.InternalMessageInfo

func (m *S2CPlayerPowerChange) GetCODE() LOGINERRORCODE {
	if m != nil {
		return m.CODE
	}
	return LOGINERRORCODE_ERROR_OK
}

func init() {
	proto.RegisterEnum("Proto.Player.LoginResult", LoginResult_name, LoginResult_value)
	proto.RegisterEnum("Proto.Player.LOGINERRORCODE", LOGINERRORCODE_name, LOGINERRORCODE_value)
	proto.RegisterType((*C2SPing)(nil), "Proto.Player.C2SPing")
	proto.RegisterType((*S2CPong)(nil), "Proto.Player.S2CPong")
	proto.RegisterType((*C2SLogout)(nil), "Proto.Player.C2SLogout")
	proto.RegisterType((*S2CKick)(nil), "Proto.Player.S2CKick")
	proto.RegisterType((*Player)(nil), "Proto.Player.Player")
	proto.RegisterType((*Context)(nil), "Proto.Player.Context")
	proto.RegisterType((*C2SLogin)(nil), "Proto.Player.C2SLogin")
	proto.RegisterType((*S2CLogin)(nil), "Proto.Player.S2CLogin")
	proto.RegisterType((*C2SChangeName)(nil), "Proto.Player.C2SChangeName")
	proto.RegisterType((*S2CChangeName)(nil), "Proto.Player.S2CChangeName")
	proto.RegisterType((*C2SChangeTitle)(nil), "Proto.Player.C2SChangeTitle")
	proto.RegisterType((*S2CChangeTitle)(nil), "Proto.Player.S2CChangeTitle")
	proto.RegisterType((*C2SChangeSex)(nil), "Proto.Player.C2SChangeSex")
	proto.RegisterType((*S2CChangeSex)(nil), "Proto.Player.S2CChangeSex")
	proto.RegisterType((*C2SChangeBubble)(nil), "Proto.Player.C2SChangeBubble")
	proto.RegisterType((*S2CChangeBubble)(nil), "Proto.Player.S2CChangeBubble")
	proto.RegisterType((*C2SChangeHead)(nil), "Proto.Player.C2SChangeHead")
	proto.RegisterType((*S2CChangeHead)(nil), "Proto.Player.S2CChangeHead")
	proto.RegisterType((*C2SChangeHeadFrame)(nil), "Proto.Player.C2SChangeHeadFrame")
	proto.RegisterType((*S2CChangeHeadFrame)(nil), "Proto.Player.S2CChangeHeadFrame")
	proto.RegisterType((*PushPlayerInfo)(nil), "Proto.Player.PushPlayerInfo")
	proto.RegisterType((*C2STransformJob)(nil), "Proto.Player.C2STransformJob")
	proto.RegisterType((*S2CTransformJob)(nil), "Proto.Player.S2CTransformJob")
	proto.RegisterType((*C2SGetPlayerProp)(nil), "Proto.Player.C2SGetPlayerProp")
	proto.RegisterType((*S2CGetPlayerProp)(nil), "Proto.Player.S2CGetPlayerProp")
	proto.RegisterType((*PushChangePlayerProp)(nil), "Proto.Player.PushChangePlayerProp")
	proto.RegisterType((*C2SGetPlayerById)(nil), "Proto.Player.C2SGetPlayerById")
	proto.RegisterType((*S2CGetPlayerById)(nil), "Proto.Player.S2CGetPlayerById")
	proto.RegisterMapType((map[int32]*proto_public.CommonPlayerLineUpInfo)(nil), "Proto.Player.S2CGetPlayerById.CardsEntry")
	proto.RegisterMapType((map[int32]*proto_public.CommonPlayerCollectionInfo)(nil), "Proto.Player.S2CGetPlayerById.CollectionsEntry")
	proto.RegisterMapType((map[int32]*proto_public.CommonPlayerEquipInfo)(nil), "Proto.Player.S2CGetPlayerById.EquipInfoEntry")
	proto.RegisterType((*C2SPlayerPowerChange)(nil), "Proto.Player.C2SPlayerPowerChange")
	proto.RegisterType((*S2CPlayerPowerChange)(nil), "Proto.Player.S2CPlayerPowerChange")
}

func init() {
	proto.RegisterFile("player.proto", fileDescriptor_41d803d1b635d5c6)
}

var fileDescriptor_41d803d1b635d5c6 = []byte{
	// 1300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xd1, 0x6e, 0xdb, 0xc6,
	0x12, 0x0d, 0x45, 0x4b, 0xb6, 0x46, 0xb2, 0xcc, 0x2c, 0x74, 0x03, 0x5e, 0xdf, 0x20, 0xf1, 0x65,
	0xfa, 0xe0, 0x04, 0xa9, 0x53, 0xb0, 0x2f, 0x6d, 0x1e, 0xd2, 0x5a, 0x34, 0x1d, 0x33, 0x76, 0x24,
	0x95, 0x54, 0x1a, 0x20, 0x0f, 0x0d, 0xd6, 0xe4, 0xda, 0x26, 0x4c, 0x73, 0x55, 0x92, 0x4a, 0xec,
	0x1f, 0xe8, 0x63, 0x3f, 0xa0, 0x7f, 0xd4, 0x1f, 0xe8, 0x6f, 0xf4, 0x17, 0x8a, 0xd9, 0x5d, 0x52,
	0xa2, 0x92, 0x20, 0x15, 0xd0, 0x3e, 0x89, 0xe7, 0x70, 0x76, 0xce, 0xec, 0xcc, 0xce, 0x70, 0x05,
	0xdd, 0x69, 0x42, 0x6f, 0x58, 0xb6, 0x37, 0xcd, 0x78, 0xc1, 0x49, 0x77, 0x8c, 0x3f, 0x7b, 0x63,
	0xc1, 0x6d, 0x77, 0xc7, 0xb3, 0xd3, 0x24, 0x0e, 0xf7, 0x04, 0x69, 0xb5, 0x61, 0xdd, 0xb1, 0x83,
	0x71, 0x9c, 0x9e, 0x5b, 0x0f, 0x61, 0x3d, 0xb0, 0x9d, 0x31, 0x4f, 0xcf, 0xc9, 0x3d, 0x80, 0x37,
	0x3c, 0x65, 0xa3, 0xb3, 0xb3, 0x9c, 0x15, 0xa6, 0xb6, 0xa3, 0xed, 0xea, 0xfe, 0x02, 0x63, 0x75,
	0xa0, 0xed, 0xd8, 0xc1, 0x09, 0x3f, 0xe7, 0xb3, 0x02, 0x5d, 0x04, 0xb6, 0x73, 0x1c, 0x87, 0x97,
	0xd6, 0x2f, 0x3a, 0xb4, 0xa4, 0x0c, 0xe9, 0x41, 0xc3, 0x8b, 0xd4, 0xd2, 0x86, 0x17, 0x11, 0x03,
	0xf4, 0x57, 0x71, 0x64, 0x36, 0x76, 0xb4, 0xdd, 0xb6, 0x8f, 0x8f, 0x84, 0xc0, 0xda, 0x90, 0x5e,
	0x31, 0x53, 0x17, 0x94, 0x78, 0x26, 0x7d, 0x68, 0x9e, 0xb0, 0x77, 0x2c, 0x31, 0xd7, 0x76, 0xb4,
	0xdd, 0xa6, 0x2f, 0x01, 0xd9, 0x86, 0x8d, 0x23, 0x46, 0x23, 0x2f, 0xe4, 0xa9, 0xd9, 0x14, 0x2f,
	0x2a, 0x8c, 0xa1, 0x3a, 0x19, 0xa3, 0x05, 0x9b, 0xc4, 0x57, 0xcc, 0x6c, 0xc9, 0x50, 0xe7, 0x0c,
	0xea, 0xba, 0xd7, 0x53, 0x73, 0x5d, 0x2c, 0xc3, 0x47, 0xd4, 0xf5, 0x69, 0x7a, 0x69, 0x6e, 0x08,
	0x4a, 0x3c, 0x93, 0xbb, 0xd0, 0x46, 0x8f, 0x87, 0x19, 0x06, 0xd4, 0x16, 0x2f, 0xe6, 0x04, 0x46,
	0x35, 0x89, 0x8b, 0x84, 0x99, 0x20, 0xa3, 0x12, 0x00, 0x3d, 0xbf, 0xe0, 0xa7, 0x66, 0x47, 0x7a,
	0x7e, 0xc1, 0x4f, 0x91, 0x09, 0xd8, 0xb5, 0xd9, 0x95, 0x4c, 0xc0, 0xae, 0x51, 0xcb, 0x49, 0x68,
	0x6a, 0x6e, 0x4a, 0x2d, 0x7c, 0x26, 0x77, 0xa0, 0x85, 0xbf, 0x5e, 0x64, 0xf6, 0xc4, 0xce, 0x15,
	0x42, 0xfe, 0x88, 0x65, 0xdc, 0x8b, 0xcc, 0x2d, 0x61, 0xad, 0x10, 0xf2, 0x83, 0xd9, 0xe9, 0x69,
	0xc2, 0x4c, 0x43, 0xf2, 0x12, 0x61, 0x56, 0x02, 0x96, 0xbd, 0x63, 0x99, 0x17, 0x99, 0xb7, 0x65,
	0x56, 0x4a, 0x6c, 0xfd, 0xd9, 0x80, 0x75, 0x87, 0xa7, 0x05, 0xbb, 0x2e, 0xfe, 0x89, 0x4a, 0xe8,
	0x65, 0x25, 0x54, 0x36, 0x9b, 0x82, 0x13, 0xd9, 0xbc, 0x03, 0xad, 0x43, 0x1a, 0x32, 0x2f, 0x52,
	0xb9, 0x57, 0x08, 0xeb, 0x82, 0x4f, 0x41, 0xc2, 0x0b, 0x2f, 0x12, 0xe9, 0xd7, 0xfd, 0x05, 0xa6,
	0x56, 0x05, 0x5d, 0x55, 0xe1, 0x0e, 0xb4, 0x4e, 0xe2, 0x94, 0xbd, 0x9a, 0xaa, 0x12, 0x28, 0x44,
	0x76, 0xa0, 0x33, 0x3a, 0x3b, 0x4b, 0xe2, 0x54, 0x16, 0x19, 0xc4, 0x92, 0x45, 0x8a, 0x98, 0xb0,
	0xee, 0x5c, 0xd0, 0x69, 0xc1, 0x32, 0x55, 0x8f, 0x12, 0xe2, 0x3e, 0x82, 0x82, 0x9e, 0x33, 0x55,
	0x15, 0x09, 0x88, 0x05, 0xdd, 0xd1, 0x94, 0xa5, 0x03, 0x7e, 0x2d, 0x37, 0x29, 0xeb, 0x53, 0xe3,
	0xca, 0xfa, 0xf6, 0xe6, 0xf5, 0x5d, 0xcc, 0xf8, 0xd6, 0x52, 0xc6, 0x9f, 0xc2, 0x86, 0x6c, 0x89,
	0x38, 0x15, 0xe7, 0x85, 0x5f, 0xb2, 0x54, 0x24, 0xbd, 0xed, 0x4b, 0x80, 0x31, 0xee, 0x87, 0x21,
	0x9f, 0xa5, 0x85, 0xca, 0x7d, 0x09, 0xad, 0xdf, 0x35, 0xd8, 0x08, 0x6c, 0x47, 0x2e, 0xbe, 0x0b,
	0x6d, 0xdc, 0x52, 0x5e, 0xd0, 0xab, 0xa9, 0xaa, 0xda, 0x9c, 0xc0, 0x54, 0xb8, 0x69, 0x84, 0xf8,
	0x55, 0x1a, 0x5f, 0x0b, 0x47, 0xba, 0xbf, 0x48, 0x2d, 0xf5, 0xae, 0xbe, 0xdc, 0xbb, 0xe4, 0x89,
	0x48, 0x48, 0xc1, 0x44, 0x61, 0x7b, 0xf6, 0x7f, 0xf7, 0xd4, 0x74, 0x90, 0x53, 0xc1, 0xe1, 0x57,
	0x57, 0x3c, 0x15, 0x06, 0xbe, 0xb4, 0x23, 0x8f, 0xcb, 0x9e, 0x16, 0x65, 0xef, 0xd8, 0xfd, 0xbd,
	0xc5, 0x79, 0xa2, 0x7e, 0x7c, 0x65, 0x63, 0x3d, 0x80, 0x4d, 0xc7, 0x0e, 0x9c, 0x0b, 0x9a, 0x9e,
	0x33, 0x71, 0x90, 0xca, 0xc3, 0xa5, 0xcd, 0x0f, 0x97, 0xb5, 0x0f, 0x9b, 0x81, 0xed, 0x2c, 0x18,
	0x7d, 0x05, 0x6b, 0xce, 0xe8, 0xc0, 0x15, 0x46, 0x3d, 0xfb, 0x6e, 0x5d, 0xe1, 0x64, 0xf4, 0xdc,
	0x1b, 0xba, 0xbe, 0x3f, 0xf2, 0xd1, 0xc6, 0x17, 0x96, 0xd6, 0x0e, 0xf4, 0x2a, 0x1d, 0xd9, 0x8f,
	0xf3, 0x73, 0xde, 0xc4, 0x73, 0x6e, 0x0d, 0xa0, 0x57, 0x89, 0x48, 0x8b, 0xd5, 0x55, 0xee, 0x41,
	0xb7, 0x52, 0xc1, 0x7e, 0x5e, 0xd6, 0xf8, 0x1e, 0xba, 0x95, 0x06, 0xbe, 0x5f, 0x5d, 0xe1, 0xff,
	0xb0, 0x55, 0x29, 0xa8, 0xc6, 0x5e, 0x16, 0x71, 0x60, 0xab, 0x12, 0x51, 0x26, 0xab, 0xeb, 0xdc,
	0x5f, 0xa8, 0x0b, 0x4e, 0xb6, 0x0f, 0x54, 0x16, 0x6b, 0x22, 0x0c, 0x56, 0xd7, 0x78, 0x04, 0xa4,
	0xa6, 0x51, 0x4d, 0x4f, 0x39, 0x57, 0xa5, 0x96, 0x04, 0xd6, 0x21, 0x90, 0x9a, 0x9c, 0xb4, 0x5d,
	0x5d, 0xf3, 0x19, 0xf4, 0xc6, 0xb3, 0xfc, 0x42, 0x9a, 0x78, 0xe9, 0x19, 0x5f, 0x38, 0xaf, 0xda,
	0xdf, 0x3a, 0xaf, 0x98, 0xff, 0x49, 0x46, 0xd3, 0xfc, 0x8c, 0x67, 0x57, 0x6a, 0x8c, 0x63, 0xe3,
	0x6b, 0x55, 0xe3, 0xab, 0x0a, 0xd4, 0x8c, 0x56, 0x8f, 0x94, 0x80, 0xe1, 0xd8, 0xc1, 0x73, 0x56,
	0x48, 0xa3, 0x71, 0xc6, 0xa7, 0x56, 0x04, 0x46, 0x60, 0x3b, 0x35, 0x0e, 0x1b, 0xb8, 0x4a, 0x48,
	0x6e, 0x6a, 0x3b, 0xfa, 0x6e, 0xd3, 0x5f, 0x60, 0x70, 0x4a, 0x8a, 0xe3, 0x9c, 0x9b, 0x0d, 0xf1,
	0x4e, 0x21, 0x9c, 0x2f, 0xf2, 0x74, 0xe4, 0xa6, 0x2e, 0x5e, 0x94, 0xd0, 0xba, 0x80, 0x3e, 0xe6,
	0x48, 0x26, 0xfb, 0x5f, 0x55, 0xb2, 0xea, 0x7b, 0x1c, 0xdc, 0x78, 0xd1, 0xf2, 0xf7, 0xc7, 0xfa,
	0xa3, 0x59, 0xdf, 0xb4, 0x30, 0xb2, 0x61, 0x0d, 0x8b, 0xa7, 0x4a, 0x76, 0xef, 0x63, 0x43, 0x69,
	0x5e, 0x62, 0x5f, 0xd8, 0x92, 0x63, 0x68, 0xbb, 0x3f, 0xcf, 0xe2, 0xa9, 0x58, 0x88, 0x11, 0x76,
	0xec, 0x2f, 0xeb, 0x75, 0x58, 0x96, 0xd9, 0xab, 0xec, 0xdd, 0xb4, 0xc8, 0x6e, 0xfc, 0xf9, 0x7a,
	0xf2, 0x1d, 0x34, 0x43, 0x9a, 0x45, 0x72, 0x47, 0x1d, 0xfb, 0xe1, 0x67, 0x1c, 0x39, 0x68, 0x2b,
	0x9d, 0xc8, 0x75, 0x98, 0x94, 0xd7, 0x8c, 0x4e, 0x79, 0x5a, 0xa8, 0xcb, 0x4b, 0x09, 0xf1, 0xcd,
	0x4b, 0x9c, 0xf3, 0x5e, 0xa4, 0x6e, 0x2f, 0x25, 0xc4, 0x0f, 0xca, 0x20, 0xa3, 0x21, 0xcb, 0xd5,
	0xe7, 0xb3, 0xe9, 0x57, 0x98, 0xfc, 0x00, 0x9d, 0x90, 0x27, 0x09, 0x0b, 0x8b, 0x98, 0xa7, 0xb9,
	0xb9, 0x2e, 0xc2, 0x7a, 0xf2, 0xb9, 0xb0, 0xe6, 0x2b, 0x64, 0x70, 0x8b, 0x3e, 0xf0, 0xcc, 0x46,
	0xb4, 0xa0, 0xe2, 0x9b, 0xdb, 0x99, 0x9f, 0x59, 0x99, 0xe4, 0x01, 0x2d, 0x8a, 0x84, 0xe1, 0x9d,
	0xe3, 0x80, 0x16, 0xd4, 0x17, 0x96, 0xdb, 0x14, 0x7a, 0xf5, 0x94, 0x61, 0x73, 0x5c, 0xb2, 0x9b,
	0xb2, 0x39, 0x2e, 0xd9, 0x0d, 0xf9, 0x16, 0x9a, 0xef, 0x68, 0x32, 0x63, 0xe2, 0x63, 0xd4, 0xb1,
	0x1f, 0x7c, 0xba, 0x76, 0x95, 0x2b, 0x5f, 0xae, 0x78, 0xda, 0xf8, 0x46, 0xdb, 0xfe, 0x09, 0x60,
	0x9e, 0xcc, 0x8f, 0xb8, 0x7f, 0x5a, 0x77, 0xff, 0xc5, 0xa7, 0xdd, 0xcb, 0xdb, 0xc2, 0xb2, 0xff,
	0x0b, 0x30, 0x96, 0xb3, 0xf2, 0x11, 0x95, 0x67, 0x75, 0x95, 0xdd, 0x4f, 0xab, 0xcc, 0x9d, 0x2d,
	0x29, 0x59, 0x8f, 0xa1, 0x8f, 0x77, 0x69, 0xd9, 0x5f, 0xfc, 0x3d, 0xcb, 0x64, 0xc3, 0xe1, 0x00,
	0x14, 0x50, 0xf5, 0x80, 0x04, 0xd6, 0x11, 0xf4, 0xf1, 0xba, 0xfd, 0x81, 0xf5, 0xca, 0x83, 0xe5,
	0xd1, 0xaf, 0x1a, 0x74, 0xc4, 0xdd, 0xc1, 0x67, 0xf9, 0x2c, 0x29, 0x88, 0x01, 0x5d, 0x01, 0x83,
	0x59, 0x18, 0xb2, 0x3c, 0x37, 0x6e, 0x91, 0x4d, 0x68, 0x0b, 0xe6, 0x90, 0xc6, 0x89, 0xa1, 0x55,
	0x06, 0x07, 0x03, 0x37, 0xcb, 0x78, 0x66, 0x34, 0x48, 0x1f, 0x0c, 0xc1, 0xc8, 0x8b, 0xb3, 0x64,
	0x75, 0xf2, 0x1f, 0xb8, 0xad, 0xfc, 0x4e, 0x13, 0x1a, 0x2a, 0x7a, 0x8d, 0xdc, 0x87, 0xff, 0x09,
	0x5a, 0x5d, 0x5f, 0x46, 0xd9, 0x98, 0xe6, 0xf9, 0x7b, 0x9e, 0x45, 0xd2, 0xa0, 0xf9, 0xe8, 0x37,
	0x0d, 0x7a, 0xf5, 0x48, 0x49, 0x17, 0x36, 0x04, 0x78, 0x3b, 0x3a, 0x36, 0x6e, 0xa1, 0x9c, 0x44,
	0xc3, 0xd1, 0x70, 0xff, 0xa5, 0xeb, 0xec, 0xfb, 0x07, 0x86, 0x46, 0x6e, 0xc3, 0x66, 0xc9, 0x4e,
	0xbc, 0xc9, 0x89, 0x6b, 0x34, 0x30, 0xd2, 0x92, 0x3a, 0x72, 0xfd, 0x91, 0xa1, 0x93, 0x1e, 0x80,
	0x64, 0x82, 0x63, 0x6f, 0x68, 0xac, 0x11, 0x13, 0xfa, 0x0a, 0xbb, 0xc3, 0xc0, 0x9b, 0x78, 0x3f,
	0xba, 0xaf, 0x47, 0xfe, 0x41, 0x60, 0x34, 0x31, 0x7a, 0xf9, 0xc6, 0x9b, 0xb8, 0x2f, 0x87, 0x23,
	0x77, 0xf8, 0x7c, 0x72, 0x64, 0xb4, 0x06, 0x5b, 0x6f, 0x36, 0x9f, 0x88, 0xff, 0x45, 0x6f, 0xe5,
	0x9f, 0xa4, 0xd3, 0x96, 0x40, 0x5f, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x14, 0x18, 0x5c, 0x33,
	0x35, 0x0d, 0x00, 0x00,
}
