// Code generated by protoc-gen-go. DO NOT EDIT.
// source: magic.proto

package proto_magic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//错误码
type ERRORCODEMAGIC int32

const (
	ERRORCODEMAGIC_ERR_Ok             ERRORCODEMAGIC = 0
	ERRORCODEMAGIC_ERROR_NOMAGIC      ERRORCODEMAGIC = 1
	ERRORCODEMAGIC_ERROR_PARAMERROR   ERRORCODEMAGIC = 2
	ERRORCODEMAGIC_ERROR_NOENGTHERROR ERRORCODEMAGIC = 3
)

var ERRORCODEMAGIC_name = map[int32]string{
	0: "ERR_Ok",
	1: "ERROR_NOMAGIC",
	2: "ERROR_PARAMERROR",
	3: "ERROR_NOENGTHERROR",
}

var ERRORCODEMAGIC_value = map[string]int32{
	"ERR_Ok":             0,
	"ERROR_NOMAGIC":      1,
	"ERROR_PARAMERROR":   2,
	"ERROR_NOENGTHERROR": 3,
}

func (x ERRORCODEMAGIC) String() string {
	return proto.EnumName(ERRORCODEMAGIC_name, int32(x))
}

func (ERRORCODEMAGIC) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{0}
}

type C2SInitMagic struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SInitMagic) Reset()         { *m = C2SInitMagic{} }
func (m *C2SInitMagic) String() string { return proto.CompactTextString(m) }
func (*C2SInitMagic) ProtoMessage()    {}
func (*C2SInitMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{0}
}

func (m *C2SInitMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SInitMagic.Unmarshal(m, b)
}
func (m *C2SInitMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SInitMagic.Marshal(b, m, deterministic)
}
func (m *C2SInitMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SInitMagic.Merge(m, src)
}
func (m *C2SInitMagic) XXX_Size() int {
	return xxx_messageInfo_C2SInitMagic.Size(m)
}
func (m *C2SInitMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SInitMagic.DiscardUnknown(m)
}

var xxx_messageInfo_C2SInitMagic proto.InternalMessageInfo

type S2CInitMagic struct {
	Option               *MagicOption `protobuf:"bytes,1,opt,name=Option,proto3" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *S2CInitMagic) Reset()         { *m = S2CInitMagic{} }
func (m *S2CInitMagic) String() string { return proto.CompactTextString(m) }
func (*S2CInitMagic) ProtoMessage()    {}
func (*S2CInitMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{1}
}

func (m *S2CInitMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CInitMagic.Unmarshal(m, b)
}
func (m *S2CInitMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CInitMagic.Marshal(b, m, deterministic)
}
func (m *S2CInitMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CInitMagic.Merge(m, src)
}
func (m *S2CInitMagic) XXX_Size() int {
	return xxx_messageInfo_S2CInitMagic.Size(m)
}
func (m *S2CInitMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CInitMagic.DiscardUnknown(m)
}

var xxx_messageInfo_S2CInitMagic proto.InternalMessageInfo

func (m *S2CInitMagic) GetOption() *MagicOption {
	if m != nil {
		return m.Option
	}
	return nil
}

type MagicOption struct {
	Magics               map[int32]*MagicItem `protobuf:"bytes,1,rep,name=Magics,proto3" json:"Magics,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LineUp               []int32              `protobuf:"varint,2,rep,packed,name=LineUp,proto3" json:"LineUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MagicOption) Reset()         { *m = MagicOption{} }
func (m *MagicOption) String() string { return proto.CompactTextString(m) }
func (*MagicOption) ProtoMessage()    {}
func (*MagicOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{2}
}

func (m *MagicOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicOption.Unmarshal(m, b)
}
func (m *MagicOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicOption.Marshal(b, m, deterministic)
}
func (m *MagicOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicOption.Merge(m, src)
}
func (m *MagicOption) XXX_Size() int {
	return xxx_messageInfo_MagicOption.Size(m)
}
func (m *MagicOption) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicOption.DiscardUnknown(m)
}

var xxx_messageInfo_MagicOption proto.InternalMessageInfo

func (m *MagicOption) GetMagics() map[int32]*MagicItem {
	if m != nil {
		return m.Magics
	}
	return nil
}

func (m *MagicOption) GetLineUp() []int32 {
	if m != nil {
		return m.LineUp
	}
	return nil
}

type MagicItem struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Num                  int32    `protobuf:"varint,3,opt,name=Num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MagicItem) Reset()         { *m = MagicItem{} }
func (m *MagicItem) String() string { return proto.CompactTextString(m) }
func (*MagicItem) ProtoMessage()    {}
func (*MagicItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{3}
}

func (m *MagicItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MagicItem.Unmarshal(m, b)
}
func (m *MagicItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MagicItem.Marshal(b, m, deterministic)
}
func (m *MagicItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MagicItem.Merge(m, src)
}
func (m *MagicItem) XXX_Size() int {
	return xxx_messageInfo_MagicItem.Size(m)
}
func (m *MagicItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MagicItem.DiscardUnknown(m)
}

var xxx_messageInfo_MagicItem proto.InternalMessageInfo

func (m *MagicItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MagicItem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MagicItem) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

//装配
type C2SWearMagic struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SWearMagic) Reset()         { *m = C2SWearMagic{} }
func (m *C2SWearMagic) String() string { return proto.CompactTextString(m) }
func (*C2SWearMagic) ProtoMessage()    {}
func (*C2SWearMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{4}
}

func (m *C2SWearMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SWearMagic.Unmarshal(m, b)
}
func (m *C2SWearMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SWearMagic.Marshal(b, m, deterministic)
}
func (m *C2SWearMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SWearMagic.Merge(m, src)
}
func (m *C2SWearMagic) XXX_Size() int {
	return xxx_messageInfo_C2SWearMagic.Size(m)
}
func (m *C2SWearMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SWearMagic.DiscardUnknown(m)
}

var xxx_messageInfo_C2SWearMagic proto.InternalMessageInfo

func (m *C2SWearMagic) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SWearMagic) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type S2CWearMagic struct {
	Code                 ERRORCODEMAGIC `protobuf:"varint,1,opt,name=Code,proto3,enum=Proto.Magic.ERRORCODEMAGIC" json:"Code,omitempty"`
	LineUp               []int32        `protobuf:"varint,2,rep,packed,name=LineUp,proto3" json:"LineUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CWearMagic) Reset()         { *m = S2CWearMagic{} }
func (m *S2CWearMagic) String() string { return proto.CompactTextString(m) }
func (*S2CWearMagic) ProtoMessage()    {}
func (*S2CWearMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{5}
}

func (m *S2CWearMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CWearMagic.Unmarshal(m, b)
}
func (m *S2CWearMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CWearMagic.Marshal(b, m, deterministic)
}
func (m *S2CWearMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CWearMagic.Merge(m, src)
}
func (m *S2CWearMagic) XXX_Size() int {
	return xxx_messageInfo_S2CWearMagic.Size(m)
}
func (m *S2CWearMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CWearMagic.DiscardUnknown(m)
}

var xxx_messageInfo_S2CWearMagic proto.InternalMessageInfo

func (m *S2CWearMagic) GetCode() ERRORCODEMAGIC {
	if m != nil {
		return m.Code
	}
	return ERRORCODEMAGIC_ERR_Ok
}

func (m *S2CWearMagic) GetLineUp() []int32 {
	if m != nil {
		return m.LineUp
	}
	return nil
}

//卸下
type C2SXieXiaMagic struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=Index,proto3" json:"Index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SXieXiaMagic) Reset()         { *m = C2SXieXiaMagic{} }
func (m *C2SXieXiaMagic) String() string { return proto.CompactTextString(m) }
func (*C2SXieXiaMagic) ProtoMessage()    {}
func (*C2SXieXiaMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{6}
}

func (m *C2SXieXiaMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SXieXiaMagic.Unmarshal(m, b)
}
func (m *C2SXieXiaMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SXieXiaMagic.Marshal(b, m, deterministic)
}
func (m *C2SXieXiaMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SXieXiaMagic.Merge(m, src)
}
func (m *C2SXieXiaMagic) XXX_Size() int {
	return xxx_messageInfo_C2SXieXiaMagic.Size(m)
}
func (m *C2SXieXiaMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SXieXiaMagic.DiscardUnknown(m)
}

var xxx_messageInfo_C2SXieXiaMagic proto.InternalMessageInfo

func (m *C2SXieXiaMagic) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *C2SXieXiaMagic) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type S2CXieXiaMagic struct {
	Code                 ERRORCODEMAGIC `protobuf:"varint,1,opt,name=Code,proto3,enum=Proto.Magic.ERRORCODEMAGIC" json:"Code,omitempty"`
	LineUp               []int32        `protobuf:"varint,2,rep,packed,name=LineUp,proto3" json:"LineUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *S2CXieXiaMagic) Reset()         { *m = S2CXieXiaMagic{} }
func (m *S2CXieXiaMagic) String() string { return proto.CompactTextString(m) }
func (*S2CXieXiaMagic) ProtoMessage()    {}
func (*S2CXieXiaMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{7}
}

func (m *S2CXieXiaMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CXieXiaMagic.Unmarshal(m, b)
}
func (m *S2CXieXiaMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CXieXiaMagic.Marshal(b, m, deterministic)
}
func (m *S2CXieXiaMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CXieXiaMagic.Merge(m, src)
}
func (m *S2CXieXiaMagic) XXX_Size() int {
	return xxx_messageInfo_S2CXieXiaMagic.Size(m)
}
func (m *S2CXieXiaMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CXieXiaMagic.DiscardUnknown(m)
}

var xxx_messageInfo_S2CXieXiaMagic proto.InternalMessageInfo

func (m *S2CXieXiaMagic) GetCode() ERRORCODEMAGIC {
	if m != nil {
		return m.Code
	}
	return ERRORCODEMAGIC_ERR_Ok
}

func (m *S2CXieXiaMagic) GetLineUp() []int32 {
	if m != nil {
		return m.LineUp
	}
	return nil
}

//升级
type C2SUpLevelMagic struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SUpLevelMagic) Reset()         { *m = C2SUpLevelMagic{} }
func (m *C2SUpLevelMagic) String() string { return proto.CompactTextString(m) }
func (*C2SUpLevelMagic) ProtoMessage()    {}
func (*C2SUpLevelMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{8}
}

func (m *C2SUpLevelMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SUpLevelMagic.Unmarshal(m, b)
}
func (m *C2SUpLevelMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SUpLevelMagic.Marshal(b, m, deterministic)
}
func (m *C2SUpLevelMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SUpLevelMagic.Merge(m, src)
}
func (m *C2SUpLevelMagic) XXX_Size() int {
	return xxx_messageInfo_C2SUpLevelMagic.Size(m)
}
func (m *C2SUpLevelMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SUpLevelMagic.DiscardUnknown(m)
}

var xxx_messageInfo_C2SUpLevelMagic proto.InternalMessageInfo

func (m *C2SUpLevelMagic) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type S2CUpLevelMagic struct {
	Code                 ERRORCODEMAGIC       `protobuf:"varint,1,opt,name=Code,proto3,enum=Proto.Magic.ERRORCODEMAGIC" json:"Code,omitempty"`
	Magics               map[int32]*MagicItem `protobuf:"bytes,2,rep,name=Magics,proto3" json:"Magics,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S2CUpLevelMagic) Reset()         { *m = S2CUpLevelMagic{} }
func (m *S2CUpLevelMagic) String() string { return proto.CompactTextString(m) }
func (*S2CUpLevelMagic) ProtoMessage()    {}
func (*S2CUpLevelMagic) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{9}
}

func (m *S2CUpLevelMagic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CUpLevelMagic.Unmarshal(m, b)
}
func (m *S2CUpLevelMagic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CUpLevelMagic.Marshal(b, m, deterministic)
}
func (m *S2CUpLevelMagic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CUpLevelMagic.Merge(m, src)
}
func (m *S2CUpLevelMagic) XXX_Size() int {
	return xxx_messageInfo_S2CUpLevelMagic.Size(m)
}
func (m *S2CUpLevelMagic) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CUpLevelMagic.DiscardUnknown(m)
}

var xxx_messageInfo_S2CUpLevelMagic proto.InternalMessageInfo

func (m *S2CUpLevelMagic) GetCode() ERRORCODEMAGIC {
	if m != nil {
		return m.Code
	}
	return ERRORCODEMAGIC_ERR_Ok
}

func (m *S2CUpLevelMagic) GetMagics() map[int32]*MagicItem {
	if m != nil {
		return m.Magics
	}
	return nil
}

//一键装配
type C2SOneKeyWear struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SOneKeyWear) Reset()         { *m = C2SOneKeyWear{} }
func (m *C2SOneKeyWear) String() string { return proto.CompactTextString(m) }
func (*C2SOneKeyWear) ProtoMessage()    {}
func (*C2SOneKeyWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{10}
}

func (m *C2SOneKeyWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SOneKeyWear.Unmarshal(m, b)
}
func (m *C2SOneKeyWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SOneKeyWear.Marshal(b, m, deterministic)
}
func (m *C2SOneKeyWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SOneKeyWear.Merge(m, src)
}
func (m *C2SOneKeyWear) XXX_Size() int {
	return xxx_messageInfo_C2SOneKeyWear.Size(m)
}
func (m *C2SOneKeyWear) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SOneKeyWear.DiscardUnknown(m)
}

var xxx_messageInfo_C2SOneKeyWear proto.InternalMessageInfo

type S2COneKeyWear struct {
	LineUp               []int32  `protobuf:"varint,1,rep,packed,name=LineUp,proto3" json:"LineUp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2COneKeyWear) Reset()         { *m = S2COneKeyWear{} }
func (m *S2COneKeyWear) String() string { return proto.CompactTextString(m) }
func (*S2COneKeyWear) ProtoMessage()    {}
func (*S2COneKeyWear) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{11}
}

func (m *S2COneKeyWear) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COneKeyWear.Unmarshal(m, b)
}
func (m *S2COneKeyWear) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COneKeyWear.Marshal(b, m, deterministic)
}
func (m *S2COneKeyWear) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COneKeyWear.Merge(m, src)
}
func (m *S2COneKeyWear) XXX_Size() int {
	return xxx_messageInfo_S2COneKeyWear.Size(m)
}
func (m *S2COneKeyWear) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COneKeyWear.DiscardUnknown(m)
}

var xxx_messageInfo_S2COneKeyWear proto.InternalMessageInfo

func (m *S2COneKeyWear) GetLineUp() []int32 {
	if m != nil {
		return m.LineUp
	}
	return nil
}

//一键升级
type C2SOneKeyUplevel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SOneKeyUplevel) Reset()         { *m = C2SOneKeyUplevel{} }
func (m *C2SOneKeyUplevel) String() string { return proto.CompactTextString(m) }
func (*C2SOneKeyUplevel) ProtoMessage()    {}
func (*C2SOneKeyUplevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{12}
}

func (m *C2SOneKeyUplevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SOneKeyUplevel.Unmarshal(m, b)
}
func (m *C2SOneKeyUplevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SOneKeyUplevel.Marshal(b, m, deterministic)
}
func (m *C2SOneKeyUplevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SOneKeyUplevel.Merge(m, src)
}
func (m *C2SOneKeyUplevel) XXX_Size() int {
	return xxx_messageInfo_C2SOneKeyUplevel.Size(m)
}
func (m *C2SOneKeyUplevel) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SOneKeyUplevel.DiscardUnknown(m)
}

var xxx_messageInfo_C2SOneKeyUplevel proto.InternalMessageInfo

type S2COneKeyUplevel struct {
	Magics               map[int32]*MagicItem `protobuf:"bytes,1,rep,name=Magics,proto3" json:"Magics,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *S2COneKeyUplevel) Reset()         { *m = S2COneKeyUplevel{} }
func (m *S2COneKeyUplevel) String() string { return proto.CompactTextString(m) }
func (*S2COneKeyUplevel) ProtoMessage()    {}
func (*S2COneKeyUplevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{13}
}

func (m *S2COneKeyUplevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COneKeyUplevel.Unmarshal(m, b)
}
func (m *S2COneKeyUplevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COneKeyUplevel.Marshal(b, m, deterministic)
}
func (m *S2COneKeyUplevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COneKeyUplevel.Merge(m, src)
}
func (m *S2COneKeyUplevel) XXX_Size() int {
	return xxx_messageInfo_S2COneKeyUplevel.Size(m)
}
func (m *S2COneKeyUplevel) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COneKeyUplevel.DiscardUnknown(m)
}

var xxx_messageInfo_S2COneKeyUplevel proto.InternalMessageInfo

func (m *S2COneKeyUplevel) GetMagics() map[int32]*MagicItem {
	if m != nil {
		return m.Magics
	}
	return nil
}

//推送法术
type PushMagicChange struct {
	Option               *MagicOption `protobuf:"bytes,1,opt,name=Option,proto3" json:"Option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PushMagicChange) Reset()         { *m = PushMagicChange{} }
func (m *PushMagicChange) String() string { return proto.CompactTextString(m) }
func (*PushMagicChange) ProtoMessage()    {}
func (*PushMagicChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5fe473dc22a19c7, []int{14}
}

func (m *PushMagicChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMagicChange.Unmarshal(m, b)
}
func (m *PushMagicChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMagicChange.Marshal(b, m, deterministic)
}
func (m *PushMagicChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMagicChange.Merge(m, src)
}
func (m *PushMagicChange) XXX_Size() int {
	return xxx_messageInfo_PushMagicChange.Size(m)
}
func (m *PushMagicChange) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMagicChange.DiscardUnknown(m)
}

var xxx_messageInfo_PushMagicChange proto.InternalMessageInfo

func (m *PushMagicChange) GetOption() *MagicOption {
	if m != nil {
		return m.Option
	}
	return nil
}

func init() {
	proto.RegisterEnum("Proto.Magic.ERRORCODEMAGIC", ERRORCODEMAGIC_name, ERRORCODEMAGIC_value)
	proto.RegisterType((*C2SInitMagic)(nil), "Proto.Magic.C2SInitMagic")
	proto.RegisterType((*S2CInitMagic)(nil), "Proto.Magic.S2CInitMagic")
	proto.RegisterType((*MagicOption)(nil), "Proto.Magic.MagicOption")
	proto.RegisterMapType((map[int32]*MagicItem)(nil), "Proto.Magic.MagicOption.MagicsEntry")
	proto.RegisterType((*MagicItem)(nil), "Proto.Magic.MagicItem")
	proto.RegisterType((*C2SWearMagic)(nil), "Proto.Magic.C2SWearMagic")
	proto.RegisterType((*S2CWearMagic)(nil), "Proto.Magic.S2CWearMagic")
	proto.RegisterType((*C2SXieXiaMagic)(nil), "Proto.Magic.C2SXieXiaMagic")
	proto.RegisterType((*S2CXieXiaMagic)(nil), "Proto.Magic.S2CXieXiaMagic")
	proto.RegisterType((*C2SUpLevelMagic)(nil), "Proto.Magic.C2SUpLevelMagic")
	proto.RegisterType((*S2CUpLevelMagic)(nil), "Proto.Magic.S2CUpLevelMagic")
	proto.RegisterMapType((map[int32]*MagicItem)(nil), "Proto.Magic.S2CUpLevelMagic.MagicsEntry")
	proto.RegisterType((*C2SOneKeyWear)(nil), "Proto.Magic.C2SOneKeyWear")
	proto.RegisterType((*S2COneKeyWear)(nil), "Proto.Magic.S2COneKeyWear")
	proto.RegisterType((*C2SOneKeyUplevel)(nil), "Proto.Magic.C2SOneKeyUplevel")
	proto.RegisterType((*S2COneKeyUplevel)(nil), "Proto.Magic.S2COneKeyUplevel")
	proto.RegisterMapType((map[int32]*MagicItem)(nil), "Proto.Magic.S2COneKeyUplevel.MagicsEntry")
	proto.RegisterType((*PushMagicChange)(nil), "Proto.Magic.PushMagicChange")
}

func init() {
	proto.RegisterFile("magic.proto", fileDescriptor_d5fe473dc22a19c7)
}

var fileDescriptor_d5fe473dc22a19c7 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0xe1, 0x8a, 0xd3, 0x40,
	0x10, 0x36, 0x89, 0x09, 0x38, 0x69, 0xd3, 0xb8, 0x1c, 0x25, 0xe8, 0x9f, 0x1a, 0x04, 0xab, 0x48,
	0x4f, 0x56, 0x11, 0x11, 0x7f, 0x5c, 0x5d, 0xc3, 0x19, 0xbc, 0x36, 0x75, 0x63, 0xb9, 0x53, 0x90,
	0x12, 0xed, 0x72, 0x17, 0xae, 0x4d, 0x43, 0x9b, 0x1e, 0xf6, 0x8d, 0x7c, 0x02, 0x5f, 0xc5, 0xd7,
	0x91, 0xcc, 0xe6, 0x72, 0x4d, 0xed, 0xfd, 0x28, 0xe8, 0xfd, 0x69, 0x77, 0x66, 0xbe, 0x6f, 0xe6,
	0xcb, 0x97, 0xc9, 0x82, 0x39, 0x8d, 0x4e, 0xe3, 0xef, 0x9d, 0x74, 0x3e, 0xcb, 0x66, 0xc4, 0x1c,
	0xe4, 0x7f, 0x9d, 0x5e, 0x9e, 0x72, 0x2d, 0xa8, 0x31, 0x1a, 0xfa, 0x49, 0x9c, 0xc9, 0xf8, 0x00,
	0x6a, 0x21, 0x65, 0x65, 0x4c, 0x9e, 0x81, 0x11, 0xa4, 0x59, 0x3c, 0x4b, 0x1c, 0xa5, 0xa5, 0xb4,
	0x4d, 0xea, 0x74, 0xd6, 0xd8, 0xf2, 0x57, 0xd6, 0x79, 0x81, 0x73, 0x7f, 0x29, 0x60, 0xae, 0xe5,
	0xc9, 0x1b, 0x30, 0x30, 0x5c, 0x38, 0x4a, 0x4b, 0x6b, 0x9b, 0xf4, 0xe1, 0x75, 0x1d, 0xe4, 0x79,
	0xe1, 0x25, 0xd9, 0x7c, 0xc5, 0x0b, 0x0e, 0x69, 0x82, 0x71, 0x14, 0x27, 0x62, 0x98, 0x3a, 0x6a,
	0x4b, 0x6b, 0xeb, 0xbc, 0x88, 0xee, 0x7d, 0x2c, 0x86, 0x48, 0x38, 0xb1, 0x41, 0x3b, 0x17, 0x2b,
	0xd4, 0xa8, 0xf3, 0xfc, 0x48, 0x9e, 0x82, 0x7e, 0x11, 0x4d, 0x96, 0xc2, 0x51, 0x51, 0x77, 0xf3,
	0xef, 0xa9, 0x7e, 0x26, 0xa6, 0x5c, 0x82, 0x5e, 0xab, 0xaf, 0x14, 0x97, 0xc1, 0x9d, 0x32, 0x4f,
	0x2c, 0x50, 0xfd, 0x71, 0xd1, 0x4f, 0xf5, 0xc7, 0x64, 0x0f, 0xf4, 0x23, 0x71, 0x21, 0x26, 0xd8,
	0x4e, 0xe7, 0x32, 0xc8, 0xc7, 0xf6, 0x97, 0x53, 0x47, 0x93, 0x63, 0xfb, 0xcb, 0xa9, 0xfb, 0x02,
	0xfd, 0x3c, 0x16, 0xd1, 0x5c, 0xfa, 0xb7, 0xa5, 0x8f, 0x9f, 0x8c, 0xc5, 0x8f, 0xcb, 0x3e, 0x18,
	0xb8, 0xc7, 0xe8, 0xfa, 0x15, 0x6b, 0x1f, 0x6e, 0xb3, 0xd9, 0x58, 0x20, 0xcf, 0xa2, 0xf7, 0x2b,
	0xda, 0x3d, 0xce, 0x03, 0xce, 0x82, 0x77, 0x5e, 0xaf, 0x7b, 0xe8, 0x33, 0x8e, 0xc0, 0xeb, 0x6c,
	0x72, 0x5f, 0x82, 0xc5, 0x68, 0x78, 0x12, 0x8b, 0x93, 0x38, 0xda, 0x45, 0xd0, 0x67, 0xb0, 0x42,
	0xca, 0xd6, 0x79, 0xff, 0x4c, 0xd2, 0x03, 0x68, 0x30, 0x1a, 0x0e, 0x53, 0x74, 0x70, 0xab, 0x26,
	0xf7, 0xb7, 0x02, 0x8d, 0x90, 0xb2, 0x0a, 0x66, 0xe7, 0xf9, 0x07, 0xe5, 0xde, 0xa9, 0xb8, 0x77,
	0xed, 0x0a, 0x65, 0xa3, 0xfd, 0xb6, 0xdd, 0xfb, 0x1f, 0x3b, 0xd6, 0x80, 0x3a, 0xa3, 0x61, 0x90,
	0x88, 0x0f, 0x62, 0x95, 0xbf, 0x6e, 0xf7, 0x11, 0xd4, 0x43, 0xca, 0xae, 0x12, 0x6b, 0xb6, 0x29,
	0x15, 0xdb, 0x08, 0xd8, 0x25, 0x73, 0x98, 0x4e, 0x72, 0xe5, 0xee, 0x4f, 0x05, 0xec, 0x92, 0x5d,
	0x24, 0x49, 0x77, 0xe3, 0x7b, 0x7b, 0xbc, 0xf9, 0xdc, 0x15, 0xf8, 0x4d, 0x3d, 0x38, 0x83, 0xc6,
	0x60, 0xb9, 0x38, 0xc3, 0x1a, 0x3b, 0x8b, 0x92, 0x53, 0xb1, 0xfb, 0xd5, 0xf2, 0xe4, 0x2b, 0x58,
	0xd5, 0x57, 0x4d, 0x00, 0x0c, 0x8f, 0xf3, 0x51, 0x70, 0x6e, 0xdf, 0x22, 0x77, 0xa1, 0x8e, 0xd5,
	0x51, 0x3f, 0xc0, 0xa2, 0xad, 0x90, 0x3d, 0xb0, 0x65, 0x6a, 0xd0, 0xe5, 0xdd, 0x1e, 0x1e, 0x6d,
	0x95, 0x34, 0x81, 0x5c, 0x02, 0xbd, 0xfe, 0xe1, 0xa7, 0xf7, 0x32, 0xaf, 0xbd, 0xb5, 0xbe, 0xd4,
	0xf6, 0xf1, 0x8a, 0x1c, 0xe1, 0x75, 0xf9, 0xcd, 0xc0, 0xe0, 0xf9, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1d, 0x3b, 0xdc, 0x5c, 0x3e, 0x05, 0x00, 0x00,
}
