// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rank.proto

package proto_rank

import (
"xfx/proto/proto_public"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RankType int32

const (
	RankType_none           RankType = 0
	RankType_perfect        RankType = 1
	RankType_grow           RankType = 2
	RankType_guild_battle   RankType = 3
	RankType_drawrank       RankType = 4
	RankType_rechargerank   RankType = 5
	RankType_climbtower     RankType = 6
	RankType_thecompetition RankType = 7
	RankType_arena          RankType = 8
	RankType_tianti         RankType = 9
	RankType_fish           RankType = 10
)

var RankType_name = map[int32]string{
	0:  "none",
	1:  "perfect",
	2:  "grow",
	3:  "guild_battle",
	4:  "drawrank",
	5:  "rechargerank",
	6:  "climbtower",
	7:  "thecompetition",
	8:  "arena",
	9:  "tianti",
	10: "fish",
}

var RankType_value = map[string]int32{
	"none":           0,
	"perfect":        1,
	"grow":           2,
	"guild_battle":   3,
	"drawrank":       4,
	"rechargerank":   5,
	"climbtower":     6,
	"thecompetition": 7,
	"arena":          8,
	"tianti":         9,
	"fish":           10,
}

func (x RankType) String() string {
	return proto.EnumName(RankType_name, int32(x))
}

func (RankType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28127d302aca29e8, []int{0}
}

type C2SRankData struct {
	Type                 RankType `protobuf:"varint,1,opt,name=type,proto3,enum=Proto.Rank.RankType" json:"type,omitempty"`
	Id                   []int32  `protobuf:"varint,2,rep,packed,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SRankData) Reset()         { *m = C2SRankData{} }
func (m *C2SRankData) String() string { return proto.CompactTextString(m) }
func (*C2SRankData) ProtoMessage()    {}
func (*C2SRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_28127d302aca29e8, []int{0}
}

func (m *C2SRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SRankData.Unmarshal(m, b)
}
func (m *C2SRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SRankData.Marshal(b, m, deterministic)
}
func (m *C2SRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SRankData.Merge(m, src)
}
func (m *C2SRankData) XXX_Size() int {
	return xxx_messageInfo_C2SRankData.Size(m)
}
func (m *C2SRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SRankData.DiscardUnknown(m)
}

var xxx_messageInfo_C2SRankData proto.InternalMessageInfo

func (m *C2SRankData) GetType() RankType {
	if m != nil {
		return m.Type
	}
	return RankType_none
}

func (m *C2SRankData) GetId() []int32 {
	if m != nil {
		return m.Id
	}
	return nil
}

type S2CRankData struct {
	Type                 int32       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Rankings             []*RankItem `protobuf:"bytes,2,rep,name=rankings,proto3" json:"rankings,omitempty"`
	Self                 *RankItem   `protobuf:"bytes,3,opt,name=self,proto3" json:"self,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2CRankData) Reset()         { *m = S2CRankData{} }
func (m *S2CRankData) String() string { return proto.CompactTextString(m) }
func (*S2CRankData) ProtoMessage()    {}
func (*S2CRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_28127d302aca29e8, []int{1}
}

func (m *S2CRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRankData.Unmarshal(m, b)
}
func (m *S2CRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRankData.Marshal(b, m, deterministic)
}
func (m *S2CRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRankData.Merge(m, src)
}
func (m *S2CRankData) XXX_Size() int {
	return xxx_messageInfo_S2CRankData.Size(m)
}
func (m *S2CRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRankData.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRankData proto.InternalMessageInfo

func (m *S2CRankData) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *S2CRankData) GetRankings() []*RankItem {
	if m != nil {
		return m.Rankings
	}
	return nil
}

func (m *S2CRankData) GetSelf() *RankItem {
	if m != nil {
		return m.Self
	}
	return nil
}

// 排行榜
type RankItem struct {
	Rank                 int64                          `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Score                int64                          `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Player               *proto_public.CommonPlayerInfo `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Guild                *GuildRankItem                 `protobuf:"bytes,4,opt,name=guild,proto3" json:"guild,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *RankItem) Reset()         { *m = RankItem{} }
func (m *RankItem) String() string { return proto.CompactTextString(m) }
func (*RankItem) ProtoMessage()    {}
func (*RankItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_28127d302aca29e8, []int{2}
}

func (m *RankItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankItem.Unmarshal(m, b)
}
func (m *RankItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankItem.Marshal(b, m, deterministic)
}
func (m *RankItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankItem.Merge(m, src)
}
func (m *RankItem) XXX_Size() int {
	return xxx_messageInfo_RankItem.Size(m)
}
func (m *RankItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RankItem.DiscardUnknown(m)
}

var xxx_messageInfo_RankItem proto.InternalMessageInfo

func (m *RankItem) GetRank() int64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *RankItem) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *RankItem) GetPlayer() *proto_public.CommonPlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *RankItem) GetGuild() *GuildRankItem {
	if m != nil {
		return m.Guild
	}
	return nil
}

type GuildRankItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level                int32    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Banner               int32    `protobuf:"varint,4,opt,name=banner,proto3" json:"banner,omitempty"`
	BannerColor          int32    `protobuf:"varint,5,opt,name=banner_color,json=bannerColor,proto3" json:"banner_color,omitempty"`
	Master               int64    `protobuf:"varint,6,opt,name=master,proto3" json:"master,omitempty"`
	CurMemberNum         int32    `protobuf:"varint,7,opt,name=cur_member_num,json=curMemberNum,proto3" json:"cur_member_num,omitempty"`
	MasterFaceId         int32    `protobuf:"varint,8,opt,name=master_face_id,json=masterFaceId,proto3" json:"master_face_id,omitempty"`
	MasterFaceSlotId     int32    `protobuf:"varint,9,opt,name=master_face_slot_id,json=masterFaceSlotId,proto3" json:"master_face_slot_id,omitempty"`
	MasterLevel          int32    `protobuf:"varint,10,opt,name=master_level,json=masterLevel,proto3" json:"master_level,omitempty"`
	MasterName           string   `protobuf:"bytes,11,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuildRankItem) Reset()         { *m = GuildRankItem{} }
func (m *GuildRankItem) String() string { return proto.CompactTextString(m) }
func (*GuildRankItem) ProtoMessage()    {}
func (*GuildRankItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_28127d302aca29e8, []int{3}
}

func (m *GuildRankItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuildRankItem.Unmarshal(m, b)
}
func (m *GuildRankItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuildRankItem.Marshal(b, m, deterministic)
}
func (m *GuildRankItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuildRankItem.Merge(m, src)
}
func (m *GuildRankItem) XXX_Size() int {
	return xxx_messageInfo_GuildRankItem.Size(m)
}
func (m *GuildRankItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GuildRankItem.DiscardUnknown(m)
}

var xxx_messageInfo_GuildRankItem proto.InternalMessageInfo

func (m *GuildRankItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GuildRankItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GuildRankItem) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GuildRankItem) GetBanner() int32 {
	if m != nil {
		return m.Banner
	}
	return 0
}

func (m *GuildRankItem) GetBannerColor() int32 {
	if m != nil {
		return m.BannerColor
	}
	return 0
}

func (m *GuildRankItem) GetMaster() int64 {
	if m != nil {
		return m.Master
	}
	return 0
}

func (m *GuildRankItem) GetCurMemberNum() int32 {
	if m != nil {
		return m.CurMemberNum
	}
	return 0
}

func (m *GuildRankItem) GetMasterFaceId() int32 {
	if m != nil {
		return m.MasterFaceId
	}
	return 0
}

func (m *GuildRankItem) GetMasterFaceSlotId() int32 {
	if m != nil {
		return m.MasterFaceSlotId
	}
	return 0
}

func (m *GuildRankItem) GetMasterLevel() int32 {
	if m != nil {
		return m.MasterLevel
	}
	return 0
}

func (m *GuildRankItem) GetMasterName() string {
	if m != nil {
		return m.MasterName
	}
	return ""
}

func init() {
	proto.RegisterEnum("Proto.Rank.RankType", RankType_name, RankType_value)
	proto.RegisterType((*C2SRankData)(nil), "Proto.Rank.C2SRankData")
	proto.RegisterType((*S2CRankData)(nil), "Proto.Rank.S2CRankData")
	proto.RegisterType((*RankItem)(nil), "Proto.Rank.RankItem")
	proto.RegisterType((*GuildRankItem)(nil), "Proto.Rank.GuildRankItem")
}

func init() {
	proto.RegisterFile("rank.proto", fileDescriptor_28127d302aca29e8)
}

var fileDescriptor_28127d302aca29e8 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xc1, 0x6e, 0xd4, 0x3c,
	0x10, 0xfe, 0x37, 0xbb, 0xd9, 0x66, 0x27, 0xdb, 0x95, 0xe5, 0xbf, 0x42, 0x81, 0x03, 0x94, 0x15,
	0x87, 0x0a, 0x89, 0x16, 0x15, 0x89, 0x07, 0x60, 0x11, 0x55, 0x24, 0xa8, 0xaa, 0x94, 0x13, 0x97,
	0xc8, 0x49, 0x66, 0xb7, 0x56, 0x63, 0x3b, 0x72, 0x1c, 0xaa, 0x1e, 0x78, 0x14, 0x2e, 0xbc, 0x16,
	0x2f, 0x83, 0x3c, 0x0e, 0x6d, 0x11, 0xe2, 0xb2, 0x3b, 0xf3, 0xcd, 0x37, 0xf3, 0x7d, 0x1e, 0x3b,
	0x00, 0x56, 0xe8, 0xeb, 0xe3, 0xce, 0x1a, 0x67, 0x38, 0x5c, 0xf8, 0xbf, 0xe3, 0x42, 0xe8, 0xeb,
	0x27, 0xcb, 0x6e, 0xa8, 0x5a, 0x59, 0x87, 0xca, 0xfa, 0x0c, 0xd2, 0xcd, 0xe9, 0xa5, 0x2f, 0xbc,
	0x17, 0x4e, 0xf0, 0x23, 0x98, 0xb9, 0xdb, 0x0e, 0xb3, 0xc9, 0xe1, 0xe4, 0x68, 0x75, 0x7a, 0x70,
	0x7c, 0xdf, 0x47, 0x3f, 0x9f, 0x6f, 0x3b, 0x2c, 0x88, 0xc1, 0x57, 0x10, 0xe5, 0x4d, 0x16, 0x1d,
	0x4e, 0x8f, 0xe2, 0x22, 0xca, 0x9b, 0xf5, 0x37, 0x48, 0x2f, 0x4f, 0x37, 0x77, 0x83, 0xf8, 0x83,
	0x41, 0xf1, 0xd8, 0xf2, 0x1a, 0x12, 0xef, 0x49, 0xea, 0x5d, 0x4f, 0x8d, 0xe9, 0xdf, 0x02, 0xb9,
	0x43, 0x55, 0xdc, 0xb1, 0xbc, 0x9d, 0x1e, 0xdb, 0x6d, 0x36, 0x3d, 0x9c, 0xfc, 0x93, 0x4d, 0x8c,
	0xf5, 0xf7, 0x09, 0x24, 0xbf, 0x21, 0x2f, 0xee, 0x47, 0x90, 0xf8, 0xb4, 0xa0, 0x98, 0x1f, 0x40,
	0xdc, 0xd7, 0xc6, 0x62, 0x16, 0x11, 0x18, 0x12, 0xfe, 0x16, 0xe6, 0x5d, 0x2b, 0x6e, 0xd1, 0x8e,
	0x12, 0x4f, 0x47, 0x89, 0x8b, 0xb0, 0xa3, 0x8d, 0x51, 0xca, 0xe8, 0x0b, 0x62, 0xe4, 0x7a, 0x6b,
	0x8a, 0x91, 0xcd, 0x4f, 0x20, 0xde, 0x0d, 0xb2, 0x6d, 0xb2, 0x19, 0xb5, 0x3d, 0x7e, 0xe8, 0xec,
	0xcc, 0x17, 0xee, 0xec, 0x05, 0xde, 0xfa, 0x67, 0x04, 0xfb, 0x7f, 0x14, 0xfc, 0x02, 0x65, 0x33,
	0x5a, 0x8c, 0x64, 0xe3, 0x4d, 0x6b, 0xa1, 0x82, 0xbf, 0x45, 0x41, 0xb1, 0x37, 0xdd, 0xe2, 0x57,
	0x6c, 0xc9, 0x5d, 0x5c, 0x84, 0x84, 0x3f, 0x82, 0x79, 0x25, 0xb4, 0x46, 0x4b, 0xea, 0x71, 0x31,
	0x66, 0xfc, 0x39, 0x2c, 0x43, 0x54, 0xd6, 0xa6, 0x35, 0x36, 0x8b, 0xa9, 0x9a, 0x06, 0x6c, 0xe3,
	0x21, 0xdf, 0xaa, 0x44, 0xef, 0xd0, 0x66, 0x73, 0x12, 0x1e, 0x33, 0xfe, 0x02, 0x56, 0xf5, 0x60,
	0x4b, 0x85, 0xaa, 0x42, 0x5b, 0xea, 0x41, 0x65, 0x7b, 0xd4, 0xbc, 0xac, 0x07, 0xfb, 0x89, 0xc0,
	0xf3, 0x41, 0x79, 0x56, 0xe0, 0x97, 0x5b, 0x51, 0x63, 0x29, 0x9b, 0x2c, 0x09, 0xac, 0x80, 0x7e,
	0x10, 0x35, 0xe6, 0x0d, 0x7f, 0x05, 0xff, 0x3f, 0x64, 0xf5, 0xad, 0x71, 0x9e, 0xba, 0x20, 0x2a,
	0xbb, 0xa7, 0x5e, 0xb6, 0xc6, 0xe5, 0x8d, 0x77, 0x3d, 0xd2, 0xc3, 0x51, 0x21, 0xb8, 0x0e, 0xd8,
	0x47, 0x3a, 0xf0, 0x33, 0x18, 0xd3, 0x92, 0x36, 0x94, 0xd2, 0x86, 0x20, 0x40, 0xe7, 0x42, 0xe1,
	0xcb, 0x1f, 0xe3, 0xed, 0xfb, 0xf7, 0xc9, 0x13, 0x98, 0x69, 0xa3, 0x91, 0xfd, 0xc7, 0x53, 0xd8,
	0xeb, 0xd0, 0x6e, 0xb1, 0x76, 0x6c, 0xe2, 0xe1, 0x9d, 0x35, 0x37, 0x2c, 0xe2, 0x0c, 0x96, 0x74,
	0x29, 0x65, 0x25, 0x9c, 0x6b, 0x91, 0x4d, 0xf9, 0x12, 0x92, 0xc6, 0x8a, 0x1b, 0xff, 0x50, 0xd8,
	0xcc, 0xd7, 0x2d, 0xd6, 0x57, 0xc2, 0xee, 0x90, 0x90, 0x98, 0xaf, 0x00, 0xea, 0x56, 0xaa, 0xca,
	0x99, 0x1b, 0xb4, 0x6c, 0xce, 0x39, 0xac, 0xdc, 0x15, 0xd6, 0x46, 0x75, 0xe8, 0xa4, 0x93, 0x46,
	0xb3, 0x3d, 0xbe, 0x80, 0x58, 0x58, 0xd4, 0x82, 0x25, 0x1c, 0x60, 0xee, 0xa4, 0xd0, 0x4e, 0xb2,
	0x85, 0x97, 0xdd, 0xca, 0xfe, 0x8a, 0xc1, 0xbb, 0xfd, 0x2f, 0xe9, 0x09, 0x7d, 0x74, 0xa5, 0x9f,
	0x5a, 0xcd, 0x29, 0x7e, 0xf3, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x1b, 0x79, 0xa0, 0xa8, 0x03,
	0x00, 0x00,
}
